### ISSUE TITLE
Framework 4.8 pulling "Unable to load DLL 'LibTorchSharp': The specified module could not be found"

### ISSUE THREAD

**Issue by dturnerADM** [dotnet/TorchSharp#1006]
Long story but we need to run a pre-trained TorchSharp model in a framework app.
All nugets and dependencies are present. Other ML.NET ops are good.
Maybe a hard-coded path that's assuming NET6+? i.e. is TorchSharp looking for the libtorch-cpu DLL at a certain place?
Anyone know of a work around? Or is this related to the VS version issue?
VS Pro 17.6.1
Nuget TorchSharp 0.100.0
Nuget libtorch-cpu-win-x64 2.0.1.1

DllNotFoundException: Unable to load DLL 'LibTorchSharp': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by ChengYen-Tang** [comment]
@dturnerADM, Can you provide some code?

**Comment by LamerTex** [comment]
I'm working in more or less with the same setup and all is working well. 
I think your problem is the second nuget package, you should install 
- "Nuget TorchSharp 0.100.0" 

and then one between 
- "Nuget TorchSharp-cpu 0.100.0"
- "Nuget TorchSharp-cuda-windows 0.100.0"
- "Nuget TorchSharp-cuda-linux 0.100.0"

![image](https://github.com/dotnet/TorchSharp/assets/5462278/eea4743b-c7d6-4f38-83ea-61615b8b62ec)

the "Nuget libtorch-cpu-win-x64 2.0.1.1" is not needed (and maybe also conflict in some way with the "official" TorchSharp packages but I don't know this).

**Comment by NiklasGustafsson** [comment]
@dturnerADM has it right -- TorchSharp + libtorch-xxx is correct. 

It's more convenient to choose one of the packages from @LamerTex' second list (which pulls in TorchSharp and one of the libtorch packages).

**Comment by NiklasGustafsson** [comment]
> Long story but we need to run a pre-trained TorchSharp model in a framework app. All nugets and dependencies are present. Other ML.NET ops are good. Maybe a hard-coded path that's assuming NET6+? i.e. is TorchSharp looking for the libtorch-cpu DLL at a certain place?

No, there's no hard-coded path. It looks for the libraries in the normal locations, as well as the package folders, if it finds them (that would be more of a development scenario than a deployed scenario). 

>All nugets and dependencies are present.

On the system or in the binaries folder? Check the contents of the output binaries folder; the error means that either the LibTorchSharp.dll or one of its dependencies are missing, so a listing of what's there (with file sizes) would be helpful. The best way to get precise file sizes is to use the 'dir' command from CMD.

**Comment by Ev4sio** [comment]
Ok thanks for the info, but how do I do if I want to alternate the use of CPU and GPU to make performance comparisons?

**Comment by NiklasGustafsson** [comment]
The CUDA backend contains all of the CPU backend, but they are built with different dependencies, so you can take a dependency on both. Just take a dependency on **either** TorchSharp-cpu or TorchSharp-cuda-windows and don't worry about the libtorch-* packages, they will be pulled in as dependencies.

**Comment by NiklasGustafsson** [comment]
I would also recommend manually deleting the entire 'bin' folder, recursively, so that any residue from the double backend dependency is cleaned up. I'm not sure a 'dotnet clean' or 'Clean Solution' is enough.

**Comment by Ev4sio** [comment]
Thank you for your suggestion. I've followed your advice and deleted the entire 'bin' folder manually. I've also tried uninstalling and reinstalling the 'libtorch' package from my project. Despite these steps, I'm still encountering the same issue. Interestingly, there's no reference to the 'libtorch' DLLs in my .csproj file even after reinstalling the package.

This is the 'packages' repository for the solution:
![packages](https://github.com/dotnet/TorchSharp/assets/86192911/652f6aed-27fb-404a-89b0-6300c70559d3)

The .csproj file:
![csproj](https://github.com/dotnet/TorchSharp/assets/86192911/85f709d6-8258-4b1a-a048-1def63c717c5)

I would appreciate any further guidance.

**Comment by LamerTex** [comment]
In the .csproj file, I only see the reference to TorchSharp, you should also have one between "TorchSharp-cpu" or "TorchSharp-cuda-windows/linux". It's normal that there is no reference to the 'libtorch' DLLs in it. 
This is my nuget explorer and .csproj:
![image](https://github.com/dotnet/TorchSharp/assets/5462278/2e20e182-4682-4e3d-869a-0cfae621b2be)


I think your problem could be the compilation platform. 
I can't explain the technical reason (maybe @NiklasGustafsson can enlighten both of us), but to make the project works correctly we had to set the platform of the project to x64.
![image](https://github.com/dotnet/TorchSharp/assets/5462278/22247fc9-1306-4b95-bfee-16be6031fa98)

If left to "AnyCPU" the "LibTorchSharp.dll" which is in "...nuget\packages\torchsharp\0.100.x\runtimes\ **win-x64** \native" is not copied to the final executable folder and the application would not work



P.S. Probably unrelated to the issue, but I suggest you [migrate from packages.config to PackageReference](https://learn.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference), it works much better for us, in particular, if you have some "library" projects which are used in more than one solution, in that case, the "HintPath" of the packages.config would always break the compilation of the project.
You just need to "right-click on the References node or the packages.config file in Solution Explorer and select Migrate packages.config to PackageReference"

**Comment by NiklasGustafsson** [comment]
Any CPU works for me (from the TorchSharpExamples repo):

![image](https://github.com/dotnet/TorchSharp/assets/1791495/00b16c17-596b-476b-9a1f-471b35ea8af8)

**Comment by LamerTex** [comment]
I confirm that TorchSharpExamples repo works correctly with Any CPU also on my computer.

I also re-confirm that a newly created and empty WPF app targeting ".Net Framework" (4.6.2 in my case) without anything else 
([SimpleTorchSharpApp.zip](https://github.com/dotnet/TorchSharp/files/11760452/SimpleTorchSharpApp.zip) )
gives execution error in "Any CPU" but works correctly with "x64" as the Platform.


The first run, with the default build option "Prefer 32bit" set, gives this error:
![image](https://github.com/dotnet/TorchSharp/assets/5462278/0bb7b05e-7fca-43c0-b692-fbcd3b4a0ee6)

Removing the "Prefer 32bit" option but keeping the Platform as "Any CPU" gives this error:
![image](https://github.com/dotnet/TorchSharp/assets/5462278/d574a469-c8a2-4845-b16c-e9dcfcbf543c)

Finally changing the Platform to "x64" works correctly:
![image](https://github.com/dotnet/TorchSharp/assets/5462278/2c6fdae0-45fa-47c0-b126-9bb4635a7bb0)

There is also a warning from the compiler that alerts about the problem until you change the Platform to "x64"
![image](https://github.com/dotnet/TorchSharp/assets/5462278/1aca3342-cea9-46d8-a726-377e57a82ec8)

**Comment by NiklasGustafsson** [comment]
I just realized that in TorchSharpExample uses .NET 6.0, not .NET FX, so ignore my earlier comment. This seems to be an issue specific to .NET FX. Worth commenting on it somewhere conspicuous.

Glad we're getting to the bottom of this.

**Comment by NiklasGustafsson** [comment]
> Worth commenting on it somewhere conspicuous.

It's in the README now. High up near the top.

**Comment by NiklasGustafsson** [comment]
> I would appreciate any further guidance.

Don't import 'TorchSharp' import 'Torch-cpu' or 'Torch-cuda-windows' (but not both). You need the libtorch backend to run.

As it says in the README:

```
We recommend using one of the 'bundled' packages: TorchSharp-cpu, TorchSharp-cuda-windows, or TorchSharp-cuda-linux. They will pull in the right libtorch backends.
```

**Comment by Ev4sio** [comment]
I first tried to remove the TorchSharp package to avoid redundancy but it seems to me that it was installed automatically with the _TorchSharp-cuda-windows_ package:
![redundant](https://github.com/dotnet/TorchSharp/assets/86192911/c06fe858-3325-4cd0-b75f-d6ba457d3b20)

I then migrated from packages.config to PackageReference... and **that solved the issue**!

And now I see better the dependencies between packages and transitive packages:
![transitive packages](https://github.com/dotnet/TorchSharp/assets/86192911/ea3b3a35-df45-429e-8003-5fb6ed1e8b44)
PS: I also work with "x64" as the Platform, but that was already the case, I didn't change that.

Thank you all so much for your assistance. Your guidance and suggestions were very helpful in resolving my issue. I truly appreciate the time and effort you took to help me.

**Comment by NiklasGustafsson** [comment]
Great to hear that it works.

**Comment by NiklasGustafsson** [comment]
@dturnerADM -- I'll leave it to you to confirm that this works for you, too, and close the issue if it does.

**Comment by NiklasGustafsson** [comment]
BTW, all those parts you see... that's because NuGet-hosted packages cannot be larger than 250MB, so we have to split them up in many and then stitch them back together when downloaded. Ugly business, and it's a total hack, but it works.

**Comment by NiklasGustafsson** [comment]
That's what the FileRestitcher project in the repo is about.

**Comment by NiklasGustafsson** [comment]
@dturnerADM -- any input?
