### ISSUE TITLE
read  model error 

### ISSUE THREAD

**Issue by hwef** [dotnet/TorchSharp#1008]
**error descr:** 
PytorchStreamReader failed reading zip archive: failed finding central directory
Exception raised from valid at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\caffe2\serialize\inline_container.cc:183 (most recent call first):
00007FFBE1F5AD0200007FFBE1F5ACA0 c10.dll!
python code to export model  file
```
model = Model(image_size, checkpoint, model_type)
model_trace = torch.jit.trace(model, input_image_torch)

f = open("model_weights.dat", "wb")

exportsd.save_state_dict(model_trace.to("cpu").state_dict(), f)
f.close()
```
c# code   to read  model file

```
  torch.nn.Module module = null;
  module = torch.nn.Module.Load(@"model_weights.dat");
```

**Comment by NiklasGustafsson** [comment]
See: https://github.com/dotnet/TorchSharp/wiki/Sharing-Model-Data-between-PyTorch-and-TorchSharp

To load weights in TorchSharp, you have to first create a module instance with the right architecture, then load the weights.

**Comment by NiklasGustafsson** [comment]
@hwef -- does this address your question?

**Comment by hwef** [comment]
sry it cannot help me  to sovle the question

**Comment by NiklasGustafsson** [comment]
Can you share the modified code that is still not working?

**Comment by NiklasGustafsson** [comment]
No reply for four months, so I'm closing the issue.
