### ISSUE TITLE
LazyModuleMixin?

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/TorchSharp#1019]
If there is sufficient interest, this has yet to be implemented

[LazyModuleMixin](https://pytorch.org/docs/stable/_modules/torch/nn/modules/lazy.html#LazyModuleMixin)
> A mixin for modules that lazily initialize parameters, also known as "lazy modules."

https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/lazy.py

**Comment by NiklasGustafsson** [comment]
@GeorgeS2019 -- I'll close this one unless you have instructions on how to accomplish it in .NET

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson 
The original [purpose for LazyModuleMixin](https://github.com/pytorch-labs/tensordict#lazy-preallocation) was to evaluate [TensorDict.](https://github.com/dotnet/TorchSharp/discussions/1020)

Evaluation of TensorDict was for TorchRL. 

Tentatively lazy-preallocation could be left out with lower priority.
