### ISSUE TITLE
Implement iterable-style Datasets

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/TorchSharp#1028]
Pytorch supports [Two types of Dataset](https://pytorch.org/docs/stable/data.html#dataset-types)

1. [map-style datasets](https://pytorch.org/docs/stable/data.html#map-style-datasets),
2. [iterable-style datasets](https://pytorch.org/docs/stable/data.html#iterable-style-datasets).

Looking through the Torchsharp Dataset ussages including the recent [Synthetic dataset example](https://github.com/dotnet/TorchSharpExamples/blob/main/tutorials/CSharp/synthetic_data.ipynb)

Am I right that TorchSharp supports only the **Type ONE** dataset?

**Comment by NiklasGustafsson** [comment]
That is correct. It was added because of the randomization control that map-style datasets provide. Iterable datasets should be straight-forward to implement, too.

**Comment by NiklasGustafsson** [comment]
I'll track that in this issue.
