### ISSUE TITLE
.NET framework

### ISSUE THREAD

**Issue by Mariob96** [dotnet/TorchSharp#1030]
I have a project targetting .NET framework 4.8,
is there a way to make it compatible?
Thank you in advance!

**Comment by NiklasGustafsson** [comment]
Yes, TorchSharp supports .NET FX 4.7.2 and later. Are you running into any specific issues with it?

**Comment by NiklasGustafsson** [comment]
@Mariob96 -- Ping! :-)

**Comment by Mariob96** [comment]
Sorry! I forgot go answer! There was no problem in the end
