### ISSUE TITLE
TorchSharp TensorFactory

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/TorchSharp#1031]
# [TENSOR CREATION API](https://pytorch.org/cppdocs/notes/tensor_creation.html#tensor-creation-api)

## Factory Functions
- [arrange](https://pytorch.org/docs/stable/torch.html#torch.arange): Returns a tensor with a sequence of integers,

- [empty](https://pytorch.org/docs/stable/torch.html#torch.empty): Returns a tensor with uninitialized values,

- [eye](https://pytorch.org/docs/stable/torch.html#torch.eye): Returns an identity matrix,

- [full](https://pytorch.org/docs/stable/torch.html#torch.full): Returns a tensor filled with a single value,

- [linspace](https://pytorch.org/docs/stable/torch.html#torch.linspace): Returns a tensor with values linearly spaced in some interval,

- [logspace](https://pytorch.org/docs/stable/torch.html#torch.logspace): Returns a tensor with values logarithmically spaced in some interval,

- [ones](https://pytorch.org/docs/stable/torch.html#torch.ones): Returns a tensor filled with all ones,

- [rand](https://pytorch.org/docs/stable/torch.html#torch.rand): Returns a tensor filled with values drawn from a uniform distribution on [0, 1).

- [randint](https://pytorch.org/docs/stable/torch.html#torch.randint): Returns a tensor with integers randomly drawn from an interval,

- [randn](https://pytorch.org/docs/stable/torch.html#torch.randn): Returns a tensor filled with values drawn from a unit normal distribution,

- [randperm](https://pytorch.org/docs/stable/torch.html#torch.randperm): Returns a tensor filled with a random permutation of integers in some interval,

- [zeros](https://pytorch.org/docs/stable/torch.html#torch.zeros): Returns a tensor filled with all zeros.

### Questions
1 Not all have unit test 
  - `randperm`

2 Why `randperm_out` instead of `randperm`?
3 Wh `randint_like` instead of `randint`?

**Comment by NiklasGustafsson** [comment]
1. Not all have unit test.

See line 143 in TestTorchSharp.cs

2. Why randperm_out instead of randperm?

That's a mistake based on the libtorch native API, which has a separate one. I'll correct that in the next release. There's also a `randperm()`

3. Why randint_like instead of randint?
https://pytorch.org/docs/stable/generated/torch.randint_like.html?highlight=randint#torch.randint_like
