### ISSUE TITLE
conv2d leaking memory (EDIT: maybe my own problem, investigating)

### ISSUE THREAD

**Issue by zimpzon** [dotnet/TorchSharp#1034]
Edit: maybe my own problem, investigating.

**Edit2: it seems to stop growing at 5.2GB, just a lot more than I expected from rather small inferences. I do run out of memory sometimes, though, if I have other memory hungry things running. Maybe because torch insists on keeping those 5.2GB.**

-------------------------------------------------------------

Hi, I seem to have the problem described here (CPU inference):

https://github.com/pytorch/vision/issues/984#issuecomment-498603088

A simple Forward on my conv2d does not release memory used. It keeps growing until I eventually get an out of memory error. Could this issue be present in the current TorchSharp version, or should I take another look at my own code? (already looked for a long time)

Just calling forward on this keeps rapidly increasing memory used for every call:

__conv1 = torch.nn.Conv2d(8, NumChannels, kernelSize: 3, stride: 1, padding: 1, dilation: 1, PaddingModes.Zeros, bias: false);_

_""malloc'ed memory is not always released back to the OS, especially for small object sizes. (Larger allocations will use mmap() / munmap() directly.) The memory can be reused in the same process, though." - Tudor

"There are better memory allocators out there, such as our own Jason Evans's jemalloc", "(jemalloc does make a good faith effort to release memory back to the OS if possible; shrinking the data segment is hard because you can't defragment without a GC, so jemalloc uses mmap() rather than sbrk())".

So, if we use jemalloc instead of the default malloc, things should work fine."_

**Comment by zimpzon** [comment]
Fixed by doing this: `using var disposeScope = torch.NewDisposeScope();`

I suspect the problem was that dotnet was not aware of the memory pressure, and didn't to GC in time.

https://learn.microsoft.com/en-us/dotnet/api/system.gc.addmemorypressure?view=net-7.0

**Comment by NiklasGustafsson** [comment]
That is exactly right. See: https://github.com/dotnet/TorchSharp/wiki/Memory-Management

**Comment by NiklasGustafsson** [comment]
@zimpzon -- can we close this issue?
