### ISSUE TITLE
Request access to torch.nn.functional.scaled_dot_product_attention

### ISSUE THREAD

**Issue by dje-dev** [dotnet/TorchSharp#1042]
Transformer networks have become dominant. This torch function provides an optimized version of the attention mechanism, yielding speedup of a full transformer network by a factor of between 1.3x and 1.6x (based on my testing). It seems like function could be easily exposed in TorchSharp, and would make it fully practical to use TorchSharp for transformer inference and training with competitive performance.

**Comment by NiklasGustafsson** [comment]
@dje-dev: yes, this should be straight-forward to implement, since there's a C++ implementation available in libtorch. Expect it in the next release.

**Comment by NiklasGustafsson** [comment]
See: https://github.com/dotnet/TorchSharp/pull/1043

**Comment by NiklasGustafsson** [comment]
And please let me know if there are additional essential operators missing. I try to be systematic about them, but it's easy to miss some.
