### ISSUE TITLE
Missing torch.cuda.empty_cache(), help needed for relesing memory

### ISSUE THREAD

**Issue by SneakyPillow** [dotnet/TorchSharp#1054]
Hi, thanks for the awersomw work. I'm using torchsharp for implementing SAM and is working wonderfully so far.

The only issue I have is that I can't release the reserved memory, and also I do not know how to release the memory occupied by nn.Modules. 
Disposing them seem to not work as I expected since the GPU memory remains occupied.
Is there a way to release the memory occupied by the modules?

**Comment by NiklasGustafsson** [comment]
Last I looked, empty_cache() was not available in the libtorch API, it's buried in the CUDA backend somewhere, so it would require a lot of trickery (although doable) to get access to it.

**Comment by ChengYen-Tang** [comment]
Are we going to include this reference in LibTorchSharp?

https://pytorch.org/docs/stable/_modules/torch/cuda/memory.html#empty_cache
https://github.com/pytorch/pytorch/blob/main/torch/_C/__init__.pyi.in#L1520-L1579
https://github.com/pytorch/pytorch/blob/main/torch/csrc/cuda/Module.h

**Comment by NiklasGustafsson** [comment]
This is a duplicate of https://github.com/dotnet/TorchSharp/issues/892. I'll close it here, and you can all add to the discussion in the earlier issue.

**Comment by NiklasGustafsson** [comment]
Duplicate bug
