### ISSUE TITLE
Access violation with TensorAccessor.ToArray - incompatible data types

### ISSUE THREAD

**Issue by dje-dev** [dotnet/TorchSharp#1056]
The following sometimes causes an AV (within the CopyTo method of ToArray). Although the code is erroneous (the source and target data types of different sizes), it seems TorchSharp could and would be better to defensively detect this condition and throw an appropriate .NET Exception. 

It is also an interesting question if somewhere in TorchSharp there might exist a similar lack of defensive coding where the data movement is going the other way, thereby allowing writing beyond the end of an unmanaged memory buffer, thereby causing corruption.
 
```
float[] paramValues = new TensorAccessor<float>(param.parameter.cpu().to(TorchSharp.torch.ScalarType.Float16)).ToArray();
```

**Comment by ChengYen-Tang** [comment]
Hi @dje-dev ,
Try this.
```
        Tensor tensor = rand(new long[] { 2, 3 }, dtype: ScalarType.Float32, device: new(DeviceType.CUDA));
        float[] values = tensor.cpu().data<float>().ToArray();
```

**Comment by NiklasGustafsson** [comment]
Yes, calling 'data<T>()' is the canonical way to create a TensorAccessor. I didn't really even notice that you can create one using the constructor... I'm not sure that should be the case.

**Comment by NiklasGustafsson** [comment]
I'm going to fix this one by making the TensorAccessor `internal`.
