### ISSUE TITLE
Memory leak with requires_grad

### ISSUE THREAD

**Issue by GilesBathgate** [dotnet/TorchSharp#1057]
I have the following code:

```c#
using System;
using TorchSharp;

namespace MemoryLeak
{
    class Program
    {
        static void Main(string[] args)
        {
            var device = torch.CUDA;

            while(true) {
	        using (var _ = torch.NewDisposeScope()) {
                    var data = torch.randn(32,1,32,32).to(device).requires_grad_(true);
	        }
	    }
        }
    }
}
```

This crashes quite quickly with:

```
Unhandled exception. System.Runtime.InteropServices.ExternalException (0x80004005): CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 9.77 GiB total capacity; 9.46 GiB already allocated; 3.31 MiB free; 9.46 GiB reserved in total by PyTorch)
```

The equivalent code in pytorch doesn't crash:
```python
import torch

device = torch.device("cuda")

while(True):
    data = torch.randn(32,1,32,32).to(device).requires_grad_(True);
```

Also if I change the `requires_grad` line to the following:
```c#
var data = torch.randn(32,1,32,32).requires_grad_(true).to(device);
```

It doesn't seem to crash, but maybe it leaks CPU memory instead?

**Comment by GilesBathgate** [comment]
output of `nvtop` command:

![image](https://github.com/dotnet/TorchSharp/assets/444143/1f0cdfc6-b3b1-4efa-a3ac-3de93facebf7)

(The large drop in memory is at the moment of crash)

**Comment by GilesBathgate** [comment]
> I wonder if it's as easy as checking (in `Tensor.Dispose()`) whether the associated `grad` Tensor is non-null and disposing it, too...

Where does the 'grad' property exist?

In python I do:
```python
>>> import torch
>>> a = torch.tensor(1.0, requires_grad=True)
>>> a.backward()
>>> a.grad
tensor(1.)
```

**Comment by NiklasGustafsson** [comment]
I have verified that it's not that easy... :-( The grad property is on Tensor, but it's not filled in until you to back-prop, so it's not the problem here.

**Comment by GilesBathgate** [comment]
.requires_grad_(True); should be an in-place operation, so it shouldn't allocate, but maybe the way you CATCH the allocation assumes it allocates?

**Comment by NiklasGustafsson** [comment]
No, catch doesn't assume allocation:

```C
#define CATCH(x) \
  try { \
    torch_last_err = 0; \
    x \
  } catch (const c10::Error e) { \
      torch_last_err = strdup(e.what()); \
  } catch (const std::runtime_error e) { \
      torch_last_err = strdup(e.what()); \
  }
```

Even if it allocated, the 'Dispose()' call should take care of it. There's something else going on... Feel free to debug in parallel! If you do, I suggest setting the batch size to something much larger than 32. With N=30000 and three channels, it takes 21 iteration for it to fail with 8GB of GPU memory (my machine).

**Comment by NiklasGustafsson** [comment]
BTW:

```C#
torch.randn(3, 1, 32, 32, requires_grad: true, device:device)
```

is much faster than what your repro has, and it does not leak memory.

**Comment by NiklasGustafsson** [comment]
> BTW:
> 
> ```cs
> torch.randn(3, 1, 32, 32, requires_grad: true, device:device)
> ```
> 
> is much faster than what your repro has, and it does not leak memory.

And I mean *much* faster... :-)

**Comment by GilesBathgate** [comment]
@NiklasGustafsson Sorry I meant CATCH_TENSOR

```c++
#define CATCH_TENSOR(expr) \
    at::Tensor res = at::Tensor(); \
    CATCH(  \
        res = expr;  \
    );  \
    return ResultTensor(res);
```

Does it default initialise res, then move assign it to expr?

expr is expanded to `tensor->set_requires_grad(requires_grad)` which returns a Tensor& to its *this.

**Comment by NiklasGustafsson** [comment]
Good point. Let me debug...

**Comment by GilesBathgate** [comment]
>torch.randn(3, 1, 32, 32, requires_grad: true, device:device)

Ok, good workaround. The original code I used was:

```python
real_img_tmp = real_img.detach().requires_grad_(do_Dr1)
```

Which was from: https://github.com/NVlabs/stylegan2-ada-pytorch/blob/6f160b3d22b8b178ebe533a50d4d5e63aedba21d/training/loss.py#L111

**Comment by NiklasGustafsson** [comment]
Yup, I believe that was it -- the C++ implementation of 'set_requires_grad()' essentially created a native alias for the tensor, which was never recognized in the managed code that keeps track of disposables. Therefore, the native reference count is kept up, never reaches 0, so the memory is not freed. I'm sure the rewrite you had wastes CPU memory, instead. Anyway, it should work after the next release.

**Comment by NiklasGustafsson** [comment]
> Yup, I believe that was it -- the C++ implementation of 'set_requires_grad()' essentially created a native alias for the tensor, which was never recognized in the managed code that keeps track of disposables. Therefore, the native reference count is kept up, never reaches 0, so the memory is not freed. I'm sure the rewrite you had wastes CPU memory, instead. Anyway, it should work after the next release, but it will still be far slower than setting `requires_grad` and `device` when creating the tensor, when possible.

**Comment by GilesBathgate** [comment]
Is the fix something like this?

```c++
#define CATCH_TENSOR(expr) \
    const at::Tensor& res = [&]() -> const at::Tensor& { \
       CATCH(  \
        return expr;  \
    }(); \
    return ResultTensor(res);
```

**Comment by GilesBathgate** [comment]
@NiklasGustafsson Oh of course, you have control over that method. I thought it was implemented in `at::`

**Comment by NiklasGustafsson** [comment]
> @NiklasGustafsson Oh of course, you have control over that method. I thought it was implemented in `at::`

Yeah... no, it's the culprit is the `return ResultTensor(res);` and the fact that the managed-code caller ignores the returned handle except to check for errors.
