### ISSUE TITLE
After the merge of PR #1062, Ubuntu builds fail.

### ISSUE THREAD

**Issue by NiklasGustafsson** [dotnet/TorchSharp#1063]
After I merge, the build jobs that include the modified Ubuntu tasks fail with:

```
  Unable to find Clang Compiler
  Install clang-6.0, clang-5.0, or clang-4.0
```

It does not happen in the Linux_Native_Build_For_Packages job, which was not modified.

Here's something different from the 'installing build dependencies' logs:

Working
```
GLIBCXX_DEBUG_MESSAGE_LENGTH
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.twLpNwTseX/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys DE19EB17684BA42D
gpg: key FCEE74BB7F3C88C8: public key "Kitware Apt Archive Automatic Signing Key (2021) <debian@kitware.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

Not working:

```
GLIBCXX_DEBUG_MESSAGE_LENGTH
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.eCFyVS9aoA/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys DE19EB17684BA42D
gpg: keyserver receive failed: Cannot assign requested address
```

**Comment by NiklasGustafsson** [comment]
@ChengYen-Tang, for information

**Comment by ChengYen-Tang** [comment]
@NiklasGustafsson,
https://github.com/dotnet/TorchSharp/pull/1065

**Comment by ChengYen-Tang** [comment]
> After I merge, the build jobs that include the modified Ubuntu tasks fail with:
> 
> ```
>   Unable to find Clang Compiler
>   Install clang-6.0, clang-5.0, or clang-4.0
> ```
> 
> It does not happen in the Linux_Native_Build_For_Packages job, which was not modified.
> 
> Here's something different from the 'installing build dependencies' logs:
> 
> Working
> 
> ```
> GLIBCXX_DEBUG_MESSAGE_LENGTH
> Warning: apt-key output should not be parsed (stdout is not a terminal)
> Executing: /tmp/apt-key-gpghome.twLpNwTseX/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys DE19EB17684BA42D
> gpg: key FCEE74BB7F3C88C8: public key "Kitware Apt Archive Automatic Signing Key (2021) <debian@kitware.com>" imported
> gpg: Total number processed: 1
> gpg:               imported: 1
> ```
> 
> Not working:
> 
> ```
> GLIBCXX_DEBUG_MESSAGE_LENGTH
> Warning: apt-key output should not be parsed (stdout is not a terminal)
> Executing: /tmp/apt-key-gpghome.eCFyVS9aoA/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys DE19EB17684BA42D
> gpg: keyserver receive failed: Cannot assign requested address
> ```

@NiklasGustafsson ,
I don't think this error has anything to do with what I modified.

These two ubuntu jobs run on the same pipeline.
Ubuntu_x64 Debug_Build(Build success): https://dev.azure.com/dotnet/TorchSharp/_build/results?buildId=97049&view=logs&j=80b813b5-9a08-5859-11a8-dc0e5b556e52&t=99848337-6ccc-53eb-9c14-1b676ae001b9
![image](https://github.com/dotnet/TorchSharp/assets/32535494/ef22751d-d44e-4df4-a7d3-8fcb3830f57e)

Ubuntu_x64 Release_Build(Build fail): https://dev.azure.com/dotnet/TorchSharp/_build/results?buildId=97049&view=logs&j=660e8eb5-d5ee-5653-778d-3490b8f06993&t=7ccf78ce-78bb-5b09-5117-b59e88f27655
![image](https://github.com/dotnet/TorchSharp/assets/32535494/9b44e399-e867-4b7d-a665-8245a7d66cd1)

Is it a network or environmental problem?

**Comment by ChengYen-Tang** [comment]
Very interesting question, is this a problem of probability?
I found that only Ubuntu_x64 Release_Build is abnormal in the step of Install build dependencies.

**Comment by NiklasGustafsson** [comment]
No, it often happens on both. You might not be noticing when I restart failed jobs, which I spend a lot of my time on... There's something unstable about acquiring Ubuntu dependencies that I don't understand.

**Comment by NiklasGustafsson** [comment]
The other build jobs are unstable because there is (per my analysis) some issues running the unit tests concurrently. The .NET FX jobs are the most affected by that.

**Comment by ChengYen-Tang** [comment]
So is this problem related to my previous commit🤔
https://github.com/dotnet/TorchSharp/pull/1062

**Comment by NiklasGustafsson** [comment]
No, I don't think so. It got worse yesterday, after the checkin, but not consistently so, and it's better today (but not good). I think it was a coincidence.
