### ISSUE TITLE
Implementation of torch.sparse_coo_tensor for sparse tensor creation

### ISSUE THREAD

**Issue by dje-dev** [dotnet/TorchSharp#1069]
As input to a net, I have a very sparse 2D tensor (each row has 16,384 columns of which only at most 64 will be nonzero). It is prohibitively expensive to instantiate the tensor on CPU and transfer it across the bus to the GPU).

Ideally Torchsharp would support code such as the following. It seems that just one critical function would need to be added to make this work: sparse_coo_tensor.

```
int[,] indices = new int[BATCH_SIZE, 64];
float[,] values = new float[BATCH_SIZE, 64]; 

Tensor indices_tensor = torch.tensor(indices).to(ScalarType.Int64).to(Device);
Tensor values_tensor = torch.tensor(values).to(ScalarType.Float16).to(Device);

Tensor sparse_tensor = torch.sparse_coo_tensor(indices_tensor, values_tensor, size: new long[] { BATCH_SIZE, 16_384 }, device: Device);

Tensor tensor = sparse_tensor.to(ScalarType.Float16).to_dense();
```

**Comment by NiklasGustafsson** [comment]
Okay, this seems reasonable. I would, however, suggest broadening the request to a wider set of sparse tensor operations.

**Comment by dje-dev** [comment]
I would suggest these might be better as separate efforts. Commonly the inputs to the neural network are sparse, but the actual layers of the network need to run with the existing dense layers. To support efficient GPU uploading, only two methods are required (sparse_coo_tensor and to_dense) and only one of these is currently missing. This should be hopefully very easy to implement.

By contrast, the full sparse tensor operations encompasses a large API surface that would take much more effort to eventually support.

**Comment by dje-dev** [comment]
I've found a workaround using current TorchSharp - simply use torch.scatter operator. Thus this enhancement is no longer important for my work. Thanks.

**Comment by NiklasGustafsson** [comment]
Turns out the method was actually there, but incorrectly called `torch.sparse`. I made that one obsolete and renamed the implementation, also adding doc strings. Will appear in the next release.
