### ISSUE TITLE
Module.zero_grad() does not work

### ISSUE THREAD

**Issue by brianberns** [dotnet/TorchSharp#1084]
`Optimizer.zero_grad()` works fine, but `Module.zero_grad()` doesn't seem to do anything. To reproduce this easily, modify the [MNIST example's training loop](https://github.com/dotnet/TorchSharp/blob/d7be25b4c5946c426920d0aef539fccd4979d5a9/src/FSharp.Examples/MNIST.fs#L94) as follows:

```fsharp
        model.zero_grad()   // this should zero out all the gradients, but it doesn't
        for (name, param) in model.named_parameters() do
            let grad = param.grad()
            let n = 
                if isNull grad then 0L
                else torch.count_nonzero(grad).item<int64>()
            if n > 0 then
                printfn $"{name} gradient has {n} non-zero values"
```

Output:

```
Running MNIST on CUDA
Dataset: mnist
Epoch: 1...
conv1.weight gradient has 288 non-zero values
conv1.bias gradient has 32 non-zero values
conv2.weight gradient has 18419 non-zero values
conv2.bias gradient has 64 non-zero values
fc1.weight gradient has 1086148 non-zero values
fc1.bias gradient has 127 non-zero values
fc2.weight gradient has 1270 non-zero values
fc2.bias gradient has 10 non-zero values
```

**Comment by NiklasGustafsson** [comment]
This is curious -- I'll take a look

**Comment by NiklasGustafsson** [comment]
Okay, it was a simple fix... The Module.zero_grad() default implementation did not consider any submodules, only the top. Fortunately, a workaround is straight-forward, too.

Here's what the Module.zero_grad() implementation **should** look like:

```C#
public virtual void zero_grad()
{
    THSNN_Module_zero_grad(handle);
    CheckForErrors();

    foreach (var (_,m) in named_modules()) {
        m.zero_grad();
    }
}
```

and it will, in the next release. 

The temporary workaround is to override `zero_grad` in any custom module and add the loop after a call to `base.zero_grad()`. If you're using `Sequential`, you may need to derive a class from it and add the override. For now.

**Comment by NiklasGustafsson** [comment]
Not so fast! The fix only works for modules composed entirely of submodules. Any module with its own parameters still fails.

**Comment by NiklasGustafsson** [comment]
The correct loop in Module.zero_grad() (and any workaround) is this:

```C#
foreach (var (_, p) in named_parameters()) {
    var grad = p.grad();
    if (grad is not null) {
        grad.zero_();
    }
}
```

**Comment by NiklasGustafsson** [comment]
Okay, the new fix also works for custom modules, as long as `RegisterComponents()` has been called (if it hasn't, then all kinds of unrelated trouble will also occur).
