### ISSUE TITLE
max_pool2d overload creates tensor with incorrect shape

### ISSUE THREAD

**Issue by brianberns** [dotnet/TorchSharp#1089]
The stride should default to the kernel size.

F# repro:

```fsharp
type F = torch.nn.functional

let x = torch.zeros([|1L; 6L; 28L; 28L|])

let bad = F.max_pool2d(x, [|2L; 2L|])
printfn "%A" bad.shape    // incorrect: [|1L; 6L; 27L; 27L|]

let good = F.max_pool2d(x, struct (2L, 2L))
printfn "%A" good.shape   // correct:   [|1L; 6L; 14L; 14L|]
```

For bonus points, it would be nice if there was another overload that accepted a plain F# tuple instead.

**Comment by NiklasGustafsson** [comment]
@brianberns -- thank you for reporting this and providing such a great repro case! The fix will be in the next release. For a temporary workaround, just pass in the strides explicitly.

As far as F# tuples go -- open to any suggestions that don't involve taking a dependency on the F#-specific runtime. We already have some minor syntactic sugar in place for F#, such as the '-->' operator for forwarding between instances of Module<Tensor,Tensor>:

```C#
public static Tensor op_MinusMinusGreater(Tensor t, torch.nn.Module<Tensor, Tensor> m) => m.call(t);
```

**Comment by brianberns** [comment]
You're welcome! I'm happy to help out.

I can understand not wanting to take a dependency on the F# runtime for tuple support, but I suspect that a significant fraction of TorchSharp users will be working in F#, and will prefer to write idiomatic code. Perhaps it would make sense to have a separate, smaller "TorchSharpForFSharp" library that has this dependency instead. Or maybe that's what DiffSharp is already intended to be?

**Comment by NiklasGustafsson** [comment]
>> Or maybe that's what DiffSharp is already intended to be?

I don't speak for @dsyme, but I personally think DiffSharp presents the best F# API surface over TorchSharp.
