### ISSUE TITLE
got error when using DataLoader

### ISSUE THREAD

**Issue by mfingstar** [dotnet/TorchSharp#1092]
as we know, in python we can use DataLoader with TensorDataset like:

inps = torch.arange(10 * 5, dtype=torch.float32).view(10, 5)
tgts = torch.arange(10 * 5, dtype=torch.float32).view(10, 5)
dataset = TensorDataset(inps, tgts)
loader = DataLoader(dataset, batch_size=2) # that's right

but in C# we got an error, that first argument of DataLoader func is "Dataset"

var inps = torch.arange(10 * 5, torch.float32).view(10, 5);
var tgts = torch.arange(10 * 5, torch.float32).view(10, 5);
var dataset = TensorDataset(inps, tgts);
// error: Can't convert “TorchSharp.Modules.TensorDataset” to“TorchSharp.torch.utils.data.Dataset”
var loader = DataLoader(dataset, batch_size=2); 

please help me type a right code

**Comment by NiklasGustafsson** [comment]
@mfingstar  -- thanks for reporting this API bug. 

It seems that DataLoader expects a dictionary-based dataset, while TensorDataset is a list-based dataset. This will require some thinking.

**Comment by mfingstar** [comment]
thank u for reply, i handled it by my own dataloader,waiting for offical update :)

**Comment by NiklasGustafsson** [comment]
@mfingstar -- this sounds like it would make for a great contribution to TorchSharp... :-)
