### ISSUE TITLE
Add Github label: Torchsharp so users can track all TorchSharp projects

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/TorchSharp#1104]
https://github.com/topics/torchsharp
![image](https://github.com/ds5678/TorchCategorizationDemo/assets/49812372/6323b634-2247-4be6-9ebf-66c0d927590d)

I know this could work, sometimes it gathers others through just the Torchsharp label
https://github.com/dotnet/TorchSharp/network/dependents

**Comment by NiklasGustafsson** [comment]
@GeorgeS2019: good idea! How do I do that? :-)

**Comment by NiklasGustafsson** [comment]
Okay, I added a few GH topics to the repo.

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson 

kind reminder, please add the topic to this too! :-)
https://github.com/dotnet/TorchSharpExamples

**Comment by NiklasGustafsson** [comment]
> @NiklasGustafsson
> 
> kind reminder, please add the topic to this too! :-) https://github.com/dotnet/TorchSharpExamples

Done. Thanks for the reminder.
