### ISSUE TITLE
Dataset files get written to the wrong directory

### ISSUE THREAD

**Issue by zkWildfire** [dotnet/TorchSharp#1105]
Looking at the documentation here:
https://github.com/dotnet/TorchSharp/blob/fbb4b558e916a0771560b7159517539eddfdb62f/src/TorchVision/dsets/MNIST.cs#L17-L29

The expected behavior is that if I pass `foobar/` as the value for `root`, the dataset should be downloaded to `foobar/mnist/some-archive-name.tar.gz`. The actual behavior is that the dataset archive gets downloaded into the current working directory, then the method throws an exception because it fails to find the archive file at `foobar/mnist/some-archive-name.tar.gz`.

The bug is due to a small typo in the `DownloadFile()` method, found here:
https://github.com/dotnet/TorchSharp/blob/fbb4b558e916a0771560b7159517539eddfdb62f/src/TorchVision/dsets/CIFAR.cs#L86-L99

On line 95, `DownloadFile()` writes to the path stored in `file`, whereas it should be writing to the path stored in `filePath`.

`DownloadFile()` is called here:
https://github.com/dotnet/TorchSharp/blob/fbb4b558e916a0771560b7159517539eddfdb62f/src/TorchVision/dsets/MNIST.cs#L174

Assuming `Download()` was called with `root = "foobar"` and `dataset = "mnist"`:
1. `Download()` sets `datasetPath = "foobar/mnist"` and `sourceDir = datasetPath`
2. `DownloadFile()` will be called with `file = "train-images-idx3-ubyte.gz"` and `target = sourceDir = "foobar/mnist"`
3. Because of the typo, `DownloadFile()` writes to `train-images-idx3-ubyte.gz` instead of `foobar/mnist/train-images-idx3-ubyte.gz`
4. `DecompressFile()` is later called with `file = "train-images-idx3-ubyte"` and `sourceDir = "foobar/mnist"`
5. `DecompressFile()` expects the target file to be at `foobar/mnist/train-images-idx3-ubyte.gz`, but the file is actually at `$(pwd)/train-images-idx3-ubyte.gz`

I do not have a CLA signed with Microsoft, the .NET Foundation, or the TorchSharp repository, so I'm reporting this issue as-is rather than with a pull request. From what I've found, I believe this bug can be fixed with a 4 letter change that replaces `file` with `filePath` in the `DownloadFile()` method.

**Comment by NiklasGustafsson** [comment]
@zkWildfire -- thanks for reporting this. I'll try to reproduce it and get a fix in place ASAP.
