### ISSUE TITLE
DateTime ToTensor Support

### ISSUE THREAD

**Issue by yfbenkhalifa** [dotnet/TorchSharp#1106]
Hi everyone! 
While experimenting with the library for my personal projects I encountered an obstacle when trying to perform feature engineering with dates wrapped with the DateTime object. Is there already an implementation for converting the DateTime type objects to tensors, or is there provided some other way to deal with dates using tensors?

**Comment by NiklasGustafsson** [comment]
Are there any examples from PyTorch on how people are using DateTime? 

I can imagine that you would get the underlying epoch out, round it to the granularity you need (seconds, minutes, hours...), and put that result into a tensor, which should be a simple LINQ expression, but I confess that I don't know enough about the scenario you have in mind...

**Comment by yfbenkhalifa** [comment]
Well to put it simply, I encountered a scenario in which I needed to perform some feature engineering on dates for a machine learning model. I tried to perform such task in python, where I simply converted the date feature into a numpy array and then transform it into a tensor, but there is no direct reference to any existing direct DateTime conversion into/from a tensor in the pytorch library.  

When I stumbled upon this issue in C# I pretty much done the same thing I have done in the python environment, but I had an idea by looking at the ToTensor() extension methods to implement an extension method myself (along with the tests) for automatically converting DateTime objects into tensors. I don't really know if it can actually be useful for anybody else, but I thought to throw out this idea, since feature engineering on date objects can be a powerful tool in some machine learning applications.

**Comment by NiklasGustafsson** [comment]
So, to fill a tensor with 10 instances of 'now' would be:

```C#
var dt = Enumerable.Range(0,10).Select(r => DateTime.Now.Ticks).ToArray();
var dtT = torch.tensor(dt);
```

From the MSDN docs:

  _A single tick represents one hundred nanoseconds or one ten-millionth of a second. There are 10,000 ticks in a millisecond (see [TicksPerMillisecond](https://learn.microsoft.com/en-us/dotnet/api/system.timespan.tickspermillisecond?view=net-7.0#system-timespan-tickspermillisecond)) and 10 million ticks in a second._

**Comment by yfbenkhalifa** [comment]
I meant more a generic DateTime object to directly transform into a tensor using an extension method just like with ints and floats. Which means doing:
```
DateTime date = new DateTime(2023, 10, 9);
 var tensor = date.ToTensor<DateTime>();
```
I don't if that makes sense or I'm making stuff up

**Comment by NiklasGustafsson** [comment]
Hmm... I don't know what that would mean, so I think an example of how it would be used would be useful (to me).

One way to look at it is that DateTime instance is just an API on top of a `long` (Ticks), with some additional metadata (such as time zone) and APIs to translate to and from other (more human-meaningful) forms of expressing time and dates.

**Comment by yfbenkhalifa** [comment]
In my scenario I have a DB with some some DateTime fields, from which i had an idea of extracting some useful features. So instead of having to create manually convert the dates into 3 separate tensors (one for the year, one for the month, one for the day) I was thinking of implementing an extensions methods that does that for me

**Comment by NiklasGustafsson** [comment]
Okay. I have no bright ideas on how to represent that, except to suggest (as earlier) to just take the Ticks and round to the granularity you want to represent the time dimension.

**Comment by yfbenkhalifa** [comment]
Alright, thank you for the suggestion!

**Comment by NiklasGustafsson** [comment]
When I say `round`, I mean `floor`

**Comment by NiklasGustafsson** [comment]
@yfbenkhalifa -- any reason to keep this issue open?

**Comment by yfbenkhalifa** [comment]
No not really, you can close it
