### ISSUE TITLE
How to convert this python code into torchsharp code?

### ISSUE THREAD

**Issue by williamlzw** [dotnet/TorchSharp#1112]
class SwitchSequential(nn.Sequential):
        def forward(self, x, context, time):
            for layer in self:
                if isinstance(layer, AttentionBlock):
                    x = layer(x, context)
                elif isinstance(layer, ResidualBlock):
                    x = layer(x, time)
                else:
                    x = layer(x)
            return x

**Comment by williamlzw** [comment]
Sequential does not support generics for two input tensors
  public class SwitchSequentialAttentionBlock : Sequential<Module<Tensor, Tensor, Tensor>>
     {
         public SwitchSequentialAttentionBlock(long in_channel, long out_channel, long kernel_size) :
             base(new AttentionBlock(in_channel, out_channel, kernel_size))
         {
         }
     }

**Comment by williamlzw** [comment]
The main reason I want to port this code is to directly use the torchsharp weights exported by exportsd.py.

**Comment by williamlzw** [comment]
https://github.com/kjsman/stable-diffusion-pytorch/blob/main/stable_diffusion_pytorch/diffusion.py#L110C7-L110C23

**Comment by williamlzw** [comment]
public class UNet : Module<Tensor, Tensor, Tensor, Tensor>
    {
        private readonly ModuleList<ModuleList<torch.nn.Module>> encoders;
        private readonly ModuleList<torch.nn.Module> bottleneck;
        private readonly ModuleList<ModuleList<torch.nn.Module>> decoders;
      
    
        public UNet() : base("UNet")
        {
            encoders = new ModuleList<ModuleList<torch.nn.Module>>();
    
            var seq1 = new ModuleList<torch.nn.Module>();
            seq1.append(Conv2d(4, 320, kernelSize: 3, padding: 1));
            var seq2 = new ModuleList<torch.nn.Module>();
            seq2.append(new ResidualBlock(320, 320));
            seq2.append(new AttentionBlock(8, 40));
    
            var seq3 = new ModuleList<torch.nn.Module>();
            seq3.append(new ResidualBlock(320, 320));
            seq3.append(new AttentionBlock(8, 40));
    
            var seq4 = new ModuleList<torch.nn.Module>();
            seq4.append(Conv2d(320, 320, kernelSize: 3, stride:2, padding: 1));
    
            var seq5 = new ModuleList<torch.nn.Module>();
            seq5.append(new ResidualBlock(320, 640));
            seq5.append(new AttentionBlock(8, 80));
    
            var seq6 = new ModuleList<torch.nn.Module>();
            seq6.append(new ResidualBlock(640, 640));
            seq6.append(new AttentionBlock(8, 80));
    
            var seq7 = new ModuleList<torch.nn.Module>();
            seq7.append(Conv2d(640, 640, kernelSize: 3, stride: 2, padding: 1));
    
            var seq8 = new ModuleList<torch.nn.Module>();
            seq8.append(new ResidualBlock(640, 1280));
            seq8.append(new AttentionBlock(8, 160));
    
            var seq9 = new ModuleList<torch.nn.Module>();
            seq9.append(new ResidualBlock(1280, 1280));
            seq9.append(new AttentionBlock(8, 160));
    
            var seq10 = new ModuleList<torch.nn.Module>();
            seq10.append(Conv2d(1280, 1280, kernelSize: 3, stride: 2, padding: 1));
    
            var seq11 = new ModuleList<torch.nn.Module>();
            seq11.append(new ResidualBlock(1280, 1280));
    
            var seq12 = new ModuleList<torch.nn.Module>();
            seq12.append(new ResidualBlock(1280, 1280));
    
            encoders.Add(seq1);
            encoders.Add(seq2);
            encoders.Add(seq3);
            encoders.Add(seq4);
            encoders.Add(seq5);
            encoders.Add(seq6);
            encoders.Add(seq7);
            encoders.Add(seq8);
            encoders.Add(seq9);
            encoders.Add(seq10);
            encoders.Add(seq11);
            encoders.Add(seq12);
    
            bottleneck = new ModuleList<torch.nn.Module>();
            bottleneck.Add(new ResidualBlock(1280, 1280));
            bottleneck.Add(new AttentionBlock(8, 160));
            bottleneck.Add(new ResidualBlock(1280, 1280));
    
            decoders = new ModuleList<ModuleList<torch.nn.Module>>();
            var seq_decode1 = new ModuleList<torch.nn.Module>();
            seq_decode1.append(new ResidualBlock(2560, 1280));
    
            var seq_decode2 = new ModuleList<torch.nn.Module>();
            seq_decode2.append(new ResidualBlock(2560, 1280));
    
            var seq_decode3 = new ModuleList<torch.nn.Module>();
            seq_decode3.append(new ResidualBlock(2560, 1280));
            seq_decode3.append(new Upsample(1280));
    
            var seq_decode4 = new ModuleList<torch.nn.Module>();
            seq_decode4.append(new ResidualBlock(2560, 1280));
            seq_decode4.append(new AttentionBlock(8, 160));
    
            var seq_decode5 = new ModuleList<torch.nn.Module>();
            seq_decode5.append(new ResidualBlock(2560, 1280));
            seq_decode5.append(new AttentionBlock(8, 160));
    
            var seq_decode6 = new ModuleList<torch.nn.Module>();
            seq_decode6.append(new ResidualBlock(1920, 1280));
            seq_decode6.append(new AttentionBlock(8, 160));
            seq_decode6.append(new Upsample(1280));
    
            var seq_decode7 = new ModuleList<torch.nn.Module>();
            seq_decode7.append(new ResidualBlock(1920, 640));
            seq_decode7.append(new AttentionBlock(8, 80));
    
            var seq_decode8 = new ModuleList<torch.nn.Module>();
            seq_decode8.append(new ResidualBlock(1280, 640));
            seq_decode8.append(new AttentionBlock(8, 80));
    
            var seq_decode9 = new ModuleList<torch.nn.Module>();
            seq_decode9.append(new ResidualBlock(960, 640));
            seq_decode9.append(new AttentionBlock(8, 80));
            seq_decode9.append(new Upsample(640));
    
            var seq_decode10 = new ModuleList<torch.nn.Module>();
            seq_decode10.append(new ResidualBlock(960, 320));
            seq_decode10.append(new AttentionBlock(8, 40));
    
            var seq_decode11 = new ModuleList<torch.nn.Module>();
            seq_decode11.append(new ResidualBlock(640, 320));
            seq_decode11.append(new AttentionBlock(8, 40));
    
            var seq_decode12 = new ModuleList<torch.nn.Module>();
            seq_decode12.append(new ResidualBlock(640, 320));
            seq_decode12.append(new AttentionBlock(8, 40));
    
            decoders.Add(seq_decode1);
            decoders.Add(seq_decode2);
            decoders.Add(seq_decode3);
            decoders.Add(seq_decode4);
            decoders.Add(seq_decode5);
            decoders.Add(seq_decode6);
            decoders.Add(seq_decode7);
            decoders.Add(seq_decode8);
            decoders.Add(seq_decode9);
            decoders.Add(seq_decode10);
            decoders.Add(seq_decode11);
            decoders.Add(seq_decode12);
    
            RegisterComponents();
        }
    
        public override Tensor forward(Tensor x, Tensor context, Tensor time)
        {
            using var _ = NewDisposeScope();
            List<Tensor> skip_connections = new List<Tensor>();
            foreach(var layers in encoders.modules())
            {
                x = ((Module<Tensor, Tensor, Tensor, Tensor>)layers).forward(x, context, time);
                skip_connections.Add(x);
            }
            foreach(var index in bottleneck)
            {
                x = ((Module<Tensor, Tensor, Tensor, Tensor>)index).forward(x, context, time);
            }
            
            foreach(var layers in decoders.modules())
            {
                x = torch.cat(new Tensor[] { x, skip_connections[-1] }, 1);
                skip_connections.RemoveAt(-1);
                x = ((Module<Tensor, Tensor, Tensor, Tensor>)layers).forward(x, context, time);
            }
    
            return x.MoveToOuterDisposeScope();
        }
    }

**Comment by williamlzw** [comment]
The following code can be run

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TorchSharp;
using static TorchSharp.torch.nn;
using static TorchSharp.torch;
using TorchSharp.Modules;


namespace StableDiffusionTorchSharp
{
    public class TimeEmbedding : Module<Tensor, Tensor>
    {
        private readonly Linear linear_1;
        private readonly Linear linear_2;
        private readonly SiLU silu;

        public TimeEmbedding(long n_embd) : base("TimeEmbedding")
        {
            linear_1 = Linear(n_embd, 4 * n_embd);
            linear_2 = Linear(4 * n_embd, 4 * n_embd);
            silu = SiLU();
            RegisterComponents();
        }

        public override Tensor forward(Tensor x)
        {
            using var _ = NewDisposeScope();
            x = linear_1.forward(x);
            x = silu.forward(x);
            x = linear_2.forward(x);
            return x.MoveToOuterDisposeScope();
        }
    }

    public class ResidualBlock : Module<Tensor, Tensor, Tensor>
    {
        private readonly GroupNorm groupnorm_feature;
        private readonly Conv2d conv_feature;
        private readonly Linear linear_time;
        private readonly GroupNorm groupnorm_merged;
        private readonly Conv2d conv_merged;
        private readonly Module<Tensor, Tensor> residual_layer;
        private readonly SiLU silu;

        public ResidualBlock(long in_channels, long out_channels, long n_time = 1280) : base("ResidualBlock")
        {
            groupnorm_feature = GroupNorm(32, in_channels);
            conv_feature = Conv2d(in_channels, out_channels, kernelSize: 3, padding: 1);
            linear_time = Linear(n_time, out_channels);
            groupnorm_merged = GroupNorm(32, out_channels);
            conv_merged = Conv2d(out_channels, out_channels, kernelSize: 3, padding: 1);
            silu = SiLU();
            if (in_channels == out_channels)
            {
                residual_layer = nn.Identity();
            }
            else
            {
                residual_layer = Conv2d(in_channels, out_channels, kernelSize: 1);
            }
            RegisterComponents();
        }

        public override Tensor forward(Tensor feature, Tensor time)
        {
            using var _ = NewDisposeScope();
            var residue = feature;
            feature = groupnorm_feature.forward(feature);
            feature = silu.forward(feature);
            feature = conv_feature.forward(feature);

            time = silu.forward(time);
            time = linear_time.forward(time);

            var merged = feature + time.unsqueeze(-1).unsqueeze(-1);
            merged = groupnorm_merged.forward(merged);
            merged = silu.forward(merged);
            merged = conv_merged.forward(merged);
            var output = merged + residual_layer.forward(residue);
            return output.MoveToOuterDisposeScope();
        }
    }

    public class AttentionBlock : Module<Tensor, Tensor, Tensor>, torch.nn.IModule<Tensor, Tensor>
    {
        private readonly GroupNorm groupnorm;
        private readonly Conv2d conv_input;
        private readonly LayerNorm layernorm_1;
        private readonly SelfAttention attention_1;
        private readonly LayerNorm layernorm_2;
        private readonly CrossAttention attention_2;
        private readonly LayerNorm layernorm_3;
        private readonly Linear linear_geglu_1;
        private readonly Linear linear_geglu_2;
        private readonly Conv2d conv_output;

        public AttentionBlock(long n_head, long n_embd, long d_context = 768) : base("AttentionBlock")
        {
            var channels = n_head * n_embd;
            groupnorm = GroupNorm(32, channels);
            conv_input = Conv2d(channels, channels, kernelSize: 1);
            layernorm_1 = LayerNorm(channels);
            attention_1 = new SelfAttention(n_head, channels, in_proj_bias: false);
            layernorm_2 = LayerNorm(channels);
            attention_2 = new CrossAttention(n_head, channels, d_context, in_proj_bias: false);
            layernorm_3 = LayerNorm(channels);
            linear_geglu_1 = Linear(channels, 4 * channels * 2);
            linear_geglu_2 = Linear(4 * channels, channels);
            conv_output = Conv2d(channels, channels, kernelSize: 1);
            RegisterComponents();
        }

        public Tensor call(Tensor feature)
        {
            return forward(feature, null);
        }

        public override Tensor forward(Tensor x, Tensor context)
        {
            using var _ = NewDisposeScope();
            var residue_long = x;
            x = groupnorm.forward(x);
            x = conv_input.forward(x);
            var n = x.shape[0];
            var c = x.shape[1];
            var h = x.shape[2];
            var w = x.shape[3];
            x = x.view(n, c, h * w);
            x = x.transpose(-1, -2);
            var residue_short = x;
            x = layernorm_1.forward(x);
            x = attention_1.forward(x);
            x += residue_short;
            residue_short = x;
            x = layernorm_2.forward(x);
            x = attention_2.forward(x, context);
            x+= residue_short;
            residue_short = x;
            x = layernorm_3.forward(x);
            var ret = linear_geglu_1.forward(x).chunk(2, -1);
            x = ret[0];
            var gate = ret[1];
            x = x * torch.nn.functional.gelu(gate);
            x = linear_geglu_2.forward(x);
            x += residue_short;
            x = x.transpose(-1, -2);
            x = x.view(n, c, h, w);
            var output = conv_output.forward(x) + residue_long;
            return output.MoveToOuterDisposeScope();
        }
    }

    public class Upsample : Module<Tensor, Tensor>
    {
        private readonly Conv2d conv;
        public Upsample(long channels) : base("Upsample")
        {
            conv = Conv2d(channels, channels, kernelSize: 3, padding: 1);
            RegisterComponents();
        }

        public override Tensor forward(Tensor x)
        {
            using var _ = NewDisposeScope();
            x = torch.nn.functional.interpolate(x, scale_factor: new double[] { 2, 2 });
            var output = conv.forward(x);
            return output.MoveToOuterDisposeScope();
        }
    }


    public class UNet : Module<Tensor, Tensor, Tensor, Tensor>
    {
        private readonly ModuleList<ModuleList<torch.nn.Module>> encoders;
        private readonly ModuleList<ModuleList<torch.nn.Module>> bottleneck;
        private readonly ModuleList<ModuleList<torch.nn.Module>> decoders;
      

        public UNet() : base("UNet")
        {
            encoders = new ModuleList<ModuleList<torch.nn.Module>>();

            var seq1 = new ModuleList<torch.nn.Module>();
            seq1.append(Conv2d(4, 320, kernelSize: 3, padding: 1));
            var seq2 = new ModuleList<torch.nn.Module>();
            seq2.append(new ResidualBlock(320, 320));
            seq2.append(new AttentionBlock(8, 40));

            var seq3 = new ModuleList<torch.nn.Module>();
            seq3.append(new ResidualBlock(320, 320));
            seq3.append(new AttentionBlock(8, 40));

            var seq4 = new ModuleList<torch.nn.Module>();
            seq4.append(Conv2d(320, 320, kernelSize: 3, stride:2, padding: 1));

            var seq5 = new ModuleList<torch.nn.Module>();
            seq5.append(new ResidualBlock(320, 640));
            seq5.append(new AttentionBlock(8, 80));

            var seq6 = new ModuleList<torch.nn.Module>();
            seq6.append(new ResidualBlock(640, 640));
            seq6.append(new AttentionBlock(8, 80));

            var seq7 = new ModuleList<torch.nn.Module>();
            seq7.append(Conv2d(640, 640, kernelSize: 3, stride: 2, padding: 1));

            var seq8 = new ModuleList<torch.nn.Module>();
            seq8.append(new ResidualBlock(640, 1280));
            seq8.append(new AttentionBlock(8, 160));

            var seq9 = new ModuleList<torch.nn.Module>();
            seq9.append(new ResidualBlock(1280, 1280));
            seq9.append(new AttentionBlock(8, 160));

            var seq10 = new ModuleList<torch.nn.Module>();
            seq10.append(Conv2d(1280, 1280, kernelSize: 3, stride: 2, padding: 1));

            var seq11 = new ModuleList<torch.nn.Module>();
            seq11.append(new ResidualBlock(1280, 1280));

            var seq12 = new ModuleList<torch.nn.Module>();
            seq12.append(new ResidualBlock(1280, 1280));

            encoders.Add(seq1);
            encoders.Add(seq2);
            encoders.Add(seq3);
            encoders.Add(seq4);
            encoders.Add(seq5);
            encoders.Add(seq6);
            encoders.Add(seq7);
            encoders.Add(seq8);
            encoders.Add(seq9);
            encoders.Add(seq10);
            encoders.Add(seq11);
            encoders.Add(seq12);

            bottleneck = new ModuleList<ModuleList<torch.nn.Module>>();
            var seq_bottleneck = new ModuleList<torch.nn.Module>();
            seq_bottleneck.Add(new ResidualBlock(1280, 1280));
            seq_bottleneck.Add(new AttentionBlock(8, 160));
            seq_bottleneck.Add(new ResidualBlock(1280, 1280));
            bottleneck.Add(seq_bottleneck);

            decoders = new ModuleList<ModuleList<torch.nn.Module>>();
            var seq_decode1 = new ModuleList<torch.nn.Module>();
            seq_decode1.append(new ResidualBlock(2560, 1280));

            var seq_decode2 = new ModuleList<torch.nn.Module>();
            seq_decode2.append(new ResidualBlock(2560, 1280));

            var seq_decode3 = new ModuleList<torch.nn.Module>();
            seq_decode3.append(new ResidualBlock(2560, 1280));
            seq_decode3.append(new Upsample(1280));

            var seq_decode4 = new ModuleList<torch.nn.Module>();
            seq_decode4.append(new ResidualBlock(2560, 1280));
            seq_decode4.append(new AttentionBlock(8, 160));

            var seq_decode5 = new ModuleList<torch.nn.Module>();
            seq_decode5.append(new ResidualBlock(2560, 1280));
            seq_decode5.append(new AttentionBlock(8, 160));

            var seq_decode6 = new ModuleList<torch.nn.Module>();
            seq_decode6.append(new ResidualBlock(1920, 1280));
            seq_decode6.append(new AttentionBlock(8, 160));
            seq_decode6.append(new Upsample(1280));

            var seq_decode7 = new ModuleList<torch.nn.Module>();
            seq_decode7.append(new ResidualBlock(1920, 640));
            seq_decode7.append(new AttentionBlock(8, 80));

            var seq_decode8 = new ModuleList<torch.nn.Module>();
            seq_decode8.append(new ResidualBlock(1280, 640));
            seq_decode8.append(new AttentionBlock(8, 80));

            var seq_decode9 = new ModuleList<torch.nn.Module>();
            seq_decode9.append(new ResidualBlock(960, 640));
            seq_decode9.append(new AttentionBlock(8, 80));
            seq_decode9.append(new Upsample(640));

            var seq_decode10 = new ModuleList<torch.nn.Module>();
            seq_decode10.append(new ResidualBlock(960, 320));
            seq_decode10.append(new AttentionBlock(8, 40));

            var seq_decode11 = new ModuleList<torch.nn.Module>();
            seq_decode11.append(new ResidualBlock(640, 320));
            seq_decode11.append(new AttentionBlock(8, 40));

            var seq_decode12 = new ModuleList<torch.nn.Module>();
            seq_decode12.append(new ResidualBlock(640, 320));
            seq_decode12.append(new AttentionBlock(8, 40));

            decoders.Add(seq_decode1);
            decoders.Add(seq_decode2);
            decoders.Add(seq_decode3);
            decoders.Add(seq_decode4);
            decoders.Add(seq_decode5);
            decoders.Add(seq_decode6);
            decoders.Add(seq_decode7);
            decoders.Add(seq_decode8);
            decoders.Add(seq_decode9);
            decoders.Add(seq_decode10);
            decoders.Add(seq_decode11);
            decoders.Add(seq_decode12);

            RegisterComponents();
        }

        public override Tensor forward(Tensor x, Tensor context, Tensor time)
        {
            using var _ = NewDisposeScope();
            List<Tensor> skip_connections = new List<Tensor>();
            foreach(var modules in encoders)
            {
                foreach(var layers in modules)
                {
                    if (layers.GetType() == typeof(ResidualBlock))
                    {
                        x = ((Module<Tensor, Tensor, Tensor>)layers).forward(x, time);
                    }
                    else if (layers.GetType() == typeof(AttentionBlock))
                    {
                        x = ((Module<Tensor, Tensor, Tensor>)layers).forward(x, context);
                    }
                    else
                    {
                        x = ((Module<Tensor, Tensor>)layers).forward(x);
                    }
                }
                skip_connections.Add(x);
            }

            foreach (var modules in bottleneck)
            {
                foreach (var layers in modules)
                {
                    if (layers.GetType() == typeof(ResidualBlock))
                    {
                        x = ((Module<Tensor, Tensor, Tensor>)layers).forward(x, time);
                    }
                    else if (layers.GetType() == typeof(AttentionBlock))
                    {
                        x = ((Module<Tensor, Tensor, Tensor>)layers).forward(x, context);
                    }
                }
            }

            foreach (var modules in decoders)
            {
                var index = skip_connections.Last();
                skip_connections.RemoveAt(skip_connections.Count - 1);
                x = torch.cat(new Tensor[] { x, index }, 1);
                foreach (var layers in modules)
                {
                    if (layers.GetType() == typeof(ResidualBlock))
                    {
                        x = ((Module<Tensor, Tensor, Tensor>)layers).forward(x, time);
                    }
                    else if (layers.GetType() == typeof(AttentionBlock))
                    {
                        x = ((Module<Tensor, Tensor, Tensor>)layers).forward(x, context);
                    }
                    else
                    {
                        x = ((Module<Tensor, Tensor>)layers).forward(x);
                    }
                }
            }
            return x.MoveToOuterDisposeScope();
        }
    }

    public class FinalLayer : Module<Tensor, Tensor>
    {
        private readonly Conv2d conv;
        private readonly GroupNorm groupnorm;
        private readonly SiLU silu;

        public FinalLayer(long in_channels, long out_channels) : base("FinalLayer")
        {
            groupnorm = GroupNorm(32, in_channels);
            conv = Conv2d(in_channels, out_channels, kernelSize: 3, padding: 1);
            silu = SiLU();
            RegisterComponents();
        }

        public override Tensor forward(Tensor x)
        {
            using var _ = NewDisposeScope();
            x = groupnorm.forward(x);
            x = silu.forward(x);
            var output = conv.forward(x);
            return output.MoveToOuterDisposeScope();
        }
    }

    public class Diffusion : Module<Tensor, Tensor, Tensor, Tensor>
    {
        private readonly TimeEmbedding time_embedding;
        private readonly UNet unet;
        private readonly FinalLayer final;

        public Diffusion() : base("Diffusion")
        {
            time_embedding = new TimeEmbedding(320);
            unet = new UNet();
            final = new FinalLayer(320, 4);
            RegisterComponents();
        }

        public override Tensor forward(Tensor latent, Tensor context, Tensor time)
        {
            using var _ = NewDisposeScope();
            time = time_embedding.forward(time);
            var output = unet.forward(latent, context, time);
            output = final.forward(output);
            return output.MoveToOuterDisposeScope();
        }
    }
}

**Comment by NiklasGustafsson** [comment]
Another solution may be to use a ModuleDict instead of the ModuleList that I suggested -- that way, you have more control over the names of your sub-modules, which is what you need for loading the state dict.

**Comment by NiklasGustafsson** [comment]
@williamlzw -- I've been thinking about this a bit. I'll do some experimenting tomorrow. 

It'll be some sort of abstract base class between `Module<Tensor,Tensor>` and `Sequential` that you would then override. We would have to not call it `Sequential`, though, and then your SwitchSequential would derive from that, instead.

**Comment by NiklasGustafsson** [comment]
@williamlzw -- in my personal fork, I added a "general" Sequential base class:

https://github.com/NiklasGustafsson/TorchSharp/blob/genseq/src/TorchSharp/NN/GenericSequential.cs

If you could take that and see if it meets your needs, I could document it and merge it before the next release. Here's how I used it in a unit test:

```C#
[Fact]
public void HeterogeneousSequential()
{
    var lin = torch.nn.Linear(20, 20);
    var bl = torch.nn.Bilinear(20, 30, 40);

    var input1 = torch.randn(new long[] { 128, 20 });
    var input2 = torch.randn(new long[] { 128, 30 });

    var x = lin.call(input1);
    var y = bl.call(x, input2);

    var hs = new HeterogeneousSeq(input2, ("lin",lin), ("bl", bl));

    var z = hs.call(input1);

    Assert.Equal(y, z);
}

class HeterogeneousSeq : SequentialAbstractBase
{
    private torch.Tensor input2;

    internal HeterogeneousSeq(torch.Tensor input2, params (string name, torch.nn.Module)[] modules) : base(modules)
    {
        this.input2 = input2;
    }

    public override torch.Tensor forward(torch.Tensor input)
    {
        var modules = this.modules().ToArray();

        using var _ = torch.NewDisposeScope();

        var result = input.alias();

        for (var idx = 0; idx < modules.Length; idx++) {
            switch (modules[idx]) {
            case Bilinear bl:
                result = bl.call(result,input2);
                break;
            case torch.nn.Module<torch.Tensor, torch.Tensor> m:
                result = m.call(result);
                break;
            }
        }

        return result.MoveToOuterDisposeScope();
    }

    protected override SequentialAbstractBase Slice(int start, int end)
    {
        throw new System.NotImplementedException();
    }
}
```

**Comment by NiklasGustafsson** [comment]
Just copy the file to your project and check it out, you shouldn't have to build your own TorchSharp lib.

**Comment by NiklasGustafsson** [comment]
Got it! Back to the drawing board... more to come, then.

**Comment by NiklasGustafsson** [comment]
@williamlzw -- okay, new version. This time, it's a generic. Here's how I use it with the unit test (you'll have to use the version with four type parameters, all of which should be 'Tensor':

```C#
[Fact]
public void HeterogeneousSequential()
{
    var lin = torch.nn.Linear(20, 20);
    var bl = torch.nn.Bilinear(20, 30, 40);

    var input1 = torch.randn(new long[] { 128, 20 });
    var input2 = torch.randn(new long[] { 128, 30 });

    var x = lin.call(input1);
    var y = bl.call(x, input2);

    var hs = new HeterogeneousSeq(input2, ("lin",lin), ("bl", bl));

    var z = hs.call(input1, input2);

    Assert.Equal(y, z);
}

class HeterogeneousSeq : Sequential<Tensor,Tensor,Tensor>
{
    private torch.Tensor input2;

    internal HeterogeneousSeq(torch.Tensor input2, params (string name, torch.nn.Module)[] modules) : base(modules)
    {
        this.input2 = input2;
    }

    public override torch.Tensor forward(torch.Tensor x, torch.Tensor y)
    {
        var modules = this.modules().ToArray();

        using var _ = torch.NewDisposeScope();

        var result = x.alias();

        for (var idx = 0; idx < modules.Length; idx++) {
            switch (modules[idx]) {
            case Bilinear bl:
                result = bl.call(result,y);
                break;
            case torch.nn.Module<torch.Tensor, torch.Tensor> m:
                result = m.call(result);
                break;
            }
        }

        return result.MoveToOuterDisposeScope();
    }
}
```

**Comment by NiklasGustafsson** [comment]
No, it doesn't. My mistake.

**Comment by williamlzw** [comment]
public class AttentionBlock : Module<Tensor, Tensor, Tensor>
      {
          private readonly Conv2d conv_output;
      
          public AttentionBlock(long n_head, long n_embd) : base("AttentionBlock")
          {
              var channels = n_head * n_embd;
              conv_output = Conv2d(channels, channels, kernelSize: 1);
              RegisterComponents();
          }
      
          public override Tensor forward(Tensor x, Tensor context)
          {
              using var _ = NewDisposeScope();
              var output = conv_output.forward(x);
              return output.MoveToOuterDisposeScope();
          }
      }
      
      public class TestNet: Module<Tensor, Tensor, Tensor, Tensor>
      {
          private readonly HeterogeneousSeq decoders;
          public TestNet() : base("TestNet")
          {
              decoders = HeterogeneousSeq(
                  ("1", new AttentionBlock(8, 40)),
                  ("2", Conv2d(3, 3, 1))
                  );
              RegisterComponents();
          }
      
          public override Tensor forward(Tensor x, Tensor context, Tensor time)
          {
              foreach (var layers in decoders)
              {
                  if (layers.GetType() == typeof(AttentionBlock))
                  {
                      x = ((Module<Tensor, Tensor, Tensor>)layers).forward(x, context);
                  }
                  else
                  {
                      x = ((Module<Tensor, Tensor>)layers).forward(x);
                  }
              }
              return x;
          }
      }


What I envision for HeterogeneousSeq is something like the code above.

**Comment by NiklasGustafsson** [comment]
In the original Python code you showed, the forward is implemented in the SwitchSequential, which is what the HeterogeneousSeq class corresponded to in the unit test. Substitute 'SwitchSequential' for 'HeterogeneousSeq' and that should be like the original you showed above.

If you want the "owning" class to do the forward implementation, as in your example right above here, you don't need Sequential at all, just a ModuleList or ModuleDict. The point of Sequential is to put the forward logic in the 'decoders' block itself, i.e. in the overridden forward inside SwitchSequential.

```C#
        class SwitchSequential : Sequential<Tensor,Tensor,Tensor,Tensor>
        {
            internal SwitchSequential(params (string name, torch.nn.Module)[] modules) : base(modules)
            {
            }

            public override torch.Tensor forward(torch.Tensor x, torch.Tensor context, torch.Tensor time)
            {
                using var _ = torch.NewDisposeScope();

                x = x.alias();

                foreach (var layer in modules()) {
                    switch (modules[idx]) {
                    case AttentionBlock abl:
                        x = abl.call(x,context);
                        break;
                    case ResidualBlock rbl:
                        x = rbl.call(x,time);
                        break;
                    case torch.nn.Module<torch.Tensor, torch.Tensor> m:
                        x = m.call(result);
                        break;
                    }
                }

                return x.MoveToOuterDisposeScope();
            }
        }
```

**Comment by NiklasGustafsson** [comment]
Remaining question, then, is whether it gets the names right so that you can load weights from a Python-exported state dictionary.

**Comment by williamlzw** [comment]
Yes. The exported weight names are similar to 
decoders.0.0.layernorm_1
decoders.0.1.layernorm_2

**Comment by NiklasGustafsson** [comment]
Okay, so I'll do some testing, etc., and then I'll get this into a PR. Please let me know if you find any usability issues with it.

**Comment by NiklasGustafsson** [comment]
It's worth throwing in a 'default' case in the switch statement and raise an exception, I think. Otherwise, unexpected blocks will just be skipped, not flagged:

```C#
default:
    throw new ArgumentException($"Invalid module type in {nameof(SwitchSequential)}.");

```

**Comment by NiklasGustafsson** [comment]
I've added a section about using the generic Sequential to the 'Custom Modules' wiki page:

https://github.com/dotnet/TorchSharp/wiki/Creating-Your-Own-TorchSharp-Modules
