### ISSUE TITLE
Register buffer

### ISSUE THREAD

**Issue by Sprinzl** [dotnet/TorchSharp#1114]
Hello maybe i do something wrong or it is a bug.
I try to save a Tensor in a Model. The  this.register_buffer("Y0", Y0); in the constructor. I change the Tensor later.
It somehow does not store the Tensor in may Model.

Thanks in advance.
Michael

**Comment by NiklasGustafsson** [comment]
@Sprinzl -- how, specifically, do you change the tensor? If you construct a new Tensor, that new Tensor wouldn't be registered, so that's expected. 

If you use an in-place operation, such as `copy_()` to overwrite the contents of the existing Tensor, and observe this behavior, then that's a bug.

**Comment by GeorgeS2019** [comment]
@Sprinzl 

Thank you for having an interest in learning Torchsharp. Welcome from Germany! I assume from your Github profile.

To help us understand how best to support you, **attaching** a simple example e.g. **torchsharpTest.zip** will help us understand your questions faster.

**Comment by NiklasGustafsson** [comment]
Repro cases are often useful, but in this case, it should not be necessary to attach a ZIP file.

**Comment by Sprinzl** [comment]
Ok _copy does the trick.  I am   woundering how to handle a different shape...             

                        var iy = 1.0 / ix;
                        pot = (pot * iy) + (Pot * (1.0 - iy));
                        this.Pot = Pot.copy_(pot); //Registered Buffer
                        this.PotCumulative = PotCumulative.copy_( pot.cumsum(1)); //Registered Buffer
                        this.Save();

Thank you Niklas.
