### ISSUE TITLE
exportsd.py how to save tensor with pytorch and load with torchsharp?

### ISSUE THREAD

**Issue by williamlzw** [dotnet/TorchSharp#1139]
exportsd.py how to save tensor with pytorch and load with torchsharp?

      def test_save_tensor():
          x = torch.ones(2, 2, 2, 2)
          f = open("tensora.dat", "wb")
          exportsd._write_tensor(x, f)
          f.close()

    //c#
     torch.Tensor x = torch.randn(2,2,2,2);
      var stream = File.Open("tensora.dat", FileMode.Open);
      var reader = new BinaryReader(stream, encoding:System.Text.Encoding.UTF8, false);
      x.Load(reader);
      x.print(style:TorchSharp.TensorStringStyle.Numpy);

**Comment by williamlzw** [comment]
I need to save the pytorch model inference and save it to a file, then load the file with torchsharp. Handy for verifying that c# post-processing methods are written correctly. You don't need to reason the model every time you run it.

**Comment by williamlzw** [comment]
I found the above conversion method, but the writing method is not simple enough.

**Comment by NiklasGustafsson** [comment]
> I found the above conversion method, but the writing method is not simple enough.

How would you like it to look? Always open to suggestions for improvements.

**Comment by williamlzw** [comment]
python:
  
  def test_save_tensor():
        x = torch.ones(2, 2, 2, 2)
        exportsd.write_tensor(x, "tensora.dat")
  
  //c#
   torch.Tensor x = torch.load_tensor("tensora.dat");
    x.print(style:TorchSharp.TensorStringStyle.Numpy);

**Comment by NiklasGustafsson** [comment]
Okay, I see. Your request is about writing and reading individual tensors, not state_dicts. Okay, that should be straight-forward.

**Comment by NiklasGustafsson** [comment]
It'll be `static Tensor.Load(string)` and `Tensor.Save(string)`, also with overloads for `Stream`, `BinaryReader/Writer`
