### ISSUE TITLE
tensor print optimization

### ISSUE THREAD

**Issue by williamlzw** [dotnet/TorchSharp#1142]
shape[1,77,768]
       Can print data with close locations be displayed?
       //python 
         tensor([[[-3.8917e+00, -2.5113e+00,  4.7167e+00,  ...,  1.1270e+00,
                  -2.2396e+00, -1.2505e+00],
                 [ 2.9914e-02,  5.6423e-01,  2.8374e-02,  ..., -2.5628e-01,
                  -5.3054e-01, -2.9966e-03],
                 [-2.1349e-01, -5.5431e-01, -7.1037e-01,  ...,  2.1956e-01,
                   8.7091e-02, -8.4753e-01],
                 ...,
                 [ 4.2301e-02, -4.4001e-01, -4.4282e-01,  ...,  6.5201e-01,
                  -3.0249e-01, -2.0086e-01],
                 [ 3.4720e-02, -4.3296e-01, -4.3660e-01,  ...,  6.7538e-01,
                  -3.1798e-01, -1.9269e-01],
                 [ 3.1171e-02, -3.6360e-01, -3.2888e-01,  ...,  6.4809e-01,
                  -2.7908e-01, -2.2351e-01]],
        
                [[-3.8917e+00, -2.5113e+00,  4.7167e+00,  ...,  1.1270e+00,
                  -2.2396e+00, -1.2505e+00],
                 [-4.3533e-02, -3.2126e-01, -1.1155e-01,  ...,  4.3668e-01,
                  -2.1201e-01, -4.5503e-02],
                 [-5.8780e-01, -5.1043e-01, -3.3263e-02,  ...,  1.0280e+00,
                   3.0414e-01, -9.6674e-01],
                 ...,
                 [-1.3889e-01, -2.8969e-01, -4.5040e-01,  ...,  7.5641e-01,
                  -4.6745e-01, -1.8153e-01],
                 [-1.4301e-01, -2.8429e-01, -4.4609e-01,  ...,  7.8050e-01,
                  -4.7931e-01, -1.7398e-01],
                 [-1.4289e-01, -1.9903e-01, -3.3218e-01,  ...,  7.6626e-01,
                  -4.3880e-01, -2.0482e-01]],
        
                [[-3.8917e+00, -2.5113e+00,  4.7167e+00,  ...,  1.1270e+00,
                  -2.2396e+00, -1.2505e+00],
                 [-6.3191e-01, -6.3897e-02, -1.8121e-01,  ..., -1.0667e+00,
                  -1.0416e+00, -1.6426e-01],
                 [-6.1471e-01,  5.4341e-01, -4.6983e-01,  ...,  5.7399e-01,
                  -1.1093e-02, -8.4604e-01],
                 ...,
                 [-3.4268e-01, -3.0228e-01, -4.2182e-01,  ...,  5.6220e-01,
                  -6.0012e-01, -2.5774e-01],
                 [-3.3000e-01, -3.0496e-01, -4.1568e-01,  ...,  5.8275e-01,
                  -6.0254e-01, -2.5020e-01],
                 [-3.7815e-01, -2.2963e-01, -3.0679e-01,  ...,  5.2398e-01,
                  -5.9870e-01, -2.7526e-01]]], device='cuda:0', grad_fn=<AddBackward0>)

        //c#
        [[[-3.8917, -2.5113, 4.7167, ... 1.127, -2.2396, -1.2505]  [-1.1935, 0.45616, 0.23719, ... -0.43066, -0.34218, -0.22676]  [-0.48245, 0.54961, -0.76683, ... 0.57444, 0.22785, -1.0039]  ...  [-0.31547, -0.29602, -0.2571, ... 0.88035, -0.4051, -0.53152]  [-0.31658, -0.29161, -0.24926, ... 0.89166, -0.40809, -0.52601]  [-0.32793, -0.2703, -0.18109, ... 0.85977, -0.37548, -0.53399]]]

**Comment by NiklasGustafsson** [comment]
You may want to experiment with specifying the newline string that's to be used.

**Comment by williamlzw** [comment]
I want to print data with the same location.Easy to verify data results.
          
          
          tensor([[[-3.8917e+00, -2.5113e+00,  4.7167e+00,  ...,  1.1270e+00,
                        -2.2396e+00, -1.2505e+00],///////no.1
                       [ 2.9914e-02,  5.6423e-01,  2.8374e-02,  ..., -2.5628e-01,
                        -5.3054e-01, -2.9966e-03],///////no.2
                       [-2.1349e-01, -5.5431e-01, -7.1037e-01,  ...,  2.1956e-01,
                         8.7091e-02, -8.4753e-01],///////no.3
                       ...,
                       [ 4.2301e-02, -4.4001e-01, -4.4282e-01,  ...,  6.5201e-01,
                        -3.0249e-01, -2.0086e-01],///////no.4
                       [ 3.4720e-02, -4.3296e-01, -4.3660e-01,  ...,  6.7538e-01,
                        -3.1798e-01, -1.9269e-01],///////no.5
                       [ 3.1171e-02, -3.6360e-01, -3.2888e-01,  ...,  6.4809e-01,
                        -2.7908e-01, -2.2351e-01]]///////no.6

**Comment by NiklasGustafsson** [comment]
I see. Well, the 'format' argument should give you control over that, it allows you to define a format for floating-points values, which I believe should provide this functionality. It's just the standard .NET FP formats.

You will also, depending on your OS, have to control the new line string.

**Comment by williamlzw** [comment]
It's not about defining the format, but the location of the printed data is the same.

**Comment by williamlzw** [comment]
Seems like there's no problem.
