### ISSUE TITLE
Add an option to dispose of Distributions / let it's Tensor parameters optionally be moved to wrapping dispose container

### ISSUE THREAD

**Issue by rejwan** [dotnet/TorchSharp#1158]
As the title says, when using a distribution, it detaches the given tensors from its dispose container; this means it's very uncontrollable and will only get GCed later down the line, hogging resources.

A suggested solution might be adding an `IDisposable` interface to distribution or adding a parameter in the constructor regarding the dispose container.

**Comment by NiklasGustafsson** [comment]
@rejwan: this sounds reasonable, but there are not enough details of what you actually imagine the user experience would be like. Could you provide some mocked-up code that illustrates how such improved distributions would be used in your code?

**Comment by NiklasGustafsson** [comment]
For example, should they automatically register themselves in the current DisposeScope, or not?

**Comment by NiklasGustafsson** [comment]
@rejwan: please see #1165 -- is that what you meant?

**Comment by NiklasGustafsson** [comment]
#1165 has been merged -- all distributions are now disposable. If there's more to your request, please reopen with more details.
