### ISSUE TITLE
Setting .bias on nn.Linear crashes

### ISSUE THREAD

**Issue by GilesBathgate** [dotnet/TorchSharp#1166]
```c#
using TorchSharp;
using static TorchSharp.torch;

namespace TorchSharpBug
{
    public class Program
    {
        static public void Main(string[] args)
        {
		var l = nn.Linear(5,6);
		l.bias = null; //Crash with no exception message.
		Console.WriteLine("Success!");
        }
    }
}
```

**Comment by GilesBathgate** [comment]
@NiklasGustafsson This is probably fixed by your yet to merge changes: https://github.com/NiklasGustafsson/TorchSharp/blob/unit/src/TorchSharp/NN/Linear.cs

**Comment by NiklasGustafsson** [comment]
It does. That PR is also incomplete, a WIP.

I can add an exception so that it won't blow up, but for now, avoid setting the bias, or any parameter of built-in modules to 'null'. Instead, create the module with `bias: false`

**Comment by NiklasGustafsson** [comment]
I'll use this to track adding meaningful argument validation on parameter modifications on native-code modules.
