### ISSUE TITLE
`Module.to(ScalarType)` has restrictions in `PyTorch` which aren't restricted in `TorchSharp`

### ISSUE THREAD

**Issue by shaltielshmid** [dotnet/TorchSharp#1180]
When calling `Module.to(ScalarType)` on a module, PyTorch has a restriction that the target dtype must be a floating point or a complex number. See [here](https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/module.py#L1136). 

Also, when it gets a floating point type, PyTorch only moves parameters that are already a floating_point type to the new type. See for example [here](https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/module.py#L1136). 

This is relatively trivial to add, would TorchSharp want to add the same restrictions?

**Comment by NiklasGustafsson** [comment]
Under the assumption that modules always participate in backprop, this constraint makes sense.
