### ISSUE TITLE
MissingMethodException when trying to declare a resnet18 model

### ISSUE THREAD

**Issue by MLSMITH-WSS** [dotnet/TorchSharp#1186]
### Discussed in https://github.com/dotnet/TorchSharp/discussions/1184

<div type='discussions-op-text'>

Hello! Wanted to see if anyone would be able to provide some guidance with using pre-built torchsharp models like resnet18. I am trying to declare it with the following line, but it's throwing a MissingMethodException when I do so. Stating the Module.load method is not found. 

Here's the line declaring the model:
var model = torchvision.models.resnet18(skipfc: true);

Here's the exact exception text:

System.MissingMethodException: 'Method not found: 'Module Module.load(System.String, Boolean, System.Collections.Generic.IList`1<System.String>)'.'

I am using the TorchSharp 0.101.1 package and TorchVision 0.100.7 and I have the libtorch-cpu-win-x64 as well. 
</div>

**Comment by NiklasGustafsson** [comment]
First thing to do is use the same version of TorchVision and TorchSharp. They should always be aligned. It cannot have caused this problem, but you also need to make sure you are using the latest version of libtorch, too.
