### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by theentropic** [dotnet/TorchSharp#1189]
I'm currently using the new ML.NET 3.0 with TorchSharp 0.101.4 to take a look at the new QuestionAnswering trainer.  When I go to fit the model to create the prediction engine, I'm getting the following error

```
Unhandled exception. System.MissingMethodException: Method not found: 'Module Module.load(System.String, Boolean, System.Collections.Generic.IList`1<System.String>)'.
   at Microsoft.ML.TorchSharp.Roberta.QATrainer.Trainer..ctor(QATrainer parent, IChannel ch, IDataView input)
   at Microsoft.ML.TorchSharp.Roberta.QATrainer.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
```
My code is as follows: 

```c-sharp
MLContext _context = new();

var data = _context.Data.LoadFromTextFile<QnaPair>(path: "TrainingData.csv", separatorChar: ',', hasHeader: true, allowQuoting: true, trimWhitespace: true);

var chain = new EstimatorChain<ITransformer>();
var estimatorQA = chain.Append(_context.MulticlassClassification.Trainers.QuestionAnswer("Context", "Question", "Answer"));

var transformer = estimatorQA.Fit(data);
var engine = _context.Model.CreatePredictionEngine<QnaPair, QnaAnswer>(transformer, data.Schema);
```

When I dive into the .pdb it looks to be failing at this line in the QATrainer.cs file: 
```c-sharp
QATrainer.Trainer trainer = new QATrainer.Trainer(this, ch, input);
```

Digging into that it looks like it's trying to load a .tsm file but I haven't been able to locate at it.  Can someone point me in the right direction?

**Comment by NiklasGustafsson** [comment]
This exception is usually an indication that you have an assembly (DLL) that was built against a different version of TorchSharp than the one you're using now. There was a breaking change related to Module.load() v0.101.3, so it makes sense that this is breaking if you haven't rebuilt everything in your project, or is using a version of TorchVision that is older.

See also: #1186, and my response to that issue.

**Comment by theentropic** [comment]
Thanks @NiklasGustafsson, I rolled back to 0.99.6 and I'm getting somewhere.  Appreciate the help.

**Comment by NiklasGustafsson** [comment]
You shouldn't have to roll back that far, or at all.

**Comment by theentropic** [comment]
Not sure what was going on - I updated the packages again and now everything is working fine.  This was a brand new project, so not sure where I went wrong initially.

**Comment by NiklasGustafsson** [comment]
Aha! You're using ML.NET... I overlooked that.

That explains it -- ML.NET needs the older version. I should add something about that to the README.
