### ISSUE TITLE
Using skipfc: true with resnet model doesn't appear to remove the fully connected layer

### ISSUE THREAD

**Issue by SmithyScript** [dotnet/TorchSharp#1192]
Hello. I'm trying to use the pretrained resnet152 model in torchvision.models . When I create the model using the line:

var resnet = torchvision.models.resnet152(skipfc: true);

I would expect the FC layer to be removed from the model. Is it accomplishing this in a different way than removing that layer? Is there another way I can accomplish removing that final layer from the resnet model?

Thanks for your help

**Comment by NiklasGustafsson** [comment]
I may have misunderstood, but I think that is the correct behavior.

In torchvision, the implementation of ResNet's forward is as follows:

```Python
    def _forward_impl(self, x: Tensor) -> Tensor:
        # See note [TorchScript super()]
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)

        x = self.avgpool(x)
        x = torch.flatten(x, 1)
        x = self.fc(x)

        return x
```

IOW, the FC layer is always there. What 'skipfc' in TorchSharp does is ignore the FC layer when loading weights from a file, instead leaving the linear layer with the random weights that is its default. This can be useful when you just want to train the linear layer for a new categorization scenario and leave all the residual layers having learned what they have learned.

**Comment by SmithyScript** [comment]
Okay gotcha that makes sense. So the FC layer isn't influenced by the weights, but is still changing the final shape. I'm trying to match up my model to what we currently use in pytorch. They are removing that fc layer at the end to extract the embeddings from images and I'm trying to see if I can match that exactly in my implementation. 

Do you know if it's possible to easily remove that final layer from the resnet model? Similar to how it's done in pytorch with this line:

resnet152 = models.resnet152(pretrained=True)
resnet152 = torch.nn.Sequential(*(list(resnet152.children())[:-1]))

**Comment by NiklasGustafsson** [comment]
Technically, you should be able to do the same thing in TorchSharp, just with LINQ and a Take() call instead of the list slicing. Haven't tried it, myself, but it should work...

**Comment by SmithyScript** [comment]
Okay I think I've got something along those lines now. I did also notice that there is a flatten layer that doesn't seem to be there on the pytorch resnet model. I tried removing both so it would have the same layers, but the output shape from executing that model is the same shape as the input tensor (1,3,224,224) whereas on pytorch it has the output shape of (1, 2048, 1, 1).  Here's what I had:


    var path = @"C:\ModelWeightFiles\model_weights.dat";
    var resnet = torchvision.models.resnet152();
    
    resnet.load(path);
    resnet.eval();
    
    var model = torch.nn.Sequential();
    
    foreach (var child in resnet.named_children().Take(9))
    {
        model.add_module(child.name, child.module);
    }

**Comment by NiklasGustafsson** [comment]
About the Flatten -- I've seen that in ResNet, too. Don't know why it's necessary. There are no weights or buffers, obviously, so it doesn't affect the state_dict

**Comment by SmithyScript** [comment]
It appears looking again that it just returned the same exact tensor back. 

var result= model.forward(inputTensor);

**Comment by NiklasGustafsson** [comment]
> It appears looking again that it just returned the same exact tensor back.
> 
> var result= model.forward(inputTensor);

Okay, I'm not sure I know what you're saying here -- does it return the exact same tensor (i.e. the 'Handle' property is the same), or one with identical elements?

**Comment by SmithyScript** [comment]
The handle property is different between the input and output tensor. But looking at the bytes property, both are identical. Do I need to define a new forward function for the new Sequential I created?

**Comment by SmithyScript** [comment]
I think I've resolved this by using append() instead of add_module()
