### ISSUE TITLE
Torch device type CUDA did not initialise on the current machine

### ISSUE THREAD

**Issue by Zhengtinghao-jpg** [dotnet/TorchSharp#1196]
Hello! I want to use Torchsharp in Unity. But the CUDA seems to be unavailable. I have tried CUDA version with 11.6, 12.1. It's available when I use Pytorch.
![688CFC11-1167-430f-A062-CC9A05AA311A](https://github.com/dotnet/TorchSharp/assets/73380982/2299a183-d278-4b59-b6db-b1e48c8440d5)

**Comment by shaltielshmid** [comment]
Can you try adding the following line at the beginning of your main?

```cs
var _ = torch.CUDA;
```

**Comment by Zhengtinghao-jpg** [comment]
Yes, I'm using Torchsharp-cuda-windows 0.101.5, I added the code and the error showed:
![image](https://github.com/dotnet/TorchSharp/assets/73380982/642c3fd6-0749-426d-aa25-3301d1ab67f8)
Then I checked the folder but all .dll files in error are there.

**Comment by NiklasGustafsson** [comment]
Double-check that your drivers are completely up to date.

**Comment by Zhengtinghao-jpg** [comment]
Yes, the driver version is the latest (546.33), and my CUDA version is 12.1.0.

**Comment by NiklasGustafsson** [comment]
When you say that your CUDA version is 12.1, presumably you mean the CUDA toolkit. You don't have to have any toolkit installed, all the binaries are in the NuGet packages. The only CUDA installation that matters is the driver. Which packages are you using?

**Comment by NiklasGustafsson** [comment]
Beyond that, I'll need a little bit more details on what is found in the binaries folder where the application / service is created. Is this the same machine as where you built the app, or is it moved to / installed on a second machine?

**Comment by Zhengtinghao-jpg** [comment]
Thank you for the reminder. Due to my habit, I only moved some .dll files to my project. I attempted to configure using Nuget For Unity and was successful. Thank you for your help!
