### ISSUE TITLE
Hook is not being called.

### ISSUE THREAD

**Issue by lintao185** [dotnet/TorchSharp#1203]
In TorchSharp, I registered a hook for the model, but it seems that this hook is not being called.
```
var hook = new BasicHooks();
var conv = nn.Conv2d(3, 3, 1);
conv.register_forward_hook(hook.count_parameters);
using (torch.no_grad())
{
      conv.forward(torch.ones(3, 640, 640));
}
```

**Comment by NiklasGustafsson** [comment]
Not sure why you closed it, but if you want the hooks to be called, you need to use `call()` instead of `forward()`. The latter doesn't call the hooks in PyTorch, either, you have to call the module's `()` method.

**Comment by lintao185** [comment]
Yes, initially I didn't notice it, but later after reviewing the source code, I understood and thus closed it. Thank you very much indeed!
