### ISSUE TITLE
rng_state on cuda

### ISSUE THREAD

**Issue by yueyinqiu** [dotnet/TorchSharp#1230]
In PyTorch, [`get_rng_state`](https://pytorch.org/docs/stable/generated/torch.cuda.get_rng_state.html#torch.cuda.get_rng_state), [`get_rng_state_all`](https://pytorch.org/docs/stable/generated/torch.cuda.get_rng_state_all.html#torch.cuda.get_rng_state_all) and some other methods are there to provide access to the random generators on cuda devices. However I can't find those methods in TorchSharp. (But `torch.cuda.manual_seed` is here. That seems strange.)

Have I missed something? Or will those methods be added in later versions?

**Comment by NiklasGustafsson** [comment]
It has to do with how we integrate with the libtorch CUDA backend, and how we link against the cross-backend ATen APIs. It would require a fairly major overhaul of our build to fix this, which is something we can do, but would require some hard thinking...

See also: https://github.com/dotnet/TorchSharp/issues/1194

**Comment by yueyinqiu** [comment]
Perhaps I shall close this issue, since it looks like duplicate.
