### ISSUE TITLE
Missing attribute compare with Pytorch

### ISSUE THREAD

**Issue by ElinLiu0** [dotnet/TorchSharp#1232]
Hi i have to reconstruct a model called [vocos](https://github.com/gemelo-ai/vocos)
But i have trouble to dealing with model weight init.
In vocos original code,there has a period to initialize layer weight like below:
```python
def __init__(self, num_embeddings: int, embedding_dim: int, eps: float = 1e-6):
        super().__init__()
        self.eps = eps
        self.dim = embedding_dim
        self.scale = nn.Embedding(num_embeddings=num_embeddings, embedding_dim=embedding_dim)
        self.shift = nn.Embedding(num_embeddings=num_embeddings, embedding_dim=embedding_dim)
        torch.nn.init.ones_(self.scale.weight)
        torch.nn.init.zeros_(self.shift.weight)
```
I have found the `ones_()` method by using:
```csharp
using static TorchSharp.torch.nn.init;
```
But when i want initailize layer weight like what they do,visual studio has raise an error(translated from Chinese to English) like below:
```
Severity code description: Project file line suppression status
Error CS1061 'torch. nn. Module<torch. Tensor, torch. Tensor>' does not contain a definition for 'weight' and cannot find an accessible extension method 'weight' that accepts the first 'torch. nn. Module<torch. Tensor, torch. Tensor>' type parameter. (Is there a missing using directive or assembly reference?) VALLESharp D: \ VALLESharp \ VALLESharp \ Vocos \ Modules. cs 40 Activity
```

Not very happy to deal with that,btw,Happy Chinese NewYear! : )

**Comment by shaltielshmid** [comment]
Happy Chinese NewYear @ElinLiu0 !

Can you provide me with the sample C# code you used to get this issue?

The following snippet below worked for me:
```cs
var emb = torch.nn.Embedding(100, 20);
torch.nn.init.ones_(emb.weight);
```

**Comment by ElinLiu0** [comment]
> Happy Chinese NewYear @ElinLiu0 !
> 
> Can you provide me with the sample C# code you used to get this issue?
> 
> The following snippet below worked for me:
> 
> ```cs
> var emb = torch.nn.Embedding(100, 20);
> torch.nn.init.ones_(emb.weight);
> ```

Seems same as your provide version:
```python
internal class AdaLayerNorm : Module<Tensor,Tensor, Tensor>
{
    private double eps = 1e-6;
    private int dim;
    private Module<Tensor, Tensor> scale;
    private Module<Tensor, Tensor> shift;
    public AdaLayerNorm(string name,int num_embeddings,int embedding_dim) : base(name)
    {
        this.scale = torch.nn.Embedding(num_embeddings,embedding_dim);
        this.shift = torch.nn.Embedding(num_embeddings,embedding_dim);
        torch.nn.init.ones_(this.scale.weight);
        torch.nn.init.zeros_(this.shift.weight);
    }
    public override Tensor forward(Tensor x,Tensor cond_embedding_id)
    {
        var Scales = this.scale.forward(cond_embedding_id);
        var Shift = this.shift.forward(cond_embedding_id);
        x = nn.functional.layer_norm(x, [this.dim,],null,null,eps);
        x = x * Scales + Shift;
        return x;
    }
}
```

**Comment by shaltielshmid** [comment]
Ah, the problem is with these lines:

>     private Module<Tensor, Tensor> scale;
>     private Module<Tensor, Tensor> shift;

The general Module class doesn't have a weight attribute. You can solve it by changing those lines to:
```cs
using TorchSharp.Modules;
...
private Embedding scale;
private Embedding shift;
```

**Comment by ElinLiu0** [comment]
> Ah, the problem is with these lines:
> 
> > ```
> > private Module<Tensor, Tensor> scale;
> > private Module<Tensor, Tensor> shift;
> > ```
> 
> The general Module class doesn't have a weight attribute. You can solve it by changing those lines to:
> 
> ```cs
> using TorchSharp.Modules;
> ...
> private Embedding scale;
> private Embedding shift;
> ```
Right,i will using your namespace provided and bring reply if possible,thank you.
Btw,i will left this issue till the problem solved.

**Comment by ElinLiu0** [comment]
> Ah, the problem is with these lines:
> 
> > ```
> > private Module<Tensor, Tensor> scale;
> > private Module<Tensor, Tensor> shift;
> > ```
> 
> The general Module class doesn't have a weight attribute. You can solve it by changing those lines to:
> 
> ```cs
> using TorchSharp.Modules;
> ...
> private Embedding scale;
> private Embedding shift;
> ```

![image](https://github.com/dotnet/TorchSharp/assets/75596885/71443668-e3e3-4b03-85c9-464651a160f0)
Working fine and properly.
