### ISSUE TITLE
Question:How to slice Tensor as same way in Python

### ISSUE THREAD

**Issue by ElinLiu0** [dotnet/TorchSharp#1236]
As the title,how can i do the follow python code:
```python
Tensor = Tensor[:,0,0,pad:-pad]
```
into C#?

**Comment by NiklasGustafsson** [comment]
As long as you are on .NET 6 or later:

```C#
Tensor = Tensor[..,0,0,pad..^pad]
```

**Comment by ElinLiu0** [comment]
> As long as you are on .NET 6 or later:
> 
> ```cs
> Tensor = Tensor[..,0,0,pad..^pad]
> ```

Thanks,as primary language python for me,this is my first time try to slice a Tensor like this way,lol.
