### ISSUE TITLE
Mismatch Attribute from Pytorch

### ISSUE THREAD

**Issue by ElinLiu0** [dotnet/TorchSharp#1239]
In original Pytorch,when we call to norm a Tensor,it's maybe like:
```python
x = x.norm(dim,keep_dim,true)
```
Yet use in TorchSharp i can't do this.

**Comment by shaltielshmid** [comment]
I see on the PyTorch site [here](https://pytorch.org/docs/stable/generated/torch.norm.html) that the parameters for norm are (p, dim, keepdim)

In TorchSharp the parameters are named the same, but ordered slightly different (dim, keepdim, p). 

The following segments should be equivalent:

In PyTorch:
```python
dim = ...
keep_dim = ...
x = x.norm(dim=dim, keepdim=keep_dim)
```

In TorchSharp:
```cs
int dim = ...;
bool keep_dim = ...;
x = x.norm(dim: dim, keepdim: keep_dim);
```

**Comment by ElinLiu0** [comment]
> I see on the PyTorch site [here](https://pytorch.org/docs/stable/generated/torch.norm.html) that the parameters for norm are (p, dim, keepdim)
> 
> In TorchSharp the parameters are named the same, but ordered slightly different (dim, keepdim, p).
> 
> The following segments should be equivalent:
> 
> In PyTorch:
> 
> ```python
> dim = ...
> keep_dim = ...
> x = x.norm(dim=dim, keepdim=keep_dim)
> ```
> 
> In TorchSharp:
> 
> ```cs
> int dim = ...;
> bool keep_dim = ...;
> x = x.norm(dim: dim, keepdim: keep_dim);
> ```

Thanks for your replying mate,our team finally decided to use Python to serve the model instead of recostruct into C#.
