### ISSUE TITLE
cstr and npstr for 0d tensors

### ISSUE THREAD

**Issue by yueyinqiu** [dotnet/TorchSharp#1250]
`cstr` (or `ToString(TensorStringStyle.CSharp)`) on a 0d tensor (scalar) will return an empty string, due to [the line 6575 in Tensor.cs](https://github.com/dotnet/TorchSharp/blob/3f771acc3bd0e1f2d7ad8792dc0bc7efcf58d644/src/TorchSharp/Tensor/Tensor.cs#L6575).

Meanwhile I also found [the line 6582](https://github.com/dotnet/TorchSharp/blob/3f771acc3bd0e1f2d7ad8792dc0bc7efcf58d644/src/TorchSharp/Tensor/Tensor.cs#L6582), which also tries to check `t.Dimensions == 0` and print the scalar value, so I think the current behavior is not expected.

(Also for `npstr`.)

![image](https://github.com/dotnet/TorchSharp/assets/18749772/5d77e171-f742-49fd-ae1e-b96d48d91478)

**Comment by NiklasGustafsson** [comment]
Fixed in v0.102.0.
