### ISSUE TITLE
InverseMelScale in NewDisposeScope

### ISSUE THREAD

**Issue by yueyinqiu** [dotnet/TorchSharp#1257]
Hello! I'm now using `torchaudio.transforms.InverseMelScale` to convert a generated mel spectrum to its waveform.

I've found that the following code will continuously occupy more memory without freeing it, which finally crashed my application:

![image](https://github.com/dotnet/TorchSharp/assets/18749772/888f2273-d414-469b-a8bf-e994fe377030)

And if I remove `NewDisposeScope()`:

![image](https://github.com/dotnet/TorchSharp/assets/18749772/487c9b5c-d48f-4dd6-a3dd-9959eeb38aa3)

It seems that the dispose scopes will block the GC to release the tensors? I don't know much about that, so could anyone please check whether the behavior is expected?

And if it is, maybe the dispose scopes (or some other memory managment approaches) should be applied inside `InverseMelScale.forward` to release the tensors in the loop?

---

Here is my code and file:

```csharp
using TorchSharp;
using static TorchSharp.torch;

var melPath = "C:\\Users\\yueyinqiu\\Documents\\MyTemporaryFiles\\mymel.dat";
var tensor = Tensor.Load(melPath);
using (NewDisposeScope())
{
    var inverseMelScale = torchaudio.transforms.InverseMelScale(
        n_stft: 2048 / 2 + 1,
        n_mels: 512,
        sample_rate: 24000);
    var spec = inverseMelScale.call(tensor);
}
```

[mymel.zip](https://github.com/dotnet/TorchSharp/files/14498494/mymel.zip) (The file is generated from a untrained model so it is not a real mel spectrum.)

**Comment by shaltielshmid** [comment]
Thank you for pointing this out. I took a look at the code and there isn't any tensor management going on there, so when you added the dispose scope all the tensors were kept in memory for the entire scope.  

I'll rewrite it with more careful tensor management.

**Comment by NiklasGustafsson** [comment]
The dispose scopes are meant to automatically dispose of the native memory of all tensors created within its lifetime. Tensors are backed by memory allocated in C++, so not subject to GC, and not suppressed. 

The `forward()` in question does look very large, and should probably have a dispose scope around it (or several... :-)), but it's also a good idea to place one around your training and validation loops, etc., just as long as you remember to escaped the tensors that should survive the end of the scope.

**Comment by shaltielshmid** [comment]
> The `forward()` in question does look very large, and should probably have a dispose scope around it (or several... :-)), but it's also a good idea to place one around your training and validation loops, etc., just as long as you remember to escaped the tensors that should survive the end of the scope.

The specific issue in the forward is that it runs a full training loop without any dispose scope, so the critical dispose scope was the one added inside the loop to remove the tensors created with every iteration.

**Comment by NiklasGustafsson** [comment]
Since this was a pretty serious problem, I'm doing a fast-follower release today. It'll be v0.102.2
