### ISSUE TITLE
How to import model parameters without participating in training

### ISSUE THREAD

**Issue by zengnanhua** [dotnet/TorchSharp#1265]
How to import model parameters without participating in training

**Comment by zengnanhua** [comment]
怎么导入模型参数不参与训练  如：
 model = models.vgg16(pretrained = True)
  for param in model.parameters():
    param.requires_grad = False

**Comment by shaltielshmid** [comment]
In TorchSharp it would look the same:

```cs
var model = ...;
foreach (var param in model.parameters())
    param.requires_grad = False;
```

**Comment by zengnanhua** [comment]
model = models.vgg16(pretrained = True)   How to import the trained parameters of python tourch model

**Comment by yueyinqiu** [comment]
pytorch（torchvision）的 api 是不是有改过？我没找到 `pretrained` 这个参数：https://pytorch.org/vision/main/models/generated/torchvision.models.vgg16.html

不过 TorchSharp 好像没有提供 `torchvision.models.VGG16_Weights` ，不知道直接下载然后 load state dict 能不能行。

**Comment by yueyinqiu** [comment]
I've tried that, and I suppose it could be another issue, for which currently there are no beautiful solutions available.

If you don't mind, maybe you could download the pre-trained model with pytorch, and then try [TorchSharp.PyBridge](https://www.nuget.org/packages/TorchSharp.PyBridge) or [exportsd.py](https://github.com/dotnet/TorchSharp/blob/main/src/Python/exportsd.py) to load it into csharp.

Actually `torch.hub.download_url_to_file` could work in csharp. But I haven't found a beautiful way to resolve such a `.pkl` file. Perhaps some more features should be added into `TorchSharp.PyBridge`?

**Comment by yueyinqiu** [comment]
#713

**Comment by yueyinqiu** [comment]
I have uploaded [the converted model](https://huggingface.co/yueyinqiu/vision-TorchSharp/blob/main/VGG16_Weights.IMAGENET1K_FEATURES) to hugging face. Could the following code work for you?

```csharp
using TorchSharp;

var huggingFace = "https://huggingface.co/";
// var huggingFace = "https://hf-mirror.com/";

var file = new FileInfo("./vgg16.dat");
if (!file.Exists)
    torch.hub.download_url_to_file(
        $"{huggingFace}yueyinqiu/vision-TorchSharp/resolve/main/VGG16_Weights.IMAGENET1K_V1",
        file.FullName);

var model = torchvision.models.vgg16(weights_file: file.FullName);
```

**Comment by NiklasGustafsson** [comment]
@zengnanhua  - Is this still an issue? If resolved, please close. If not, please see if you can reply to @yueyinqiu's question.

**Comment by NiklasGustafsson** [comment]
No reply, so I'm closing this.
