### ISSUE TITLE
ConvTranspose3d does not accept non-uniform kernelSize/stride values

### ISSUE THREAD

**Issue by rogerOxHB** [dotnet/TorchSharp#1274]
I am trying to replicate a pytorch UNet model where one of the layers is defined as

`ConvTranspose3d(320, 320, kernel_size=(1, 2, 2), stride=(1, 2, 2))`

TorchSharp does not expose an interface to specify kernel sizes and strides as a tuple, but only as single long values.

The same is true for ConvTranspose2d.

**Comment by NiklasGustafsson** [comment]
PR merged. Release coming up.

**Comment by NiklasGustafsson** [comment]
v0.102.3 was just released with the fix for this.
