### ISSUE TITLE
Will TorchSharp support exporting ONNX models in the future?

### ISSUE THREAD

**Issue by lintao185** [dotnet/TorchSharp#1281]
In real-world projects, for quick deployment and application, PyTorch typically exports to ONNX, but it seems that TorchSharp does not currently support this feature.

**Comment by GeorgeS2019** [comment]
https://github.com/dotnet/TorchSharp/discussions/1111

https://github.com/dotnet/TorchSharp/discussions/526

**Comment by GeorgeS2019** [comment]
https://github.com/dotnet/TorchSharp/issues/973

**Comment by GeorgeS2019** [comment]
https://github.com/dotnet/machinelearning/issues/6884
> In order to enable this, **TorchSharp would need to enable export to ONNX**. No immediate work can be done in ML.NET at this time.

@luisquintanilla

**Comment by NiklasGustafsson** [comment]
While repeatedly asked for here, ONNX export is a complicated feature that, like torch.compile, will require careful design and planning. It has been on the backburner for a long time and is likely to remain so until we add significant resources to the project. Volunteers are always welcome, but it's not a simple thing to get working. If ONNX is essential to you, then PyTorch is the solution.

**Comment by lintao185** [comment]
This is just a suggestion; if TorchSharp is positioned for the C# ecosystem, then there is indeed no need to export other formats.

**Comment by NiklasGustafsson** [comment]
And it's a good suggestion... :-) Just something we don't have the resources to handle at the moment. Same thing with torch.compile -- it's something I would love to be able to add.

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson 

- torch.compile
