### ISSUE TITLE
tensor to array with shape

### ISSUE THREAD

**Issue by yueyinqiu** [dotnet/TorchSharp#1287]
Currently I could only find this in the tutorials:

```csharp
var t = torch.rand(2,5);
TorchSharp.Utils.TensorAccessor<float> ta = t.data<float>();
float[] a = ta.ToArray();
a
```

It returns a flattened `float[]`. Are there any other methods that could keep its shape?

**Comment by shaltielshmid** [comment]
I believe this can be done with `tensor.tolist()`

**Comment by yueyinqiu** [comment]
> I believe this can be done with `tensor.tolist()`

Umm... However it returns a arraylist of tensor, which is still far from something like `double[,]`.

**Comment by yueyinqiu** [comment]
Umm... Perhaps that is because it just work for 2D and cannot be widely used? Will using `Array` as the return type solve this problem? The users could easily get the strongly typed array with any dimension count, only through an explicit conversion.

**Comment by yueyinqiu** [comment]
Oh here is `ToNDArray` in `TensorAccessor`. I missed that...
