### ISSUE TITLE
in `RemoveDisposeScope`, we can't assume that `DisposeScopeStack.Peek() == disposeScope`

### ISSUE THREAD

**Issue by yueyinqiu** [dotnet/TorchSharp#1303]
```csharp
using TorchSharp;

var d1 = torch.NewDisposeScope();
var d2 = torch.NewDisposeScope();
d1.Dispose();

var tensor = torch.zeros([]);
d2.Dispose();

tensor.print();
// It could print.
// So this tensor leaks.
```

Also:

```csharp
using TorchSharp;

var d = torch.NewDisposeScope();
d.Dispose();
d.Dispose();
// InvalidOperationException
// But exceptions are always not expected when disposing something. 
```

**Comment by NiklasGustafsson** [comment]
The canonical way to create a DisposeScope should be `using var d1 = ...`

I don't think we should allow either one of those patterns you show, but if Dispose() shouldn't throw an exception, then I don't know how to enforce it properly. I do understand the PR now, but I'd rather we looked for a way to disallow improper use.

**Comment by yueyinqiu** [comment]
I suppose this won't cause any problem, and we could just allow it.

Another possible design is to also dispose the nested scope when disposing the outer one. But this cannot avoid the possible misuse in the first example.

**Comment by NiklasGustafsson** [comment]
> I suppose this won't cause any problem, and we could just allow it.
> 
> Another possible design is to also dispose the nested scope when disposing the outer one. But this cannot avoid the possible misuse in the first example.
> 
> Or we could just add a `if` statement to check `DisposeScopeStack.Peek() == disposeScope`. If not, just do nothing.
> 
> Hmm, this also seems a bad idea. My suggestion is to just allow it.

Let's allow it for now.

**Comment by yueyinqiu** [comment]
I have made it ready for review.
