### ISSUE TITLE
How do I get the value of such an attribute, just for display purposes.

### ISSUE THREAD

**Issue by lintao185** [dotnet/TorchSharp#1314]
![image](https://github.com/dotnet/TorchSharp/assets/55724885/916d2c78-8bdc-47f9-b911-090c995d8a30)

**Comment by yueyinqiu** [comment]
Ummm... DataLoaders would be modified significantly in the next release. #1306

But I still kept the fields private since nobody has asked for that... Perhaps it's time to change that as well.

For now, maybe you could use reflection as a work around.

**Comment by lintao185** [comment]
![image](https://github.com/dotnet/TorchSharp/assets/55724885/25622f39-f1e9-4ea6-8151-690b8ed57b4a)
I think these internal fields can be declared as public, right? PyTorch allows setting these attributes.

**Comment by yueyinqiu** [comment]
Maybe a new issue for this (

I think there are actually many many classes are not exposing enough things, like #1271

> I think these internal fields can be declared as public, right? PyTorch allows setting these attributes.

**Comment by NiklasGustafsson** [comment]
>> PyTorch allows setting these attributes.

Because Python can't prevent it. 

I think any .NET version needs to carefully consider what instance data should be modifiable / accessible and what should not.
