### ISSUE TITLE
Add register_pre_hook and register_hook for generic module class?

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/TorchSharp#1321]
the `register_pre_hook` and `register_hook` allows developers to extend the module loading behavior before and after `module.forward` is invoked, which is quite useful for implementing dynamic module loading behavior similarly with what accerlerator and llama.cpp does. Currently the two hooks are supported in typed module base classes like `Module<T>`, but they are missing in the generic module `Module`

Can we also add `register_pre_hook` and `register_hook` to the generic `Module` class as well? The two hooks can take an `Action<Module>` lambda as input. As for running order with other hooks from typed Module. The `register_pre_hook` can be invoked before all other typed pre hooks, and `register_hook` being invoked after all typed hooks.

**Comment by NiklasGustafsson** [comment]
Please elaborate on why this is important. The generic Module class is mostly intended as a base class, while the Module<...> classes are the ones that compose well with others.

**Comment by LittleLittleCloud** [comment]
Sure, the generic hook can be useful to develop a hook that can be applied to all modules.

One example is `DynamicLoadingHook` which move a module to a certain device before `module.forward` and unload the module from that device afterwards.

**Comment by NiklasGustafsson** [comment]
Okay, so does it make sense to keep the Action<Module<T>> overloads? They've been released, but I doubt there's a lot of use yet, so a breaking change won't be that bad.
