### ISSUE TITLE
`Module.to(Device)` will cause warnings because non-leaf tensors `.grad` is accessed (Also for optimizers)

### ISSUE THREAD

**Issue by yueyinqiu** [dotnet/TorchSharp#1323]
https://github.com/dotnet/TorchSharp/issues/1322#issuecomment-2147081809

**Comment by yueyinqiu** [comment]
That's a bit tricky.

We can't just check `param.requires_grad` because it might be a non-leaf tensor but `retains_grad`. I'm not sure whether there are any other situations.

**Comment by yueyinqiu** [comment]
Yes there are... We can simply do that in PyTorch:

```python
import torch.nn

x = torch.zeros([], requires_grad=False)
x.grad = torch.zeros([]) + 10
print(x.grad)  # tensor(10.)
```

So we cannot know whether their is a `grad` without accessing `.grad`... Perhaps the solution is to add a new C++ method for this. Or find a way to temporarily suppress the warning.

**Comment by NiklasGustafsson** [comment]
Would it be enough to check tensor.is_leaf before accessing grad in the toEpilog() logic?

**Comment by NiklasGustafsson** [comment]
I'm confused -- all the instances of `.grad` in Module are accessing parameters. How can they be non-leaf tensors?

**Comment by yueyinqiu** [comment]
Hmmm... This issue was created due to #1322 . In that issue, it's using `this.conv.weight[..] = nn.Parameter(x.view(1, c1, 1, 1));` to make it a non-leaf tensor.

**Comment by NiklasGustafsson** [comment]
So, should #1322 also be closed, then?
