### ISSUE TITLE
Request tensor factory methods accepting Span<T>

### ISSUE THREAD

**Issue by dje-dev** [dotnet/TorchSharp#1326]
Currently it is apparently required to provide an exactly sized array to the tensor static factory methods.

In the case where (for example) tensors are being created with variable batch sizes, the size of the input will vary. With the current design, it is necessary to allocate a new array appropriate for each batch (and one cannot use a pooled object which may be oversized).

Instead, callers may prefer to allocate a large fixed managed array and then only pass the appropriately sized Span over this array to the factor method, thereby saving an object allocation on every call.

Example given below of the suggested API enhancement (to be replicated across the various data types)
  EXISTING: public static Tensor tensor(short[] rawArray, ...
  DESIRED:  public static Tensor tensor(ReadOnlySpan`<Span>` rawSpan, ...

**Comment by NiklasGustafsson** [comment]
In order to create a tensor from the span, we would have to be able to pin it in memory, and GCHandle.Alloc() won't accept a Span<T>, as far as can tell. We can add the overloads as a convenience, but I believe the allocation (and copy) is going to have to happen.

**Comment by dje-dev** [comment]
Good point, Span doesn't quite work.

Instead one or both of these approaches could seemingly avoid one full memory copy of the full tensor to be loaded onto GPU:
1. Keep current signature but relax to accept oversized T[] relative to the provided shape, instead of throwing System.ArgumentException: 'mismatched total size creating a tensor from an array'
2. Follow the ONNX pattern of supporting this over Memory<T> (which has a Pin method):
   -  public static OrtValue CreateTensorValueFromMemory<T>(OrtMemoryInfo memoryInfo, Memory<T> memory, long[] shape) where T : unmanaged

**Comment by NiklasGustafsson** [comment]
We can easily accommodate the first method by just relaxing the constraints. Memory<T> can be pinned, but I don't know how to get a pointer to the underlying array without copying, which is needed in order to create a native tensor, so that requires more thought.

**Comment by NiklasGustafsson** [comment]
Addressed in PR #1329

**Comment by yueyinqiu** [comment]
@NiklasGustafsson

I would suggest an extra option to control this behavior, instead of cutting it implicitly.

Meanwhile just cutting the "tail" may be far from expectation. At least an option for start indices is also required to let this change make sense.

I know it's maybe... impossible currently. So actually I will suggest to consider this issue "not planned"/"not current" and revert the changes in #1329 .

**Comment by yueyinqiu** [comment]
Ahhh... I got that. It do solve the original case of this issue and could be useful in some other similar situations.

**Comment by NiklasGustafsson** [comment]
I figured out how to get the address out of a `Memory<T>`. Should have read the docs better... :-) I'm reopening and will add some Memory<T> overloads. Probably not as many different variants as for `T[]`

**Comment by NiklasGustafsson** [comment]
Okay, so both of @dje-dev suggestions have been implemented and merged. Thanks for the ideas!
