### ISSUE TITLE
The function torch.cuda.empty_cache() is missing.

### ISSUE THREAD

**Issue by lintao185** [dotnet/TorchSharp#1327]
The function torch.cuda.empty_cache() is missing.

**Comment by yueyinqiu** [comment]
might be similar to #1194

**Comment by yueyinqiu** [comment]
and for the memory issues... It's really hard to help you if you don't provide a way to reproduce them.

**Comment by lintao185** [comment]
The strange thing is that I added torch.NewDisposeScope() to every function, but it still leads to memory leaks. However, when I write a standalone demo, there are no issues. It's very puzzling, and I can't figure it out.

**Comment by lintao185** [comment]
I'm giving up for now. I'll come back to it after some time; maybe there will be a surprise.😊😊😊

**Comment by lintao185** [comment]
It seems I found the reason: TorchSharp doesn't have torch.cuda.amp, so more memory is needed to store the computation graph during training.

**Comment by NiklasGustafsson** [comment]
Torch doesn't seem to release GPU memory once it's been allocated, unless you call empty_cache(). It holds onto it for future needs.

This is a duplicate of https://github.com/dotnet/TorchSharp/issues/892, where I discussed some of the complications with implementing it, so I'll close this issue and keep the old one open.
