### ISSUE TITLE
Arrays of Arrays

### ISSUE THREAD

**Issue by travisjj** [dotnet/TorchSharp#1349]
Sorry of this seems too simple, I tried to localize the problem I was facing. I am trying to create a tensor with an array of an array of ints.

```
public static void ArrayOfArrays()
{
    int[][] ints = Enumerable.Range(0,50).Select( i => new int[] { 1, 2, 3 } ).ToArray();

    var inT = torch.tensor(ints);
    var inA = torch.from_array(ints);
}
```

inT fails to compile with "Error (active)	CS1503	Argument 1: cannot convert from 'int[][]' to 'bool'	"
inA fails during runtime with "System.NotSupportedException: 'The type System.Int32[] is not supported.'"

Okay, so the second response does seem fairly clear, perhaps this just isn't supported? Or is it just that I am doing it wrong?

Is there a way to properly create a tensor of the int[][] structure shown here? In pytorch it would look like:

```
ints = [] 
arr = [1] * 3
ints.append(arr)

inA = torch.tensor(ints);
```

Please let me know, ty

**Comment by yueyinqiu** [comment]
You shall use `int[,]` (multidimensional arrays) rather than `int[][]` (jagged arrays). Here we explained why we don't support jagged arrays currently https://github.com/dotnet/TorchSharp/issues/1347#issuecomment-2203495714.

You could use the following code to convert a 2d jagged array to a 2d array and create the tensor.

```csharp
using TorchSharp;

int[][] jagged = Enumerable.Range(0, 50).Select(i => new int[] { 1, 2, 3 }).ToArray();

int[,] multi = new int[50, 3];
for (int i = 0; i < multi.GetLength(0); i++)
{
    for (int j = 0; j < multi.GetLength(1); j++)
    {
        multi[i, j] = jagged[i][j];
    }
}

var tensor = torch.tensor(multi);
Console.WriteLine(tensor.cstr());

/*
[50x3], type = Int32, device = cpu, value =
int [,] {
 {1, 2, 3},
 {1, 2, 3},
 {1, 2, 3},
 ...
 {1, 2, 3},
 {1, 2, 3},
 {1, 2, 3}
}
*/
```

**Comment by travisjj** [comment]
Thank you @yueyinqiu for your assistance, I missed the nuance between jagged and multidimensional in this use. I appreciate it.

**Comment by NiklasGustafsson** [comment]
@travisjj -- can this be closed?

**Comment by travisjj** [comment]
@NiklasGustafsson Yes, this resolved the issue and worked in setting up the sample tensors I was using for training. Thanks
