### ISSUE TITLE
There may be an error in torchvision.transforms.GaussianBlur

### ISSUE THREAD

**Issue by williamlzw** [dotnet/TorchSharp#1400]
torchvision 0.103.1

long kernel = 21;
float sigma = 11;
var trans = torchvision.transforms.GaussianBlur(kernel, sigma); //System.ArgumentException:“Invalid GaussianBlur arguments.”

**Comment by williamlzw** [comment]
![Image](https://github.com/user-attachments/assets/3e5870b3-54ae-41e2-a4b1-944758da33ba)

**Comment by NiklasGustafsson** [comment]
I will take a look.

**Comment by NiklasGustafsson** [comment]
Interesting...

The problem arises because, from these two overloads:

```C#
            static public ITransform GaussianBlur(long kernel_size, float sigma)
            {
                return new GaussianBlur(new long[] { kernel_size, kernel_size }, sigma, sigma);
            }

            static public ITransform GaussianBlur(long kernel_size, float min = 0.1f, float max = 2.0f)
            {
                return new GaussianBlur(new long[] { kernel_size, kernel_size }, min, max);
            }
```

the compiler chooses the second. I'll fix that. It's going to be a breaking fix, but that'll be okay.

In the meantime, just pass in 'sigma' twice, and it should work.

**Comment by NiklasGustafsson** [comment]
> In the meantime, just pass in 'sigma' twice, and it should work.

Strike that. The '<=' makes sure that it does not.

**Comment by NiklasGustafsson** [comment]
@williamlzw -- take a look at #1401

**Comment by williamlzw** [comment]
Thanks.
