### ISSUE TITLE
Future engineering issues 

### ISSUE THREAD

**Issue by dsyme** [dotnet/TorchSharp#150]
In recent work on this repo the aim has been to

1. split out old Aten functionality

2. move to PyTorch 1.5.0 to have some hope of staying relevant and aligned

3. test and add functionality suitable for DiffSharp (currently the only downstream consumer)

4. make and upload CPU and CUDA packages that are actually usable for downstream pacakges without requiring installs/location-detect of CUDA binaries on each consuming system.

This work is now complete and the end result is that this repo is now less buggy, and at least provably useful as a substrate for DiffSharp, subject to the additional features needed in #140.

However some compromises have been necessary along the way.  For example:

* [ ] #146 covers the removal of PyTorch JIT model loading functionality

* [x] #135 covers the removal of support for MacOS CPU because the C++ code building against PyTorch 1.5.0 is not linking correctly

In addition, the very large size of the `libtorch-*` packages caused an odd form of hell on the CI systems, which were also based on somewhat older Azure CI DevOps functionality.  Debugging the problems with the package build and deployment was really very difficult because these size issues caused a bunch of failures.   

Here are the set of things we may want to look at going forward:

* [ ] In the README I've documented the process used to produce `libtorch-*` packages.  Because of their size and relative stability they are not currently created by default.  It is possible their creation and preparation should be split into a separate repository, as to be honest packaging such massive binaries in a way that's practical and usable is somewhat of a black art.

* [ ] The azure-pipelines.yml has some unfortunate hacks to get the libtorch packages to actually deploy reliably (basically the deployment tasks are re-run about 5 times).

* [ ] The CI pipeline used is now [here](https://donsyme.visualstudio.com/TorchSharp) rather than the CI build previously used.  

* [ ] The signed build is no longer availab.e

* [ ] The infrastructure used the "tools" setup for Microsoft projects.  This was removed because of bit rot

* [ ] The version numbering previously in use was very difficult to ascertain and a more manual versioning numbering has been applied, partly because the `libtorch-*` packages use a separate numbering scheme (since they are built and updated rarely, see above).  It might make sense to remove this and revert to a more standard approach.

I'm leaving the above here for documentation and explanation, they were necessary but these aren't things I plan to fix at the moment.

**Comment by interesaaat** [comment]
Happy to see this coming along.

**Comment by dsyme** [comment]
> Happy to see this coming along.

My apologies for the damage done along the way.  It's a bit tricky as for DiffSharp we really only need the tensor slice of functionality, not the modules/JIT portions.

Ideally we would have another contributor focusing on those parts.

**Comment by interesaaat** [comment]
I prefer to have something done than have the whole system half backed! I may try to get some time in the next quarter to look at the training part. 

Nevertheless, great work! And looking forward for the code generation of the API.

**Comment by NiklasGustafsson** [comment]
I believe everything in here has been covered in recent months.
