### ISSUE TITLE
Tracking PyTorch 1.7.0 additions

### ISSUE THREAD

**Issue by dsyme** [dotnet/TorchSharp#179]
Lots of additions in PyTorch 1.7.0 which can be made available here

Python API

__New namespaces:__

torch.fft added (#41911)
~~torch.linalg added (#42664)~~
torch.optim.functional added (#44715)

__New operators:__

~~torch.count_nonzero added (#39992)~~
~~nn.SiLU activation added (#41034)~~
~~torch.logit added (#41062)~~
~~torch.gcd, torch.lcm added (#40651, #41552, #42254)~~
~~torch.functional.atleast_{1d/2d/3d} added (#41317)~~
~~torch.isreal added (#41298)~~
~~nn.Unflatten added (#41564)~~
~~torch.movedim added (#41480)~~
~~torch.isposinf, torch.isneginf added (#41588)~~
~~torch.signbit added (#41589)~~
~~torch.absolute added (#42586)~~
~~torch.clip alias added (#42770)~~
~~torch.quantile added (#42755)~~
~~torch.linalg.det and torch.outer alias added (#42802)~~
~~torch.nansum added (#38628)~~
~~torch.hypot added (#42291)~~
~~torch.nextafter added (#42580)~~
~~torch.hstack, torch.vstack, torch.dstack added (#42799)~~
~~torch.arccosh alias added (#43107)~~
~~Tensor.movedim as a method added (#43122)~~
~~torch.matrix_exp added (#40161)~~
~~torch.fix alias added (#43326)~~
~~torch.arccos, torch.arcsin, torch.arctan aliases added (#43319)~~
~~torch.negative alias added (#43400)~~
~~torch.maximum, torch.minimum added (#42579)~~
~~torch.arctanh, torch.arcsinh aliases added (#43762)~~
~~torch.linalg.norm added (#42749, #43907)~~
~~torch.amax, torch.amin added (#43819)~~
~~torch.heaviside added (#42523)~~
~~torch.i0 added (#43132)~~
~~torch.not_equal, torch.greater, torch.greater_equal, torch.less, torch.less_equal aliases added (#43870)~~
~~torch.exp2 added (#44184)~~
~~torch.kaiser_window added (#44271)~~
~~torch.nanquantile added (#44393)~~
~~torch.multiply, torch.divide aliases added (#44463)~~
~~nn.TripletMarginWithDistanceLoss added (#43680)~~
~~torch.fft.fft, torch.fft.ifft, torch.fft.rfft, torch.fft.irfft, torch.fft.hfft, torch.fft.ihfft added (#43011)~~
~~torch.fft.fftn, torch.fft.ifftn, torch.fft.rfftn, torch.fft.irfftn added (#44550)~~
optim.functional.adagrad added (#44715)
optim.functional.adam added (#44791)
~~torch.complex, torch.polar added (#39617)~~
~~Tensor.__complex__ added (#43844)~~
~~torch.vdot added (#43004)~~

**Comment by NiklasGustafsson** [comment]
I'll use this space to keep track of what has been implemented from the list above:

Already in place:

[x] torch.gcd, torch.lcm added (#40651, #41552, #42254)

The following will be added with an upcoming PR:

[ ] torch.logit added (#41062)
[ ] torch.functional.atleast_{1d/2d/3d} added (#41317)
[ ] nn.Unflatten added (#41564)
[ ] torch.isposinf, torch.isneginf added (#41588)
[ ] torch.signbit added (#41589)
[ ] torch.absolute added (#42586)
[ ] torch.clip alias added (#42770)
[ ] torch.arccosh alias added (#43107)
[ ] torch.negative alias added (#43400)
[ ] torch.not_equal, torch.greater, torch.greater_equal, torch.less, torch.less_equal aliases added (#43870)
[ ] torch.exp2 added (#44184)
[ ] torch.hstack, torch.vstack, torch.dstack added (#42799)
[ ] torch.nansum added (#38628)
[ ] torch.hypot added (#42291)
[ ] torch.nextafter added (#42580)
[ ] torch.multiply, torch.divide aliases added (#44463)
[ ] torch.maximum, torch.minimum added (#42579)
[ ] torch.heaviside added (#42523)
[ ] torch.i0 added (#43132)
[ ] torch.vdot added (#43004)
