### ISSUE TITLE
Tracking PyTorch 1.6.0 additions

### ISSUE THREAD

**Issue by dsyme** [dotnet/TorchSharp#180]
See https://github.com/pytorch/pytorch/releases/tag/v1.6.0

* Automatic mixed precision (AMP) training is now natively supported and a stable feature - thanks to NVIDIA’s contributions;

* The torch.autograd.profiler API now includes a memory profiler that lets you inspect the tensor memory cost of different operators inside your CPU and GPU models.

Some snippets

__New Operators__

~~torch.logcumsumexp added (#36308)~~
~~torch.logaddexp added (#38384)~~
~~torch.rad2deg, torch.deg2rad added (#38852)~~
~~torch.arccosh, torch.arcsinh, torch.arctanh added (#38388)~~
~~torch.flip{lr, ud} added (#38599)~~
~~torch.bucketize, torch.searchsorted added (#34577)~~
~~torch.istft (Inverse Short Time Fourier Transform) added (#35569)~~
~~torch.vander: added support for generating Vandermonde matrices (#36725)~~
~~torch.block_diag added (#33449)~~
~~nn.functional.hardswish added (#34747)~~
~~torch.nn.init.trunc_normal_ (truncated normal initializer) added (#32397) (needs scalar erf implementation)~~
Added Stochastic Weight Averaging. See torch.optim.AveragedModel and torch.optim.SWALR for more details.(#35032)

__C++ API__
~~Added Optimizer AdamW to C++ frontend (#40009)~~
Custom C++ autograd function now supports c10::optional as parameters (#37700)
~~torch::Tensor now supports bitwise NOT(!), AND(&), OR(|), XOR(^) operators (#38691)~~
Cpp extension now supports load and load_inline under ROCm (#35897)

__[Beta] Complex Tensor support__
The PyTorch 1.6 release brings beta-level support for complex tensors. The UX is similar to existing PyTorch tensors and the new complex-specific functionality is compatible with NumPy’s complex arrays. In particular, you’ll be able to create and manipulate complex tensors, interop with previously existing code that represented complex tensors as tensors of size (..., 2), and more.

While this is an early version of this feature, and we expect it to improve over time, the overall goal is provide a NumPy compatible user experience that leverages PyTorch’s ability to run on accelerators and work with autograd to better support the scientific computing and ML communities.

**Comment by NiklasGustafsson** [comment]
I'll use this space to keep track of what has been implemented from the list above:

[x] logcumsumexp
[x] flip
[x] bitwise_and, bitwise_or, bitwise_not, bitwise_xor

The following are added with PR #237:

[ ] logaddexp
[ ] logaddexp2
[ ] logsumexp
[ ] rad2deg, deg2rad
[ ] arccosh, arcsinh, arctanh
[ ] AdamW optimizer
[ ] bucketize
[ ] vander
[ ] block_diag
