### ISSUE TITLE
Using TorchSharp with OnnxRuntime C# API

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/TorchSharp#197]
This will be a use case to motivate:

1.   having [the naming rules remaining the same as PyTorch](https://github.com/xamarin/TorchSharp/issues/95#issuecomment-629204784)
2.  [identifying the area of TorchSharp](https://github.com/xamarin/TorchSharp/issues/193#issuecomment-757947622) needed to work with OnnxRuntime C# API

For 1. OnnxRuntime makes use of [System.Numerics.Tensors](https://www.nuget.org/packages/System.Numerics.Tensors/) to pass Tensor to Onnx Model. We may need to make the naming rules of the TensorKind used in TorchSharp to be compatible with that of the OnnxRuntime C# API, System.Numerics. Tensors and e.g. TensorInt64 used in Windows.Ai.Machinelearning.

Why TorchSharp?

As [Onnx Model export becoming more reliable](https://github.com/onnx/models).  The Onnx community typically use e.g. PyTorch or Tensorflow to work with the eported Onnx Mode.  It makes sense for **TorchSharp** to be extended to **do the job of PyTorch for .NET develeoper** when **working with OnnxRuntime C# API.**

**Comment by NiklasGustafsson** [comment]
@GeorgeS2019 -- can you clarify what your specific ask is on this issue.

**Comment by GeorgeS2019** [comment]
For developers to follow up on this discussion, I recently share a feedback [here](https://github.com/dotnet/machinelearning/issues/5874#issuecomment-889848670).

**Comment by NiklasGustafsson** [comment]
I propose re-purposing this issue to simply request support for System.Numerics.Tensor once it is no longer a pre-release package.

**Comment by NiklasGustafsson** [comment]
I started looking into this -- how important is it to be able to share underlying storage, i.e. to avoid copying data when converting from S.N.Tensor to torch.Tensor?
