### ISSUE TITLE
Tracking PyTorch 1.8.0 additions

### ISSUE THREAD

**Issue by NiklasGustafsson** [dotnet/TorchSharp#238]
New functions (most of them to improve numpy compatibility):

~~torch.nan_to_num (#44592)~~ 
~~torch.tensor_split (#45168)~~
~~torch.nanmedian (#45847)~~
~~torch.ravel (#46098)~~
~~torch.igamma (#46183)~~ 
~~torch.igammac (#48171)~~ 
~~torch.column_stack (#46313)~~
~~torch.row_stack} (#46313)~~ 
~~torch.kron (#45358)~~ 
~~torch.copysign (#46396)~~ 
~~Tensor.new_empty_strided (#47225)~~
~~torch.{swapdims,swapaxes} (#46041)~~
~~torch.tile (#47974)~~
~~torch.float_power (#44937)~~
~~torch.moveaxis (#48581)~~
~~torch.inner (#46716)~~ 
~~torch.msort (#48440)~~
~~torch.sinc (#48740)~~ 
~~torch.broadcast_to (#48997)~~ 
~~torch.xlogy (#48777)~~ 
~~torch.f{max,min} (#49312)~~ 
~~torch.diff (#50569)~~ 
~~torch.ldexp (#45370)~~ 
torch.broadcast_shapes (#43935)

~~linalg.tensorsolve (#46142)~~ 
~~linalg.cholesky (#46083)~~
~~linalg.tensorinv (#45969)~~
~~linalg.{eigh,eigvalsh} (#45526)~~ 
~~linalg.matrix_rank (#48206)~~ 
~~linalg.solve (#48456)~~ 
~~linalg.qr (#47764, #50046)~~
~~linalg.svd (#45562)~~
~~linalg.inv (#48261)~~ 
~~linalg.pinv (#48399)~~ 
~~linalg.slogdet (#49194)~~
~~linalg.cond (#45832)~~

New modules: 
~~nn.PixelUnshuffle (#49334)~~
~~nn.GaussianNLLLoss (#50886)~~

Automatic shape inference in torch.nn: 
nn.LazyLinear (#44538) 
nn.LazyConv{1,2,3}d 
nn.LazyConvTranspose{1,2,3}d (#47350)

**Comment by NiklasGustafsson** [comment]
```
New functions (most of them to improve numpy compatibility):

torch.nan_to_num (#44592) 
torch.tensor_split (#45168) 
torch.nanmedian (#45847) 
torch.ravel (#46098) 
torch.igamma (#46183) 
torch.igammac (#48171) 
torch.column_stack (#46313)
torch.row_stack} (#46313) 
torch.kron (#45358) 
torch.copysign (#46396) 
Tensor.new_empty_strided (#47225) 
torch.{swapdims,swapaxes} (#46041) 
torch.tile (#47974) 
torch.float_power (#44937) 
torch.moveaxis (#48581)
 torch.inner (#46716) 
torch.msort (#48440)
torch.sinc (#48740) 
torch.broadcast_to (#48997) 
torch.xlogy (#48777) 
torch.f{max,min} (#49312) 
torch.diff (#50569) 
torch.ldexp (#45370) 
torch.broadcast_shapes (#43935)

linalg.tensorsolve (#46142) 
linalg.cholesky (#46083)
linalg.tensorinv (#45969) 
linalg.{eigh,eigvalsh} (#45526) 
linalg.matrix_rank (#48206) 
linalg.solve (#48456) 
linalg.qr (#47764, #50046) 
linalg.svd (#45562) 
linalg.inv (#48261) 
linalg.pinv (#48399) 
linalg.slogdet (#49194)
linalg.cond (#45832)

New modules: 
nn.PixelUnshuffle (#49334) 
nn.GaussianNLLLoss (#50886)

Automatic shape inference in torch.nn: 
nn.LazyLinear (#44538) 
nn.LazyConv{1,2,3}d 
nn.LazyConvTranspose{1,2,3}d (#47350)
```

**Comment by NiklasGustafsson** [comment]
Implemented in next PR:

torch.nan_to_num (#44592)
torch.nanmedian (#45847) 
torch.igamma (#46183) 
torch.igammac (#48171) 
torch.ravel (#46098) 
torch.kron (#45358) 
torch.column_stack (#46313)
torch.row_stack} (#46313) 
torch.copysign (#46396) 
torch.{swapdims,swapaxes} (#46041)

**Comment by chriss2401** [comment]
Really nice work @NiklasGustafsson . Do you also plan to port JIT in the future ?

**Comment by NiklasGustafsson** [comment]
The JIT is, for sure, an important feature to add. It will require a lot more thought than the recent porting effort. Tracing should be relatively straight-forward, but script-based JIT will be more complicated.

**Comment by MosGeo** [comment]
Thank you for this push on getting these functions. This will go along way in helping C#  getting adapted for scientific applications.
