### ISSUE TITLE
Proposal for common .NET tokenization library

### ISSUE THREAD

**Issue by dsyme** [dotnet/TorchSharp#248]
@NiklasGustafsson see https://github.com/fslaborg/FsLab/discussions/6

**Comment by GeorgeS2019** [comment]
@dsyme there are valid reasons why HuggingFace dedicates an entire library ONLY on a wide variety of tokenization.  Hopefully some of us have sufficient experience on that.

The main motivation of working so hard to complete .NET binding to Torch API for NLP is to adhere as closely as possible to best practice used in HuggingFace.

.NET community has a number of excellent NLP .NET project. However, there is ONLY one that is truly transformer based (Seq2SeqSharp) and this is where the latest and future NLP AI will go, the very main motivation for the HuggingFace existence gaining industry standard.

**Comment by GeorgeS2019** [comment]
I suggest with sufficient feedback, we have two tokenization libraries. NOT ONE SINGLE Common tokenization library. One dedicated to adhere as closely as possible to the HuggingFace and the other will be called the e.g. common tokenization library.

**Comment by GeorgeS2019** [comment]
We are now sorting out here, please join the [discussion](https://github.com/xamarin/TorchSharp/issues/257#issuecomment-843450123)

The list of tokenizers considered in TorchText.Data Utils.cs are

- spacy
- moses ( perhaps fast-mosestokenizer )
- toktok
- revtok
- subword (SentencePiece as used in Seq2SeqSharp)

**Comment by aorgish** [comment]
Please, take a look at https://github.com/microsoft/BlingFire for tokenization

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson   [here ](https://github.com/xamarin/TorchSharp/issues/248#issuecomment-887450569)is a good source of HuggingFace tokenizers [Maintained by Microsoft!!!]  => Thanks @aorgish for sharing.

**Comment by NiklasGustafsson** [comment]
This will be addressed outside the scope of TorchSharp.
