### ISSUE TITLE
Missing TorchText.NN feature

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/TorchSharp#257]
The recent example: [SequenceToSequence.cs](https://github.com/xamarin/TorchSharp/blob/master/src/Examples/SequenceToSequence.cs) represents an excellent example of [**Tutorial 1**]: [SEQUENCE-TO-SEQUENCE MODELING WITH NN.TRANSFORMER AND **TORCHTEXT**](https://pytorch.org/tutorials/beginner/transformer_tutorial.html)

Together with the **SequenceToSequence Modeling** example, a number of TorchText classes were implemented:

Organized according to **TorchText** namespaces
- **TorchText.Data.Utils** => TorchText.Data.Utils.cs
- **TorchText.Data**:  => AG_NEWSReader.cs
- **TorchText.Vocab**: => Vocab.cs
- **TorchText.Datasets**: => Datasets.cs

It will make the TorchSharp more complete in term of TorchText if the following feature and example is implemented
- **TorchText.NN**:
- [**Tutorial 6**]: **[Transformers and Multi-Head Attention](https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/tutorial6/Transformers_and_MHAttention.html)** for TorchText.NN [multiheadattention.py](https://github.com/pytorch/text/blob/master/torchtext/nn/modules/multiheadattention.py)

 <img src="https://user-images.githubusercontent.com/49812372/118555563-19f40580-b763-11eb-8997-14024ed2545e.png" alt="HTML5 Icon" width="350" height="300"> 
 <img src="https://user-images.githubusercontent.com/49812372/118555930-8f5fd600-b763-11eb-9cdb-435bbdd1b7ff.png" alt="HTML5 Icon" width="200" height="200">

**Comment by NiklasGustafsson** [comment]
@GeorgeS2019 -- I have been thinking about the side-packages for a while. TorchText, TorchVision, etc. Because I didn't have a good idea of the full scenarios, I just added the functionality to the Examples, as utils. I think it's a good idea to start working on these packages for real, though.

I'm a little confused about Tutorial 6 -- it seems to be a vision tutorial, and I don't find any use of torchtext there, just torchvision.

That said, torchvision is another package that we need to get included, but I'll probably start working on the text functionality first.

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson 
The **.NET Transformer** framework [Seq2SeqSharp](https://github.com/zhongkaifu/Seq2SeqSharp)
has integrated, like TorchText,  Transformers with **Multi-Head Attention**  



![image](https://user-images.githubusercontent.com/49812372/118540925-65051d00-b751-11eb-8e7f-44d4ff4f1d64.png)


The TorchText.NN module that provides the Transformers with **Multi-Head Attention** , in my view, is essential for TorchSharp

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson

There are 6 NLP tutorials, 3 are NLP from scratch, independent of TorchText.
The other 3 are using TorchText (designed to make NLP deep learning design more industry standard)
- [x] Sequence-to-Sequence Modeling with nn.Transformer and TorchText
- [ ] TEXT CLASSIFICATION WITH THE TORCHTEXT LIBRARY
- [ ] LANGUAGE TRANSLATION WITH TRANSFORMER


![image](https://user-images.githubusercontent.com/49812372/118542518-66cfe000-b753-11eb-9eea-390d49bbfadb.png)

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson 

> I'm a little confused about Tutorial 6 -- it seems to be a vision tutorial, and I don't find any use of torchtext there, just torchvision.

Perhaps it is more important to focus on the 2 remaining TorchText tutorials as listed above.
The multihead implementation discussed in the tutorial 6 I quoted, if I am not wrong, was implemented independent of TorchText.NN's multihead

There is a lengthy discussion why the multihead feature has been transferred to TorchText.NN for various reasons that many of which are off my comprehension :-)

**Comment by NiklasGustafsson** [comment]
Thanks for those thoughts. The first of the two NLP tutorials that you list is, I believe, implemented [here](https://github.com/xamarin/TorchSharp/blob/master/src/Examples/TextClassification.cs). The second one, the language translation example, should be a great one to tackle next.

**Comment by NiklasGustafsson** [comment]
The translation tutorial depends on the 'spacy' package for language tokenization, and I don't suspect there's something similar for .NET. This speaks to a broader need to specify, design, and prioritize data processing libraries for TorchSharp.

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson 

The Data Processing step requires different types of tokenizers and spacy is only one of them

TorchText.Data   Utils.cs

```python
de_tokenizer = get_tokenizer('spacy', language='de_core_news_sm')
en_tokenizer = get_tokenizer('spacy', language='en_core_web_sm')
```

Other tokenizers anticipated by the **TorchText.Data** Utils.cs are

- spacy
- moses
- toktok
- revtok
- subword

Not all of them I have seen ported/made avaliable to .NET



```python
if tokenizer == "spacy":
        try:
            import spacy
            try:
                spacy = spacy.load(language)
            except IOError:
                # Model shortcuts no longer work in spaCy 3.0+, try using fullnames
                # List is from https://github.com/explosion/spaCy/blob/b903de3fcb56df2f7247e5b6cfa6b66f4ff02b62/spacy/errors.py#L789
                OLD_MODEL_SHORTCUTS = spacy.errors.OLD_MODEL_SHORTCUTS if hasattr(spacy.errors, 'OLD_MODEL_SHORTCUTS') else {}
                if language not in OLD_MODEL_SHORTCUTS:
                    raise
                import warnings
                warnings.warn(f'Spacy model "{language}" could not be loaded, trying "{OLD_MODEL_SHORTCUTS[language]}" instead')
                spacy = spacy.load(OLD_MODEL_SHORTCUTS[language])
            return partial(_spacy_tokenize, spacy=spacy)
        except ImportError:
            print("Please install SpaCy. "
                  "See the docs at https://spacy.io for more information.")
            raise
        except AttributeError:
            print("Please install SpaCy and the SpaCy {} tokenizer. "
                  "See the docs at https://spacy.io for more "
                  "information.".format(language))
            raise
    elif tokenizer == "moses":
        try:
            from sacremoses import MosesTokenizer
            moses_tokenizer = MosesTokenizer()
            return moses_tokenizer.tokenize
        except ImportError:
            print("Please install SacreMoses. "
                  "See the docs at https://github.com/alvations/sacremoses "
                  "for more information.")
            raise
    elif tokenizer == "toktok":
        try:
            from nltk.tokenize.toktok import ToktokTokenizer
            toktok = ToktokTokenizer()
            return toktok.tokenize
        except ImportError:
            print("Please install NLTK. "
                  "See the docs at https://nltk.org  for more information.")
            raise
    elif tokenizer == 'revtok':
        try:
            import revtok
            return revtok.tokenize
        except ImportError:
            print("Please install revtok.")
            raise
    elif tokenizer == 'subword':
        try:
            import revtok
            return partial(revtok.tokenize, decap=True)
        except ImportError:
            print("Please install revtok.")
            raise
    raise ValueError("Requested tokenizer {}, valid choices are a "
                     "callable that takes a single string as input, "
                     "\"revtok\" for the revtok reversible tokenizer, "
                     "\"subword\" for the revtok caps-aware tokenizer, "
                     "\"spacy\" for the SpaCy English tokenizer, or "
                     "\"moses\" for the NLTK port of the Moses tokenization "
                     "script.".format(tokenizer))
```

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson 

Just realized the **SentencePiece** is being considered in **TorchText.Data**  Functional.cs (To be implemented)

**Comment by GeorgeS2019** [comment]
Multi head in tensorflow is one of the Keras Layers
![image](https://user-images.githubusercontent.com/49812372/119033414-7a768300-b9ad-11eb-81ed-10d40b3778bd.png)

In PyTorch, Multi-head has been moved out as just another layers into TorchText. Why? The details and the thinking behind is the interesting part. 

Ideally, Microsoft AI engineers need to understand that and translate that reasons into .NET advantages in performance and YET coding style consistent with the reason why the multi head is meant to be in TorchText and not its original place "just as another layer".

**Comment by NiklasGustafsson** [comment]
@GeorgeS2019 -- in light of more recent discussions about tokenization, I'm closing this issue as outdated. If you disagree, please reopen with an explanation of what you think needs to be tracked.
