### ISSUE TITLE
Support GPT-2

### ISSUE THREAD

**Issue by NiklasGustafsson** [dotnet/TorchSharp#265]
Here's a suggestion I got via email from @GeorgeS2019:

There are GPT-2 .NET solutions using Python.NET (through tensorflow). 

These solutions provide the pre-tokenization .NET methods you need so you do not have to proceed from scratch:

https://github.com/losttech/GPT
 
The GPT-2 implemented using pyTorch: 

https://github.com/graykode/gpt-2-Pytorch

**Comment by lostmsu** [comment]
@NiklasGustafsson unfortunately, pre-tokenization .NET method in the first repository uses Python's `regex` library. One needs to rewrite their regex in .NET style to drop the dependency.

**Comment by GeorgeS2019** [comment]
@lostmsu   many different languages e.g. java, c# have done the pre-tokinization. The question is more about are we doing just for GPT-2 or are we doing **stepwise** the Transformer tokenization library, which comes with GPT-2 pre-tokenization.

**Comment by lostmsu** [comment]
As a developer, I don't think tokenization is in the scope of this library. At least not until there's a differentiable tokenizer.

**Comment by GeorgeS2019** [comment]
One of the above link states that the pre tokenization is done through [BytePairEncoding](https://github.com/losttech/GPT/blob/master/src/BytePairEncoding.cs)  - This has not been discussed as part of TorchText.  [Why we need community feedback so we do this right.](https://github.com/xamarin/TorchSharp/issues/248)

**Comment by GeorgeS2019** [comment]
@lostmsu   

>  tokenization is in the scope of TorchSharp

Yes,  it is either part of TorchText or Transformer Tokenization,  not part of TorchSharp,  so as other languages are doing this way.  In many ways, we simply see what other language bindings (e.g. java etc. ) of Torch is doing and learn from them.

**Comment by NiklasGustafsson** [comment]
I do agree that it belongs in its own package, just as it does in PT. That's why I placed all tokenization in 'Examples.Utils' for now, they are not part of TorchSharp itself.

That said, I think that a tokenization library will have to contend with the fact that ultimately, the data needs to go into a TorchTensor. Unfortunately, we don't have a shared tensor type across .NET bindings to machine learning libraries, which will impact our ability to share code between libraries like TorchSharp, Tensorflow.NET, and ML.NET.

**Comment by lostmsu** [comment]
@NiklasGustafsson as long as data can be read from `ReadOnlySpan<T>` I don't see a problem with every library doing it in its own way.

**Comment by NiklasGustafsson** [comment]
@lostmsu -- sure, that may be the way. I should take a look at creating a TorchTensor from a ROS<T> as an exercise.

**Comment by NiklasGustafsson** [comment]
I think that should work, in general and with relatively little effort. It seems to me that it would require a copy from the span to a new array, so that the data can be pinned while it's transferred to native memory in Torch. That may be okay at the end of a processing pipeline.

**Comment by lostmsu** [comment]
@NiklasGustafsson you should be able to pin `Span<T>` directly with `fixed` statement.

**Comment by GeorgeS2019** [comment]
@lostmsu thank you for sharing a valuable insight, that could only come from a person who is pioneering advanced AI in .NET.

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson 
Just a feedback/suggestion, start collecting TorchSharp custom modules to support the porting of [pytorch GPT-2](https://github.com/graykode/gpt-2-Pytorch) to TorchSharp


<img src="https://user-images.githubusercontent.com/49812372/123170716-21ea4800-d47b-11eb-960e-ec797bf5736e.png" alt="TorchSharp GPT-2" width="400" height="700">

**Comment by NiklasGustafsson** [comment]
I started playing with this, and realized that I had misrepresented the pinning issue -- it's not that the data has to be pinned while transferring memory to Torch, it's that the memory is not copied at all, and the data has to be kept live until the Tensor is created. Since Span<T> is a ref struct, it does not appear that we can allocate a pinning GCHandle for it. 

I don't know how Span<T>.ToArray() behaves, but I would assume it makes a copy, since who knows where the underlying data is coming from -- in the case of Tensor, for example, it's just native memory. That said, if a copy is acceptable in the case of conversion from one tensor format to another, then we can just use Span.ToArray() to accomplish the conversion. It would mean that the source and target do **not** share the underlying array.

**Comment by lostmsu** [comment]
@NiklasGustafsson according to [this doc](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/fixed-statement), `Span<T>` has `GetPinnableReference`, that might be usable directly or with `GCHandle`.

**Comment by lostmsu** [comment]
FYI, I made a [simple re-implementation of minGPT](https://github.com/losttech/Torch.MinGPT) with TorchSharp.

**Comment by NiklasGustafsson** [comment]
> FYI, I made a [simple re-implementation of minGPT](https://github.com/losttech/Torch.MinGPT) with TorchSharp.

That is very cool!!!

Would it make sense to add this to dotnet/TorchSharpExamples? If not, we should at least link to your repo from there.

**Comment by NiklasGustafsson** [comment]
@luisquintanilla -- you should take a look at @lostmsu's example. Maybe this is something that could be useful in ML.NET?

**Comment by GeorgeS2019** [comment]
@luisquintanilla @lostmsu @NiklasGustafsson 
I attempted to have an overview of minGPT. minGTP's priority is education. It is versatile and has been adapted for language generation, Q&A, etc.  

Microsoft has lots of experience in language generation using the industry standard: GPT2. For Q&A, there are sufficient .NET examples in github. 

The pytorch community has expanded the use case of minGPT to many different scenarios.  Having a TorchSharp port of minGPT could inspire others to broaden the implemented codes to different scenarios using TorchSharp. 

The other relevant question: how to coordinate the TorchSharp community working on the minGPT scenarios discussed above to eventually contribute to the foundation of TorchText for TorchSharp?

E.g. instead of following the examples and tutorials that come with TorchText, TorchText(TorchSharp) provides these examples and tutorials using minGPT.

**Comment by GeorgeS2019** [comment]
As I have shared feedback and through informal discussion on the reusability of GPT2 custom operators as key for better results from GPT2 inference [here](https://github.com/dotnet/TorchSharp/discussions/580#discussioncomment-2893376)

One of the bottlenecks for ML.NET (Langauge generation) and perhaps Microsoft Bot Framework is the lack of this easily available .NET library providing these reusable custom operators. 

@lostmsu has implemented some of these features in [minGPT](https://github.com/losttech/Torch.MinGPT) and [GPT2](https://github.com/losttech/GPT). However, we need to conceptualize how to make these features reusable.

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson 

This can be closed.

We now have users doing this
