### ISSUE TITLE
forward() should take a variable-length list of arguments

### ISSUE THREAD

**Issue by NiklasGustafsson** [dotnet/TorchSharp#323]
The pytorch Module.forward() function is defined to take a variable-length list of argument, while the TorchSharp implementation more or less assumes that you can only forward one Tensor "automatically" in a construct like Sequential.

**Comment by NiklasGustafsson** [comment]
Here's a design question I have. The most general solution would be to have a forward() that is declared as such:

```C#
public virtual object[] forward(object[])
```

but that would mean that there will be a lot of type casting, array indexing, and array creation in the common scenario, which is one tensor in, one tensor out.

We can easily overload the forward() function to take different kinds of arguments and return 'object', but that would complicate the implementation of Sequential, which won't statically know what is being passed from one layer to the next (in the current implementation it assumes one in, one out). A more complex implementation of Sequential would have to inspect the output of one layer and decide which overloaded version of forward() to invoke.

I'm not sure I like the options here, so I would be happy to get some thoughts on this.

**Comment by dsyme** [comment]
@NiklasGustafsson There's not really good solution.  DiffSharp has a generic `Model<TIn, TOut>` and we could do that but it doesn't really solve that much.  Having one virtual forward with the signature you show seems reasonable in the nature of things, pushing the complexity to Sequential.

**Comment by NiklasGustafsson** [comment]
@kaiidams, @MovGP0, @lostmsu -- looking for your input on this old issue. Most models fall into a few patterns for what forward() takes and returns, but the current implementation of Sequential expects it to be forward: Tensor -> Tensor. It would take a little bit of complexity and overhead to generalize fully, but...

**Comment by NiklasGustafsson** [comment]
We could, for example, make the only version of forward 'Tensor[] forward(params Tensor[] arguments);` and then have virtual methods `_forward(...)` for the common cases, which built-in modules override. The general version is then what is used by Sequential, but it will require a lot of allocations of arrays for the return values, which is a waste of time and space.

**Comment by lostmsu** [comment]
How about this option: simply add this method to `Module`:

```csharp
public virtual (Tensor, T) forward<T>(Tensor x, T extras)
  => (this.forward(x), extras);
```

**Comment by lostmsu** [comment]
I realized the previous suggestion does not cover scenarios with `T` being different for input and output. To cover that maybe something like

```csharp
public virtual (Tensor, TOut) forward<TIn, TOut>(Tensor x, T extras)
  => (this.forward(x), this.forward_extras<TIn, TOut>(extras));
protected virtual TOut forward_extras<TIn, TOut>(TIn extras)
  => typeof(TIn) == typeof(TOut) ? (TOut)(object)extras : throw new NotSupportedException();
```

**Comment by NiklasGustafsson** [comment]
I'm not so worried about getting the static typing right -- `Tensor` covers just about everything. However, it's the unknown number of inputs and outputs that require the use of arrays or lists, which is inefficient to manage, since they involve heap allocations.

**Comment by NiklasGustafsson** [comment]
And then, of course, there's going to be major breakage... Almost want to call the generic version 'call' instead of 'forward' just to avoid breaking code.

**Comment by NiklasGustafsson** [comment]
I'll sketch something in a WIP PR over the next couple of days...

**Comment by lostmsu** [comment]
> call the generic version 'call' instead of 'forward' just to avoid breaking code

IMHO, that's a bit excessive considering TS is < 1.0.0

**Comment by kaiidams** [comment]
> Sequential, which won't statically know what is being passed from one layer to the next

PyTorch's `Sequential.forward()` assume x->y function is https://github.com/pytorch/pytorch/blob/9c9f42481761c7f42f47c296a9dbee60f3407b90/torch/nn/modules/container.py#L202

```python
    def forward(self, input):
        for module in self:
            input = module(input)
        return input
```

Some of official PyTorch module accepts non-Tensor arguments, `LSTM`, `InverseSpectrogram`, `MaxUnpool1d`, etc. But in most cases, `Sequential` is used for `Tensor` functions.

**Comment by NiklasGustafsson** [comment]
https://pytorch.org/docs/stable/generated/torch.nn.Sequential.html#torch.nn.Sequential says that:

The forward() method of Sequential accepts any input and forwards it to the first module it contains. It then “chains” outputs to inputs sequentially for each subsequent module, finally returning the output of the last module.

**Comment by kaiidams** [comment]
It accepts any one argument, but not two.

```python
import torch
from torch import nn

class MyModule(nn.Module):
    def forward(self, x, y):
        return x + y, x - y
                
m = nn.Sequential(
    MyModule(),
    MyModule(),
    MyModule(),
)
m(torch.zeros(2), torch.zeros(2))
```

```
TypeError                                 Traceback (most recent call last)
[<ipython-input-30-e0b176883350>](https://localhost:8080/#) in <module>
     11     MyModule(),
     12 )
---> 13 m(torch.zeros(2), torch.zeros(2))

[/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

TypeError: forward() takes 2 positional arguments but 3 were given
```

**Comment by NiklasGustafsson** [comment]
But it will pass a tuple coming out of a layer to the next.

**Comment by kaiidams** [comment]
Yes, a tuple is a single object in Python. If we want it, then we can have
```
public virtual object forward(object input);
```

**Comment by kaiidams** [comment]
In PyTorch, the module has to accept a tuple as an argument.

```python
import torch
from torch import nn

class MyModule(nn.Module):
    def forward(self, input):
        x, y = input
        return x + y, x - y

m = nn.Sequential(
    MyModule(),
    MyModule(),
    MyModule(),
)
m((torch.zeros(2), torch.zeros(2)))
```

**Comment by NiklasGustafsson** [comment]
There will be a lot of dynamic type testing -- Sequential needs to dispose any temporary tensors after they've been passed to the next layer of forward(), so this is complicated...

**Comment by kaiidams** [comment]
Yes, `ScriptModule` can accept any input types and can return any outputs.

**Comment by NiklasGustafsson** [comment]
I'll take a look at Object -> Object a see how bad it gets...

**Comment by kaiidams** [comment]
In case of `ScriptModule`, I think it is more like

TorchSharp?
```csharp
  object forward(object[] inputs, IDictionary<string, object> kwargs = null);
```

LibTorch JIT https://github.com/pytorch/pytorch/blob/master/torch/csrc/api/include/torch/imethod.h
```cpp
  virtual c10::IValue operator()(
      std::vector<c10::IValue> args,
      const IValueMap& kwargs = IValueMap()) const = 0;
```

**Comment by NiklasGustafsson** [comment]
@dsyme  -- when I try to provide a general forward() like what @kaiidams suggested, the F# compiler gets and internal error:


```C#
public virtual object forward(object t) { ... }
public virtual Tensor forward(Tensor t) { ... }
public virtual Tensor forward(Tensor x, Tensor y) { ... }
public virtual Tensor forward(Tensor x, Tensor y, Tensor z) { ... }
```

```
.\TorchSharp\src\FSharp.Examples\TextClassification.fs(65,16): error FS3213: The member 'forward<'a0,'a1> : 'a0 -> 'a1' matches multiple overloads of the same method.Please restrict it to one of the following:   forward: obj -> obj   forward: torch.Tensor -> torch.Tensor   forward: torch.Tensor * torch.Tensor -> torch.Tensor   forward: torch.Tensor * torch.Tensor * torch.Tensor -> torch.Tensor.
.\TorchSharp\src\FSharp.Examples\SequenceToSequence.fs(77,55): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
.\TorchSharp\src\FSharp.Examples\SequenceToSequence.fs(77,55): error FS0752: The operator 'expr.[idx]' has been used on an object of indeterminate type based on information prior to this program point. Consider adding further type constraints
.\TorchSharp\src\FSharp.Examples\TextClassification.fs(65,16): error FS3213: The member 'forward<'a0,'a1> : 'a0 -> 'a1' matches multiple overloads of the same method.Please restrict it to one of the following:   forward: obj -> obj   forward: torch.Tensor -> torch.Tensor   forward: torch.Tensor * torch.Tensor -> torch.Tensor   forward: torch.Tensor * torch.Tensor * torch.Tensor -> torch.Tensor.
.\TorchSharp\src\FSharp.Examples\SequenceToSequence.fs(77,55): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
.\TorchSharp\src\FSharp.Examples\SequenceToSequence.fs(77,55): error FS0752: The operator 'expr.[idx]' has been used on an object of indeterminate type based on information prior to this program point. Consider adding further type constraints
.\TorchSharp\src\FSharp.Examples\AdversarialExampleGeneration.fs(61,17): error FS0039: The namespace or module 'MNIST' is not defined. Maybe you want one of the following:   List
.\TorchSharp\src\FSharp.Examples\AdversarialExampleGeneration.fs(106,29): error FS0039: The namespace or module 'MNIST' is not defined. Maybe you want one of the following:   List
.\TorchSharp\src\FSharp.Examples\AdversarialExampleGeneration.fs(109,19): error FS0039: The field, constructor or member 'trainingLoop' is not defined.
.\TorchSharp\src\FSharp.Examples\AdversarialExampleGeneration.fs(116,29): error FS0039: The namespace or module 'MNIST' is not defined. Maybe you want one of the following:   List
.\TorchSharp\src\FSharp.Examples\AdversarialExampleGeneration.fs(117,13): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
.\TorchSharp\src\FSharp.Examples\AdversarialExampleGeneration.fs(120,5): error FS0073: internal error: tcrefOfAppTy (Failure)
.\TorchSharp\src\FSharp.Examples\AdversarialExampleGeneration.fs(120,5): error FS0073: internal error: tcrefOfAppTy (Failure)
.\TorchSharp\src\FSharp.Examples\AdversarialExampleGeneration.fs(90,5): error FS0073: internal error: tcrefOfAppTy (Failure)
.\TorchSharp\src\FSharp.Examples\AdversarialExampleGeneration.fs(90,5): error FS0073: internal error: tcrefOfAppTy (Failure)
.\TorchSharp\src\FSharp.Examples\AdversarialExampleGeneration.fs(88,1): error FS0073: internal error: tcrefOfAppTy (Failure)
.\TorchSharp\src\FSharp.Examples\AdversarialExampleGeneration.fs(2,1): error FS0073: internal error: tcrefOfAppTy (Failure)
.\TorchSharp\src\FSharp.Examples\AdversarialExampleGeneration.fs(2,1): error FS0073: internal error: tcrefOfAppTy (Failure)
error FS0192 : internal error : tcrefOfAppTy
error FS0073 : internal error : tcrefOfAppTy (Failure)
error FS0192 : internal error : tcrefOfAppTy
```

**Comment by lostmsu** [comment]
The allocations with array of tensors does not apply if we use `ValueTuple`, which BTW fits into `Module<TIn, TOut>`, which I am starting to like more and more.

Sequential can easily be a `Module<T, T>`, and for heterogeneous case `Module<TIn, TOut>` can have a function or even an operator for chaining. E.g. `Module<TIn, TNewOut> compose<TNewOut>(Module<TOut, TNewOut>)`

**Comment by NiklasGustafsson** [comment]
Some modules, like MaxPool, returns either a single Tensor or a tuple, and Sequential has to be able to pass any data from one layer to the next.

The object -> object solution is ugly, but it should cover all bases, I think.

**Comment by lostmsu** [comment]
@NiklasGustafsson that's why I suggest compose. So a convnet would look like:
```csharp
Sequential(new [] {
  Conv2D(xxx).compose(MaxPool(yyy)), 
  Conv2D(xxx).compose(MaxPool(yyy)),
  ...
})
```

**Comment by NiklasGustafsson** [comment]
I compared running a fully general Sequential.forward() vs. one that is Tensor->Tensor. The former takes 2x the time with all the dynamic checking involved.

**Comment by NiklasGustafsson** [comment]
I have a sketch of a solution at: 

https://github.com/dotnet/TorchSharp/pull/757
