### ISSUE TITLE
Feedback to the plan for Torch integration to ML.NET

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/TorchSharp#328]
[TorchSharp integration to ML.NET](https://github.com/dotnet/machinelearning/projects/26#card-62428046)is currently being planned (supervised by @ericstj ) as recently shared/discussed by @NiklasGustafsson 

I suggest TorchSharp users provide feedback to the integration process here.

As part of the integration, the question h[ow to consume exported Torch model by ML.NET](https://github.com/dotnet/machinelearning/projects/26#card-62428098) has been planned.

I also would like to raise some issues raised before related to the above.
- Will there be an improvement in how TorchSharp consume Torch model created in python. Currently we need an additional python script to create a TorchSharp compatible model in python. Is there a plan soon that **this additional step will be removed**, perhaps as part of the ML.NET integration planning process? 
- There are challenges dealing with ONNX, especially when dealing with NLP use cases (e.g. [ref 1](https://github.com/dotnet/machinelearning/issues/5874#issuecomment-889848670), [ref 2](https://github.com/dotnet/machinelearning/issues/5874#issuecomment-900495155)). Is there a plan to consider incorporating [**ONNX save and load features in TorchSharp**](https://github.com/xamarin/TorchSharp/issues/146#issue-629388982)? By having Onnx save/load in TorchSharp, this provides an alternative path to the existing option to import ONNX to ML.NET

**Comment by ericstj** [comment]
cc @michaelgsharp @briacht
At the moment we're still trying to understand what this work would look like.  Thanks for raising concerns and we'll make sure to stay engaged in the discussion.

**Comment by GeorgeS2019** [comment]
FYI: **latest** [Plan for Deep learning and TorchSharp integration to ML.NET!!!](https://github.com/dotnet/machinelearning/issues/5918#issue-983175573)
