### ISSUE TITLE
Possible inconsistency between implementation and examples

### ISSUE THREAD

**Issue by mlinke-ai** [dotnet/TorchSharp#329]
Is there an inconsistency between
https://github.com/xamarin/TorchSharp/blob/93a03123c7cf6657d479e89bb55902ae9db17794/src/Examples/MNIST.cs#L128
and
https://github.com/xamarin/TorchSharp/blob/93a03123c7cf6657d479e89bb55902ae9db17794/src/TorchSharp/NN/Module.cs#L77 ?
The constructor of `Module` takes three arguments and `base(name)` gives just one. VisualStudio complains that `torch.nn.Module` has no constructor with one argument.

**Comment by NiklasGustafsson** [comment]
You will need the newest set of changes, which have not been released to NuGet yet. To use the latest examples, you have to build TorchSharp yourself. The protected constructor that is meant for custom modules is located on line 527 in the current master branch.
