### ISSUE TITLE
XLA support?

### ISSUE THREAD

**Issue by gbaydin** [dotnet/TorchSharp#346]
Hi, are there any plans to support [XLA](https://pytorch.org/xla/release/1.9/index.html) through TorchSharp?

**Comment by dsyme** [comment]
@gbaydin XLA is in DeviceType but no particular plans beyond that https://github.com/dotnet/TorchSharp/blob/45056ff4de0791126e56a186777821767033d5d5/src/TorchSharp/Torch.cs#L391

**Comment by NiklasGustafsson** [comment]
Can we test XLA on Nvidia GPUs, or is a TPU necessary?
