### ISSUE TITLE
Autograd Unit Test Failing / Disabled

### ISSUE THREAD

**Issue by NiklasGustafsson** [dotnet/TorchSharp#367]
TestAutoGradMode() started failing intermittently.

**Comment by Mattias-NCVIB** [comment]
It seems to me that no_grad isn't thread safe? So even if it's turned off by this test, it might be turned on by another test?

Say if TestTrainingWithDropout and TestAutoGradMode are running at the same time.

**Comment by NiklasGustafsson** [comment]
The test had already been enabled. Checking to see if it works on MacOS now.
