### ISSUE TITLE
Add support for loading ONNX models.

### ISSUE THREAD

**Issue by NiklasGustafsson** [dotnet/TorchSharp#379]
### Discussed in https://github.com/dotnet/TorchSharp/discussions/377

Add support for loading ONNX models for the purpose of transfer learning in TorchSharp.

**Comment by GeorgeS2019** [comment]
https://github.com/dotnet/TorchSharp/discussions/526

**Comment by NiklasGustafsson** [comment]
Since this is covered under the Discussions section, I'll close the issue.

**Comment by GeorgeS2019** [comment]
[Implement Torch.ONNX](https://github.com/dotnet/TorchSharp/discussions/526)
