### ISSUE TITLE
Reuse Functional.cs for Transform

### ISSUE THREAD

**Issue by ekagra-ranjan** [dotnet/TorchSharp#382]
Hi,

Currently, **TorchSharp.torchvision.transforms.functional** has all the implementations of transforms from Pytorch. I find some transforms, e.g., [Normalize](https://github.com/dotnet/TorchSharp/blob/117efa13aa796d178a0c49711cbb046402aafe80/src/TorchSharp/TorchVision/Normalize.cs#L13), that have their own implementations in their respective files as well as in [Functional.cs](https://github.com/dotnet/TorchSharp/blob/main/src/TorchSharp/TorchVision/Functional.cs) file. 

Should I remove the implementations of such transforms from their respective files and call the implementations from [Functional.cs](https://github.com/dotnet/TorchSharp/blob/main/src/TorchSharp/TorchVision/Functional.cs) instead?

**Comment by GeorgeS2019** [comment]
@ekagra-ranjan 

Ideally to give a quick overview the extend of coverage of TorchVision implemented in TorchSharp, the organization of files ideally follow that of [TorchVision](https://github.com/pytorch/vision/tree/main/torchvision)

e.g. TorchSharp/src/TorchSharp/TorchVision/Transforms

The [Functional.cs](https://github.com/dotnet/TorchSharp/blob/main/src/TorchSharp/TorchVision/Functional.cs) refers to [functional.py](https://github.com/pytorch/vision/blob/main/torchvision/transforms/functional.py)

Ideally, we need to provide an easy way to communicate to what extend the methods in functional.py have been implemented in Functional.cs => so users interested to use TorchVision in TorchSharp can evaluate how they can contribute to the completeness of TorchVision.

- def   _get_inverse_affine_matrix(
- def _get_perspective_coeffs(startpoints:   List[List[int]], endpoints: List[List[int]]) -> List[float]:
- def _interpolation_modes_from_int(i:   int) -> InterpolationMode:
- def _is_numpy(img: Any) -> bool:
- def _is_numpy_image(img: Any) ->   bool:
- def adjust_brightness(img: Tensor,   brightness_factor: float) -> Tensor:
- def adjust_contrast(img: Tensor,   contrast_factor: float) -> Tensor:
- def adjust_gamma(img: Tensor, gamma:   float, gain: float = 1) -> Tensor:
- def adjust_hue(img: Tensor, hue_factor:   float) -> Tensor:
- def adjust_saturation(img: Tensor,   saturation_factor: float) -> Tensor:
- def adjust_sharpness(img: Tensor,   sharpness_factor: float) -> Tensor:
- def affine(
- def autocontrast(img: Tensor) ->   Tensor:
- def center_crop(img: Tensor,   output_size: List[int]) -> Tensor:
- def convert_image_dtype(image:   torch.Tensor, dtype: torch.dtype = torch.float) -> torch.Tensor:
- def crop(img: Tensor, top: int, left:   int, height: int, width: int) -> Tensor:
- def equalize(img: Tensor) -> Tensor:
- def erase(img: Tensor, i: int, j: int,   h: int, w: int, v: Tensor, inplace: bool = False) -> Tensor:
- def five_crop(img: Tensor, size:   List[int]) -> Tuple[Tensor, Tensor, Tensor, Tensor, Tensor]:
- def gaussian_blur(img: Tensor,   kernel_size: List[int], sigma: Optional[List[float]] = None) -> Tensor:
- def get_image_num_channels(img: Tensor)   -> int:
- def get_image_size(img: Tensor) ->   List[int]:
- def hflip(img: Tensor) -> Tensor:
- def invert(img: Tensor) -> Tensor:
- def normalize(tensor: Tensor, mean:   List[float], std: List[float], inplace: bool = False) -> Tensor:
- def pad(img: Tensor, padding: List[int],   fill: int = 0, padding_mode: str = "constant") -> Tensor:
- def perspective(
- def pil_to_tensor(pic):
- def posterize(img: Tensor, bits: int)   -> Tensor:
- def resize(
- def resized_crop(
- def rgb_to_grayscale(img: Tensor,   num_output_channels: int = 1) -> Tensor:
- def rotate(
- def scale(*args, **kwargs):
- def solarize(img: Tensor, threshold:   float) -> Tensor:
- def ten_crop(img: Tensor, size:   List[int], vertical_flip: bool = False) -> List[Tensor]:
- def to_grayscale(img,   num_output_channels=1):
- def to_pil_image(pic, mode=None):
- def to_tensor(pic):
- def vflip(img: Tensor) -> Tensor:


In the same argument, there is this folder with reference to MINST and any (yet to implement) vision relevant datasets 

TorchSharp/src/TorchSharp/TorchVision/DataSets

**Comment by NiklasGustafsson** [comment]
@ekagra-ranjan -- the advantage of having a separate instance-based implementation of Normalize is that it can keep the means and stddev normalization buffers around, in the type and device that's intended, so that you don't have to call .to() over and over. Most transforms don't have buffers.

**Comment by ekagra-ranjan** [comment]
Got it. And what about transforms who dont a buffer around them, e.g., [Erase](https://github.com/dotnet/TorchSharp/blob/7a7c54176941d51bbab7e7469e84006019a5f1ad/src/TorchSharp/TorchVision/Erase.cs#L23)? Should it be using its [functional code](https://github.com/dotnet/TorchSharp/blob/7a7c54176941d51bbab7e7469e84006019a5f1ad/src/TorchSharp/TorchVision/Functional.cs#L380)?

**Comment by ekagra-ranjan** [comment]
Cool, I will remove the duplicate implementation in the forward() for such transforms and call its functional API.

**Comment by ekagra-ranjan** [comment]
Closed via #391
