### ISSUE TITLE
Missing torch.load

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/TorchSharp#403]
Similar with the discussion of the missing [torch.save](https://github.com/dotnet/TorchSharp/issues/372)

pytorch **torch.load** refers to [torch\serialization.py](https://github.com/pytorch/pytorch/blob/master/torch/serialization.py)

which provide parameter instructions for loading

[Example](https://github.com/pytorch/pytorch/blob/60fe854f9f6e911dd0d63fc1c9fa15305614e3a0/torch/serialization.py#L636)
```python
        >>> torch.load('tensors.pt')
        # Load all tensors onto the CPU
        >>> torch.load('tensors.pt', map_location=torch.device('cpu'))
        # Load all tensors onto the CPU, using a function
        >>> torch.load('tensors.pt', map_location=lambda storage, loc: storage)
        # Load all tensors onto GPU 1
        >>> torch.load('tensors.pt', map_location=lambda storage, loc: storage.cuda(1))
        # Map tensors from GPU 1 to GPU 0
        >>> torch.load('tensors.pt', map_location={'cuda:1':'cuda:0'})
        # Load tensor from io.BytesIO object
        >>> with open('tensor.pt', 'rb') as f:
        ...     buffer = io.BytesIO(f.read())
        >>> torch.load(buffer)
        # Load a module with 'ascii' encoding for unpickling
        >>> torch.load('module.pt', encoding='ascii')
```

Currently LibTorchSharp implements [one ](https://github.com/dotnet/TorchSharp/blob/08086218fb21a6f623054e2b30306da07228d11a/src/Native/LibTorchSharp/THSModule.cpp#L170)of the possible loading options listed above

Since pickling is an overkill as [discussed for .NET](https://github.com/dotnet/TorchSharp/blob/main/docfx/articles/saveload.md)

As I am still learning ...  is there a need to provide more loading options provided through torch.load instead of Module.load in TorchSharp?

I am raising this issue, as I fail to load a saved State_Dict created through[ exportsd.py](https://github.com/dotnet/TorchSharp/blob/main/src/Python/exportsd.py) back to TorchSharp using Module.Load

I did not get any error message, as the process crashes. 

suggestions: is there a need for error messages when loading fail to assist in a more reliable loading state_dict.

**Comment by GeorgeS2019** [comment]
Create a unit test to test the feasibility

```cs
[Fact]
public void LoadModelTest()
{
    string fileName = "gpt2-pytorch_model.ts";
    if (File.Exists(fileName)) {
        var stateDict = Module.Load(fileName);
        Assert.NotNull(stateDict);
    }
}
```

**Comment by NiklasGustafsson** [comment]
Yes, it is exactly what the intent for Module.load is -- to deserialize parameters. However, the model definition needs to exactly match the origin, since (unlike Python) .NET cannot create a class definition and then instantiate it. Like I mentioned, Module.load() loads weights, not modules.

**Comment by GeorgeS2019** [comment]
[Ref](https://github.com/lutzroeder/netron/issues/338#issuecomment-538224364)
>**PyTorch serialization formats** are a moving target and saving to ONNX is more reliable.

That discussion was back in 2019. I wonder how moving target is PyTorch format 2021 and will that affect future TorchSharp import PyTorch model?

**Comment by NiklasGustafsson** [comment]
@GeorgeS2019 -

In order to train with TorchSharp, you will always need a representation of the model in code. 

A longer-term solution than the one we have in place now (loading weights into a model instance) will be to generate the TorchSharp code from an ONNX graph, so that you have full fidelity, then load the weights into that.

Implementing ONNX import will take some time, so if you need to transfer from PyTorch to TorchSharp before then, the existing mechanism is your only option.

If the article at: https://github.com/dotnet/TorchSharp/blob/main/docfx/articles/saveload.md doesn't describe the mechanics of the current approach in sufficient detail, please file a documentation issue with feedback on where the article is lacking in detail or clarity.

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson  I see this eventually related to [ML.NET TorchSharp integration](https://github.com/dotnet/TorchSharp/discussions/335#discussioncomment-1461360)

It is not a simple decision. Let us hope there will be active participation to such discussion from TorchSharp/ML.NET communities

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson I took an existing diagram from  a Microsoft documentation on tensorflow integration to ML.NET and simply clone it and add in the PyTorch part.

**Comment by GeorgeS2019** [comment]
[Update](https://github.com/dotnet/TorchSharp/issues/146#issuecomment-960358658)

**Comment by GeorgeS2019** [comment]
I close this issue now after[ an unit test provided](https://github.com/dotnet/TorchSharp/issues/510#issuecomment-1045992832) to show how to save dict_states in pytorch and load them in torchsharp.
