### ISSUE TITLE
libtorch-cuda-11.3-linux-x64 not exist on nuget.org

### ISSUE THREAD

**Issue by dayo05** [dotnet/TorchSharp#427]
There are only libtorch-cuda-11.1-linux-x64

**Comment by NiklasGustafsson** [comment]
The move to CUDA 11.3 (and Torch 1.10) is underway and not complete at this point.

**Comment by NiklasGustafsson** [comment]
I'm going to close this -- support for  Torch 1.10 and CUDA 11.3 is imminent.
