### ISSUE TITLE
Feasibility of creating TorchSharp.NativeAssets.WebAssembly?

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/TorchSharp#429]
This is related to the issue raised [here](https://github.com/dotnet/TorchSharpExamples/issues/5)

[TorchSharp.NativeAssets.WebAssembly](https://github.com/dotnet/AspNetCore.Docs/issues/23661#issuecomment-960373245) is something post TorchSharp 1.0 and something a remote feasibility evaluation when the Blazor WebAssembly native library interop technology is much more mature.

**Comment by NiklasGustafsson** [comment]
@GeorgeS2019 -- I would suggest closing this for now. For TorchSharp to properly work with WebAssembly, there would have to be a WA backend libtorch implementation, which goes beyond what this project is scoped to accomplish.
