### ISSUE TITLE
Join Virtual ML.NET Hackathon 2021 with a TorchSharp project!!

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/TorchSharp#441]
November 12-19, 2021

https://github.com/virtualmlnet/hackathon-2021

Join the hackathon with a [TorchSharp project](https://github.com/virtualmlnet/hackathon-2021/blob/main/project-ideas.md)

**Comment by NiklasGustafsson** [comment]
@GeorgeS2019 -- this is a plug for an event. However relevant and interesting it may be, it's not an issue. 

Please move it to 'Discussions.'

**Comment by GeorgeS2019** [comment]
Done! => https://github.com/dotnet/TorchSharp/discussions/442
