### ISSUE TITLE
Changine naming to C# style

### ISSUE THREAD

**Issue by dayo05** [dotnet/TorchSharp#448]
I know TorchSharp's naming style is from pytorch. But torchsharp will use with other C# codes, Which follows normal C# naming style(For example, Console.WriteLine does) 

So, It can cause confused for users. 

And also, Two kinds of nameing style is coexist. 

For example, When creating dataloader(like TorchSharp.Examples.MNISTReader) will use IEnumerable which uses C# naming Style.

C# and Python is different, I think it is not necessary to use pytorch naming, And also I think it is very bad choice.

Suggestion: Changing naming of method, classes like C# core API(namespace System)

**Comment by dayo05** [comment]
For example, Sequential.forward => Sequential.Forward

**Comment by GeorgeS2019** [comment]
@dayo05 we had a long and long discussion on this. There are many reasons we ended up proceeding with this direction.

**Comment by dsyme** [comment]
This issue is a diuplicate, eg see https://github.com/dotnet/TorchSharp/issues/225#issuecomment-871506959, and a few other issues/comments
