### ISSUE TITLE
`NotSupportedException` about missing `libtorch-cpu` reference when it is present

### ISSUE THREAD

**Issue by lostmsu** [dotnet/TorchSharp#449]
- TorchSharp: 0.95.3
- OS: Windows 10

**NOTE**: CUDA and NVidia GPU are present in the system, but the intent is not to use them for test code.

I have a test project targeting `net6.0` that uses `Xunit`. The test project references `libtorch-cpu`:

```xml
<PackageReference Include="libtorch-cpu" Version="1.10.0.1" />
```

However, upon calling `torch.random.manual_seed(119);` I get 

>     System.NotSupportedException : This application uses TorchSharp but doesn't contain reference to either libtorch-cuda-11.3-win-x64 or libtorch-cpu, 1.10.0.1. Consider either referencing one of these packages or call System.Runtime.InteropServices.NativeLibrary.Load(path-to-LibTorchSharp.dll) explicitly for a Python install or a download of libtorch.so/torch.dll. See https://github.com/dotnet/TorchSharp/issues/169.". Trace from LoadNativeBackend:
> 
> TorchSharp: LoadNativeBackend: Initialising native backend, useCudaBackend = True
> 
> Step 1 - First try regular load of native libtorch binaries.
> 
>     Try loading Windows cuda native components
>     Trying to load native component cudnn_adv_infer64_8 relative to C:\Users\lost\Projects\AI\Torch.Modules\Siren\test\bin\Debug\net6.0\TorchSharp.dll
>     Trying to load native component cudnn_adv_train64_8 relative to C:\Users\lost\Projects\AI\Torch.Modules\Siren\test\bin\Debug\net6.0\TorchSharp.dll
>     Trying to load native component cudnn_cnn_infer64_8 relative to C:\Users\lost\Projects\AI\Torch.Modules\Siren\test\bin\Debug\net6.0\TorchSharp.dll
>     Trying to load native component cudnn_cnn_train64_8 relative to C:\Users\lost\Projects\AI\Torch.Modules\Siren\test\bin\Debug\net6.0\TorchSharp.dll
>     Trying to load native component cudnn_ops_infer64_8 relative to C:\Users\lost\Projects\AI\Torch.Modules\Siren\test\bin\Debug\net6.0\TorchSharp.dll
>     Trying to load native component cudnn_ops_train64_8 relative to C:\Users\lost\Projects\AI\Torch.Modules\Siren\test\bin\Debug\net6.0\TorchSharp.dll
>     Trying to load native component nvrtc-builtins64_113 relative to C:\Users\lost\Projects\AI\Torch.Modules\Siren\test\bin\Debug\net6.0\TorchSharp.dll
>     Failed to load native component nvrtc-builtins64_113 relative to C:\Users\lost\Projects\AI\Torch.Modules\Siren\test\bin\Debug\net6.0\TorchSharp.dll
>     Trying to load native component caffe2_nvrtc relative to C:\Users\lost\Projects\AI\Torch.Modules\Siren\test\bin\Debug\net6.0\TorchSharp.dll
>     Trying to load native component nvrtc64_112_0 relative to C:\Users\lost\Projects\AI\Torch.Modules\Siren\test\bin\Debug\net6.0\TorchSharp.dll
>     Trying to load native component torch_cuda relative to C:\Users\lost\Projects\AI\Torch.Modules\Siren\test\bin\Debug\net6.0\TorchSharp.dll
>     Trying to load native component LibTorchSharp relative to C:\Users\lost\Projects\AI\Torch.Modules\Siren\test\bin\Debug\net6.0\TorchSharp.dll
>     Failed to load native component LibTorchSharp relative to C:\Users\lost\Projects\AI\Torch.Modules\Siren\test\bin\Debug\net6.0\TorchSharp.dll
>     Result from regular native load of LibTorchSharp is False
> 
> Step 3 - Alternative load from consolidated directory of native binaries from nuget packages
> 
>     torchsharpLoc = C:\Users\lost\Projects\AI\Torch.Modules\Siren\test\bin\Debug\net6.0
>     packagesDir = C:\Users\lost\Projects\AI\Torch.Modules\Siren
>     torchsharpHome = C:\Users\lost\Projects\AI\Torch.Modules\Siren\test\bin
>     Giving up, TorchSharp.dll does not appear to have been loaded from package directories
> 
> 
>   Stack Trace: 
> torch.LoadNativeBackend(Boolean useCudaBackend, StringBuilder& trace)
> torch.TryInitializeDeviceType(DeviceType deviceType)
> random.manual_seed(Int64 seed)
> SirenTests.CanLearn() line 15

### Workaround

Adding a `ModuleInitializer` with `torch.TryInitializeDeviceType(DeviceType.CPU);` appears to solve the issue.

**Comment by dsyme** [comment]
Yes looks like this or similar are falsely doing cuda init 

https://github.com/dotnet/TorchSharp/blob/68e13cb081fd86ffb76998dd9b801ddc92595565/src/TorchSharp/Torch.cs#L295

I'm not quite sure what the spec should be though

**Comment by NiklasGustafsson** [comment]
@lostmsu, I will take a look at this. 

Just to make sure I understand --  It is failing to initialize CUDA, but that is your expectation given the fact that you are depending on libtorch-cpu, not libtorch-cuda.

The expected behavior is that there should not be an exception coming out of the 'TryInitializeDeviceType()' call.

**Comment by lostmsu** [comment]
@NiklasGustafsson re: `TryInitializeDeviceType`, I'd expect a method with such name to simply return `false` when CUDA library is missing. Or maybe even an enum of `OK`, `LibTorchCudaMissing`, `CudaNotInstalled`, e.t.c. Otherwise just rename it to `InitializeDeviceType` and throw an exception.

But from my perspective the issue is not with `TryInitializeDeviceType` - I am not even calling it directly, but with `torch.random.manual_seed`.

**Comment by NiklasGustafsson** [comment]
@lostmsu: right. I was projecting an API-level expectation to the underlying at-fault function.

**Comment by NiklasGustafsson** [comment]
I put together a simple test:

```C#
[Fact]
public void Test1()
{
    torch.random.manual_seed(42);
}
```

I have CUDA on my machine, but using the CPU backend, with the following dependency:

```XML
    <PackageReference Include="TorchSharp-cpu" Version="0.95.3" />
```

The call to manual_seed() does not fail. Are there any further details I'm missing?

**Comment by NiklasGustafsson** [comment]
I also tried it by separately including TorchSharp and libtorch:

```XML
    <PackageReference Include="libtorch-cpu" Version="1.10.0.1" />
    <PackageReference Include="TorchSharp" Version="0.95.3" />
```

Same outcome.

**Comment by lostmsu** [comment]
[missing-ref.zip](https://github.com/dotnet/TorchSharp/files/7557571/missing-ref.zip)
Try this one

**Comment by NiklasGustafsson** [comment]
Yes, I'm on Windows. I'll try your ZIP.

**Comment by NiklasGustafsson** [comment]
Your solution also works on my machine, so I'm at a loss. 

Any chance that running a 'Clean Solution' or removing the bin/obj folders might clean out some old things?

**Comment by NiklasGustafsson** [comment]
Or having both projects depend on TorchSharp-cpu instead of explicitly including the backend.

**Comment by lostmsu** [comment]
@NiklasGustafsson hm, I removed all bin and obj directories when I packed that zip, and `dotnet test` fails in that folder with the exact error in the head post.

Feel free to close the bug for now. I will investigate with a debug build if I have time later.
