### ISSUE TITLE
how to change the libtorch dylib location when manual package?

### ISSUE THREAD

**Issue by zhen8838** [dotnet/TorchSharp#455]
Hi !
  I'm use dotnet 6.0 with M1 Mac. I modify the torchsharp package command for arm64. Finally I install the local libtorch into my project, but the libtorch will auto install to `runtimes\osx-x64\native`, so I need manual move it to top level folder.
![截屏2021-11-20 14 46 46](https://user-images.githubusercontent.com/26156999/142717467-fb090967-f0a3-426d-a4c0-1e793b705757.png)
 
Can you teach me how to change the libtorch install location when `dotnet build`?

**Comment by GeorgeS2019** [comment]
@zhen8838  welcome to TorchSharp community.

For mac => https://github.com/dotnet/TorchSharp/blob/main/DEVGUIDE.md#mac

Even with Windows, the best way to setup is through command line. 

Keep posting your questions and we will find way to get you running and developing with Torchsharp. 

We will learn from your experience how best to assist Mac users

**Comment by GeorgeS2019** [comment]
Do follow the instructions. Do not need to change the downloaded directory of libTorch. The scripts provided will look for them and put them finally in the right place.

**Comment by GeorgeS2019** [comment]
@zhen8838  can u close this issue if no more problem

**Comment by zhen8838** [comment]
@GeorgeS2019 Thanks for your answer! I solve it!
