### ISSUE TITLE
How to set Conv2d kernel_size=(2, 300)

### ISSUE THREAD

**Issue by aiqinxuancai** [dotnet/TorchSharp#468]
python model：
```
<bound method Module.parameters of Model(
  (embedding): Embedding(4762, 300)
  (convs): ModuleList(
    (0): Conv2d(1, 256, kernel_size=(2, 300), stride=(1, 1))
    (1): Conv2d(1, 256, kernel_size=(3, 300), stride=(1, 1))
    (2): Conv2d(1, 256, kernel_size=(4, 300), stride=(1, 1))
  )
  (dropout): Dropout(p=0.5, inplace=False)
  (fc): Linear(in_features=768, out_features=12, bias=True)
)>
```
Conv2d has only long type parameters in torchsharp.
![image](https://user-images.githubusercontent.com/4475018/144003767-df4f0a8e-116e-4013-ab1f-4482168937b3.png)

**Comment by GeorgeS2019** [comment]
@aiqinxuancai  Torchsharp has very extensive Unit Tests.  Often, going through the unit tests for the method you are interested, suggests the solution you look for. :-)

**Comment by NiklasGustafsson** [comment]
The module-based convolution is missing support for non-symmetrical kernels. The torch.nn.functional API does support any kind of kernel size, but you clearly want to use modules here.

I'll add this to the backlog.

**Comment by NiklasGustafsson** [comment]
Should be in 0.95.4 -- release at the end of this week.
