### ISSUE TITLE
Load model from pyTorch issue

### ISSUE THREAD

**Issue by anytoany** [dotnet/TorchSharp#489]
I try load trained nn in pyTorch(in pth file format) to TorchSharp but give some errors.

1. **from static method**
`
Module module = Module.Load("C:\\ir50-model.pth");
module.forward(tensor_image);
`
throw System.NotImplementedException: 'forward(t)'

2. **useStrict: false**
```
var myModel = new MyModel("test");
myModel.load("C:\\ir50-model.pth", false); ;
myModel.forward(tensor_image);

public class MyModel : Module
{
        public MyModel() : base("test") {}      

        public MyModel(string name) : base(name) {}     

        public override Tensor forward(Tensor input)
        {
            return this.forward(input);
        }
}
```

throw System.FormatException: 'Too many bytes in what should have been a 7-bit encoded integer.'

Does it exist worked way to load pth model from pyTorch to TorchSharp ?

**Comment by GeorgeS2019** [comment]
@anytoany have a look at this [diagram](https://github.com/dotnet/TorchSharp/issues/403#issuecomment-940467174)

Most importantly the discussions that follow.   Short answer, Torchsharp can only load the a model saved in Torchsharp proprietary format. Torchsharp can not load a model (e.g. pth) saved by PyTorch.

**Comment by nhirschey** [comment]
You can’t load a pickled PyTorch model. 

See the detailed article on this here https://github.com/dotnet/TorchSharp/blob/main/docfx/articles/saveload.md

**Comment by anytoany** [comment]
> You can’t load a pickled PyTorch model directly.
> 
> See the detailed article on this here https://github.com/dotnet/TorchSharp/blob/main/docfx/articles/saveload.md
> 
> Use the script at the bottom of the article as a work around for loading your model.

I got "System.FormatException: 'Too many bytes in what should have been a 7-bit encoded integer.'" exception when i try load file saved by this tutorial(with exportsd.py)

**Comment by NiklasGustafsson** [comment]
Sorry, I've been out on vacation for a month. First day back...

What does the Python model that you are exporting look like? It has to have the same components as the model you're loading the weights into. 

From the code you included, it looks like:

1. There are no submodules in your model. Is this intentional, or did you simplify it for the purpose of brevity in the issue report?
2. Your forward() function recurses infinitely.

**Comment by anytoany** [comment]
1. Yes my model not have submodules, i thinhk model structure can load from model file, i`m right?
2. Yes, i not know how implement forward without determinate model structure in code

**Comment by NiklasGustafsson** [comment]
@anytoany -- the .NET model class needs to have the same structure as the Python origin. Note that the load/save only loads weights, the model structure (including the forward()) needs to be implemented in code.

**Comment by NiklasGustafsson** [comment]
@anytoany -- is this still a problem? If not, please close it. If yes, then could you please provide a reference to the original Python model code for reference?

**Comment by GeorgeS2019** [comment]
@anytoany  

Please see[ a work around](https://github.com/dotnet/TorchSharp/issues/510#issuecomment-1045992832) using the recommended save_dict codes
