### ISSUE TITLE
NU1108 when downloading from nuget

### ISSUE THREAD

**Issue by MagicBOTAlex** [dotnet/TorchSharp#507]
1. Open nuget for solution
2. goto browse
3. search for torch sharp
4. Select project
5. press install
6. agree to the terms
7. error and rollback

Info:
Windows 10
cpu: ryzen 7 5800H
gpu: rtx 3080
ram: 16GB 3200mhz

Edit: Forgot to say that i'm using C# on .net core and the target framework is .NET 5.0 (Console application)

![image](https://user-images.githubusercontent.com/44818698/152497312-e0299712-8759-48b4-855a-1f9f1ed80671.png)
There's not much to say.

**Comment by MagicBOTAlex** [comment]
Forgot to say that i'm using C# on .net core and the target framework is .NET 5.0

**Comment by NiklasGustafsson** [comment]
@MagicBOTAlex -- do you have an earlier version of TorchSharp installed that you are replacing? It may be worth trying to uninstall it from everywhere in the solution and then install it.

If that doesn't work, it's worth looking inside the .nuget folder under your user folder and remove all the TorchSharp folders, then try to install again. It's a crude "refresh," but it might help.

**Comment by MagicBOTAlex** [comment]
Sorry for the late response. But turns out that you're correct. Thank you!!!
Sorry that I just couldn't figure the problem out, myself.
