### ISSUE TITLE
AdamW bug on v0.96.0

### ISSUE THREAD

**Issue by QingtaoLi1** [dotnet/TorchSharp#516]
When I update TorchSharp from 0.95.4 to 0.96.0, some exception occurs on `torch.optim.AdamW()`:

> System.Runtime.InteropServices.SEHException: 'External component has thrown an exception.'

The only change I commit is lower-casing `train()` and `eval()`. Notice that the first argument of `torch.optim.AdamW()` (and other optimizers) changes from `IEnumerable<torch.Tensor>` to `IEnumerable<TorchSharp.Modules.Parameter>`, so I guess the bug is related to library changes to solve #501.

**Comment by NiklasGustafsson** [comment]
@QingtaoLi1 -- the renaming and the type change should not affect anything. Down in native code, neither matters.

Could you provide the whole stack trace? The one line you have is not enough to give me an idea of what is going on.

**Comment by NiklasGustafsson** [comment]
Also, in the next release, AdamW will be implemented in managed code, so things are likely to change.

**Comment by QingtaoLi1** [comment]
> @QingtaoLi1 -- the renaming and the type change should not affect anything. Down in native code, neither matters.
> 
> Could you provide the whole stack trace? The one line you have is not enough to give me an idea of what is going on.

Stack trace here. It points to the constructor of Adam and nothing else. The only error message is "external component..." I showed above.
![image](https://user-images.githubusercontent.com/89620019/153972842-06ff4afb-f0e1-4abd-8e42-77c5583dbd18.png)
![image](https://user-images.githubusercontent.com/89620019/153972923-ab67342a-5695-4571-9dc6-3e55b5d3fd8a.png)

**Comment by NiklasGustafsson** [comment]
Okay, thanks!

**Comment by QingtaoLi1** [comment]
@NiklasGustafsson Oh I didn't notice I was captioning the error of `Adam`. But the exception is the same for both optimizers.

**Comment by NiklasGustafsson** [comment]
Let's see how this changes with the new implementation in 0.96.1

**Comment by QingtaoLi1** [comment]
> Let's see how this changes with the new implementation in 0.96.1

Great! I tried `SGD` just now and it also fails.

**Comment by NiklasGustafsson** [comment]
Hmmm. There's something fundamentally wrong. Is there any possibility of any mixup of DLLs or packages?

**Comment by QingtaoLi1** [comment]
I'm not sure. Just try deleting `.nuget\\packages\\torchsharp\\` and re-installing it, but nothing changes.

**Comment by NiklasGustafsson** [comment]
OK

**Comment by QingtaoLi1** [comment]
Sure. Trying, wait a moment

**Comment by NiklasGustafsson** [comment]
If you have a chance to narrow it down to a smaller example, running with random data, etc., that would be great.
