### ISSUE TITLE
Multiprocessing dataloader support

### ISSUE THREAD

**Issue by peteryang1** [dotnet/TorchSharp#519]
Hello,

In Pytorch, a 'torch.utils.data.DataLoader' is often used to serve the data preprocessing in multiprocessing mode because data processing is very time costy and Python cannot start multithread in main thread. 
However, TorchSharp is based on C# which supports multi thread while Python should use multi process to make the best use of the CPU.

Is there a plan of implementing a multi thread DataLoader in TorchSharp or the users are intended to write their own multi-thread dataloader to support a faster and parallel data preprocess?

Thanks!

**Comment by NiklasGustafsson** [comment]
@peteryang1:

Yes and no. The DataLoader class that @dayo05 recently implemented and introduced, implements IEnumerable, and is therefore sequential in its API. It defers to 'Dataset' to implement the retrieval of the data. Dataset is an abstract class, and the concrete implementations could very well be implemented using concurrency.

Adding @oluwandabira, who has been thinking about this stuff related to TorchVision.

**Comment by peteryang1** [comment]
Thanks @NiklasGustafsson for the reply.

As we can find from Pytorch API Doc, the 'dataloader' handles the multi process procedures while the 'dataset' class implemented by the user only considers one sample strategy.
![image](https://user-images.githubusercontent.com/25981102/154891355-83fa6812-d96f-4f07-93f5-8dc9888ebacc.png)

It seems the MNIST sample codes provided only supports sequential data process strategy which makes training slow down when data augmentation is very time costy.

**Comment by NiklasGustafsson** [comment]
Adding @dayo05 and @oluwandabira to the discussion. This is a very important feature, so it would be great to get input from all who have been thinking about data load.

**Comment by oluwandabira** [comment]
Looking through the current `TorchSharp.Data`, it appears that everything there is a wrapper around `LibTorch` methods, which makes sense as TorchSharp is to be just a wrapper but if any async/parallel Loaders are to be implemented then we would have to add pure C# implementations of those classes (and maybe alter Dataset to have aync methods?).

That is my current understanding of the situation and I wouldn't mind the pure C# code if it allows faster loading times.

**Comment by NiklasGustafsson** [comment]
@peteryang1:

Maybe I'm misunderstanding what the multi-process support is about, but looking at the PyTorch documentation for Dataset, it seems like it's about splitting the data set among multiple processes. I thought you were asking about concurrency in loading the data.
