### ISSUE TITLE
Can't set `Tensor` slice using indexing

### ISSUE THREAD

**Issue by lostmsu** [dotnet/TorchSharp#521]
This fails:
```csharp
using var t = tensor(new[] { 1, 2, 3, 4 }, rows: 2, columns: 2);
t[0] = tensor(new[] { 5, 6 }); // <- exception
Assert.Equal(5, t[0, 0].ToInt32());
```

Error happens here:
```csharp
THSTensor_set1(Handle, i, value.ToScalar().Handle);
```

Because the value is not a scalar.

## Workaround
```csharp
t[0].copy_(tensor(new[] { 5, 6 }))`
```

**Comment by lostmsu** [comment]
Was there any reason why this `ToScalar` call had to be present? I just tried on my machine, and adding a simple
```cpp
void THSTensor_set1t(const Tensor tensor, int64_t index, const Tensor value)
```

And replacing the call above with
```csharp
THSTensor_set1t(Handle, i, value.Handle);
```
seems to be working fine.

**Comment by NiklasGustafsson** [comment]
@lostmsu -- yeah, I can't figure out why it would want the source to be a Scalar there. There's a reason to special-case for the index being an integer, but not for the value to be scalar, I think.

Put it in a PR, and we can get it into 0.96.1

**Comment by NiklasGustafsson** [comment]
In the meantime, you should be able to rely on the TensorIndex versions of the indexer.

**Comment by NiklasGustafsson** [comment]
BTW, I usually add at least one regression test to the 'TestTorchTensorBugs.cs' file when I have a small enough repro.

**Comment by lostmsu** [comment]
@NiklasGustafsson can I replace the existing definitions? Should I even be worried about having incompatible C++ signatures between 0.96.0 and 0.96.1?

**Comment by NiklasGustafsson** [comment]
Until we get to 1.0, we are unapologetically making breaking changes and there's no guarantee of binary compatibility. 

Breaking changes need to be highlighted in the RELEASENOTES, but otherwise, let's just get things in order. The existing code is clearly incorrect.

**Comment by NiklasGustafsson** [comment]
The parameter groups support will also be a breaking change because optimizers won't have a scalar 'LearningRate' property (those go with the parameter groups).
