### ISSUE TITLE
LSTM's forward function not work with null hidden and cell state

### ISSUE THREAD

**Issue by Leo-LiHao** [dotnet/TorchSharp#525]
Hi, I'm implementing an example of using LSTM, however, I found that if I pass null `h0_c0` to 'LSTM.forward' there will raise an exception like:

> Unhandled exception. System.Runtime.InteropServices.ExternalException (0x80004005): Expected hidden[0] size 1 128 512, got [0]

**Comment by NiklasGustafsson** [comment]
@Leo-LiHao -- can you paste the code of the model (not the whole training code) here?

**Comment by NiklasGustafsson** [comment]
> @Leo-LiHao -- can you paste the code of the model (not the whole training code) here?

No need -- this was easily reproduced: just go with the defaults... :-)
