### ISSUE TITLE
Image flipping transforms do not work as expected.

### ISSUE THREAD

**Issue by oluwandabira** [dotnet/TorchSharp#528]
![1](https://user-images.githubusercontent.com/24304808/154812535-261f7397-a9a7-4aba-915c-20f791ee7296.jpg)
I'm not sure if it's an issue with the above image in particular but applying any of the flipping transforms to it (`torchvision.transforms.RandomVerticalFlip`, `torchvision.transforms.HorizontalFlip`, e.t.c) does not give the expected output.

Applying vertical flip gives:
![image_transformed_2](https://user-images.githubusercontent.com/24304808/154812615-5fe4e716-1fcb-4275-85c0-02bf932a21d5.png)

and horizontal gives:
![image_transformed_1](https://user-images.githubusercontent.com/24304808/154812628-d2ff42e0-b180-4710-8b7f-dd392a32976e.png)

Applying another transform `Invert` worked fine:

![image_inverted](https://user-images.githubusercontent.com/24304808/154812657-a89f2d8b-baaa-4ec9-bb34-f1cd9562db7d.png)

and performing the operations with pytorch works as expected:

![flipped](https://user-images.githubusercontent.com/24304808/154812696-1464af89-b5c6-4cbd-bd6b-67701730fd53.png)
![flipped2](https://user-images.githubusercontent.com/24304808/154812698-e37a1415-dbea-4e75-b8d0-e29cc53632df.png)

**Comment by oluwandabira** [comment]
Another example of wrong vertical flip:
![c](https://user-images.githubusercontent.com/24304808/154813102-41a5c94a-bac1-4f75-a3d6-556b63d4b3d3.jpg)

![image_transformed_c](https://user-images.githubusercontent.com/24304808/154813173-004829b2-9303-4d1e-b33f-81faab67f56c.jpg)

**Comment by GeorgeS2019** [comment]
Do u know how Pytorch torchvision unit test these image transformation ?

**Comment by oluwandabira** [comment]
I should note that I am using the custom `torchvision.io` interface I'm trying to implement to read/write so that may be the actual issue but as some other transforms work, I'm not so sure it's my code causing the issue.

**Comment by GeorgeS2019** [comment]
It will help if you could check how the ImageSharp do unit tests on image transformation so it is possible to debug where the problem is.

**Comment by NiklasGustafsson** [comment]
@oluwandabira, I doubt that the issue is in your loading code, since other transformations work.

Let me ask -- does the tensor have a single image, or is there a batch of them? If the former, can you try adding a 1-sized batch dimension?

**Comment by NiklasGustafsson** [comment]
These operations simply call Tensor.flip, but it assumes there's a batch dimension.

**Comment by NiklasGustafsson** [comment]
@oluwandabira  -- this is very odd. When I downloaded your image and tried it, I first saw the same results, but it turned out that I was saving it at the wrong size. When I changed the code to save it 900x816 HxW, I get pictures that look like what I would expect:

![output-0](https://user-images.githubusercontent.com/1791495/155195639-ac26b4b0-1ca6-4821-9739-2f18bda21505.png)
 
![output-0](https://user-images.githubusercontent.com/1791495/155195819-4ff437b2-c768-4e38-b63f-9b16180d8caf.png)

This was done by editing the 'ImageTransforms.cs' file in the C# Examples project in TorchSharp (not TorchSharpExamples).

**Comment by NiklasGustafsson** [comment]
It's worth mentioning that my code had a 1-sized batch dimension.

**Comment by NiklasGustafsson** [comment]
Beautiful slug, by the way! What species is that?

**Comment by oluwandabira** [comment]
The slug is a [Limax maximus](https://en.wikipedia.org/wiki/Limax_maximus). Image is from the wiki.

I've added a batch dimension and it came up with the same results.  Example code I used is the [IOReadWrite example](https://github.com/oluwandabira/TorchSharp/blob/vision-io/src/Examples/IOReadWrite.cs) I added to my branch.

**Comment by NiklasGustafsson** [comment]
Okay, I'll take a look at it.

**Comment by NiklasGustafsson** [comment]
It maybe the encode/decode, after all. When I add a SkiaSharp implementation of IImager to your sample, I get it to work, just like with the original example.

**Comment by NiklasGustafsson** [comment]
Here's something interesting: if I load the image with both IImager implementations, the loaded images are not the same:

```C#
var img1 = torchvision.io.read_image(filename, torchvision.io.ImageReadMode.RGB);
var img2 = torchvision.io.read_image(filename, torchvision.io.ImageReadMode.RGB, new SkiaImager());

var b1 = img1.data<byte>();
var b2 = img2.data<byte>();

for (int i = 0; i < b1.Count; i++) Debug.Assert(b1[i] == b2[i]);
```

Fails with i == 15 as the first non-equal byte.

**Comment by NiklasGustafsson** [comment]
@oluwandabira -- I figured it out. The FromTensor and ToTensor had the HxW mixed up. The correct versions seem to be:

```C#
Tensor ToTensor<TPixel>(byte[] bytes) where TPixel : unmanaged, IPixel<TPixel>
{
    var image = Image.Load<TPixel>(bytes);
    var channels = Unsafe.SizeOf<TPixel>();
    byte[] imageBytes = new byte[image.Width * image.Height * channels];
    image.CopyPixelDataTo(imageBytes);
    return tensor(imageBytes, new long[] { image.Height, image.Width, channels }).permute(2, 0, 1);
}

byte[] FromTensor<TPixel>(Tensor t, ImageFormat format) where TPixel : unmanaged, IPixel<TPixel>
{
    var shape = t.shape;
    var tt = t.reshape(new long[] { shape[0] * shape[1] * shape[2] });
    var image = Image.LoadPixelData<TPixel>(tt.bytes.ToArray(), (int)shape[1], (int)shape[0]);
    IImageEncoder encoder = format switch {
        ImageFormat.PNG => new PngEncoder(),
        ImageFormat.JPEG => new JpegEncoder(),
        _ => throw new ArgumentException("Cannot encode to Unknown format"),
    };
    var stream = new MemoryStream();
    encoder.Encode(image, stream);
    return stream.ToArray();
}
```

**Comment by oluwandabira** [comment]
@NiklasGustafsson Thanks, I've corrected the code.
