### ISSUE TITLE
Implement miscellaneous utility functions

### ISSUE THREAD

**Issue by NiklasGustafsson** [dotnet/TorchSharp#560]
See: https://pytorch.org/docs/stable/nn.html#utilities

**Comment by ingted** [comment]
How about functions here?
[https://pytorch.org/docs/stable/tensors.html](https://pytorch.org/docs/stable/tensors.html)

E.g., unfold?

**Comment by NiklasGustafsson** [comment]
@ingted -- most of those should already be implemented, but we may have missed one or two. Besides 'unfold', what others are you in need of?

**Comment by ingted** [comment]
Hi @NiklasGustafsson ,

I found the following would be nice to have:
1. unfold
2. unflatten
3. eig
4. unique
5. unique_consecutive

**Comment by ingted** [comment]
Got it!!! #571 is really amazing!!

**Comment by ingted** [comment]
Hi @NiklasGustafsson,

Is PyTorch new version feature like vmap in your plan to support in near future?
[vmap](https://pytorch.org/tutorials/prototype/vmap_recipe.html)

**Comment by GeorgeS2019** [comment]
Will the discussion [here](https://github.com/dotnet/TorchSharp/discussions/580) raises the need for creating **TorchSharp.Data.Utils** folder with utility functions related **torch.data.utils**
