### ISSUE TITLE
torch.Tensor.tolist

### ISSUE THREAD

**Issue by ingted** [dotnet/TorchSharp#564]
[torch.Tensor.tolist](https://pytorch.org/docs/stable/generated/torch.Tensor.tolist.html)

Excuse me, does TorchSharp support tolist operator?
If no, will it be supported in the future?

**Comment by NiklasGustafsson** [comment]
@ingted -- I'll add this to the backlog. It should be straight-forward to implement. No native support for it, but a C# implementation should be simple enough.

**Comment by NiklasGustafsson** [comment]
The return type of 'tolist()' will be "System.Object," since the Pytorch definition is very flexible on what is returned. The leaf elements will be Torch.Scalar rather than platform data types like 'int' and 'float'
