### ISSUE TITLE
Overloads for Named Tensors missing

### ISSUE THREAD

**Issue by MovGP0** [dotnet/TorchSharp#568]
There are currently missing overloads for [named tensors](https://pytorch.org/docs/stable/named_tensor.html) in all factory methods in the following factories: 

* `torch.empty`
* `torch.rand`
* `torch.randn`
* `torch.ones`
* `torch.tensor`
* `torch.zeros` 

There is also missing the `redefine_names` method: 

```csharp
var t = torch.tensor(new[] { 1.345, 2.564, 3.456 });
t.redefine_names(new [] { "channels" });
```

**Example**
```csharp
Tensor tensor<T>(IList<T> rawArray, long[] dimensions, ScalarType? dtype = null, Device device = null, bool requiresGrad = false, string[] names = null)
where T:INumber
{
    // ....
}
```

**Usage** 

```csharp
var t = torch.tensor(new[] { 1.345, 2.564, 3.456 }, names: new [] { "channels" });
```

**Comment by NiklasGustafsson** [comment]
Right -- named tensors aren't currently supported in TorchSharp. Good to know there's a demand for it.

**Comment by NiklasGustafsson** [comment]
Just an implementation note:

Taking a closer look at the API, I noted that there doesn't seem to be any native support for named dimensions in libtorch. 

Thus, this will have to be supported in the managed code APIs and may add some overhead.

**Comment by NiklasGustafsson** [comment]
>> There is also missing the redefine_names method:

`refine_names`, right?

**Comment by MovGP0** [comment]
> > > There is also missing the redefine_names method:
> 
> `refine_names`, right?

yes ;-) 

There is a full list of operators found here: [Named Tensors operator coverage](https://pytorch.org/docs/stable/name_inference.html)

**Comment by GeorgeS2019** [comment]
## WIP [NAMED TENSORS](https://pytorch.org/docs/stable/named_tensor.html?highlight=named%20tensors)
> [INTRODUCTION TO NAMED TENSORS IN PYTORCH](https://pytorch.org/tutorials/intermediate/named_tensor_tutorial.html)
### C[reating named tensors](https://pytorch.org/docs/stable/named_tensor.html#creating-named-tensors)
- [ ] [torch.empty()](https://pytorch.org/docs/stable/generated/torch.empty.html#torch.empty)

- [x] [torch.rand()](https://pytorch.org/docs/stable/generated/torch.rand.html#torch.rand)
   - [x] CreateRandomTensorWithNames()
- [ ] [torch.randn()](https://pytorch.org/docs/stable/generated/torch.randn.html#torch.randn)

- [x] [torch.ones()](https://pytorch.org/docs/stable/generated/torch.ones.html#torch.ones)
   - [x] CreateFloat32TensorOnesWithNames
- [x] [torch.tensor()](https://pytorch.org/docs/stable/generated/torch.tensor.html#torch.tensor)
   - [x] CreateFloat32TensorFullWithNames()
- [x] [torch.zeros()](https://pytorch.org/docs/stable/generated/torch.zeros.html#torch.zeros)
   - [x] CreateFloat32TensorZerosWithNames 

### [Named dimensions](https://pytorch.org/docs/stable/named_tensor.html#named-dimensions)

### [Name propagation semantics](https://pytorch.org/docs/stable/named_tensor.html#name-propagation-semantics)

### [Explicit alignment by names](https://pytorch.org/docs/stable/named_tensor.html#explicit-alignment-by-names)
- [x] [align_as()](https://pytorch.org/docs/stable/named_tensor.html#torch.Tensor.align_as)  
     - [x] TestAlignAs()
- [x] [align_to()](https://pytorch.org/docs/stable/named_tensor.html#torch.Tensor.align_to)
     - [x] TestAlignTo()
### [Manipulating dimensions](https://pytorch.org/docs/stable/named_tensor.html#manipulating-dimensions)
  - [x] [flatten()](https://pytorch.org/docs/stable/generated/torch.Tensor.flatten.html#torch.Tensor.flatten)
     - [x] TestFlattenNamed
### [Named tensor API reference](https://pytorch.org/docs/stable/named_tensor.html#named-tensor-api-reference)
- [ ] CLASS torch.Tensor
  - [x]  rename(*names, **rename_map)
     - [x] TestRenameTensor()
     - [x] TestRenameNamedTensor()
  - [x] refine_names(*names) 
      - [x] TestRefineNames()
