### ISSUE TITLE
Migrate to .NET 6 and use generic math interfaces

### ISSUE THREAD

**Issue by MovGP0** [dotnet/TorchSharp#569]
With .NET 6 there have been introduced new interfaces for generic mathematics. This could drastically decrease the number of current factories by generalizing them.

The drawback would be that older .NET Framework versions would not be supported. 

**Reference**
[Preview Features in .NET 6 – Generic Math](https://devblogs.microsoft.com/dotnet/preview-features-in-net-6-generic-math/)

**Comment by NiklasGustafsson** [comment]
Yes, indeed. That would be excellent.

Unfortunately, we're a long way away from not caring about FX versions before .NET 6.

In fact, we're going in the opposite direction: adding support for .NET FX 4.7.2 and forward. That's coming in the next release.

**Comment by MovGP0** [comment]
There can still be arguments made to switch from the .NET 5 SDK to .NET 6 SDK. Ie. .NET 5 is EOL by next month on [2022-05-08](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core), while .NET 6 is an LTS version. This would also enable the use of C# 10; including indexers (needs a shim like [IndexRange](https://www.nuget.org/packages/IndexRange/) for .NET 4.7.2). 

Not sure if the generic math features would be backward compatible 🤔
