### ISSUE TITLE
load_state_dict functionality

### ISSUE THREAD

**Issue by Ricochet73** [dotnet/TorchSharp#576]
We often need to copy model parameters from one model to another. For example in the PPO algorithm we typically do the following in python:

self.model_policy_old.load_state_dict(self.model_policy.state_dict())

This does not currently seem possible with TorchSharp as you do not implement the load_state_dict function. Alternative is to save model to a file and load it again. But this requires disc access during every model update operation. Do you have any other suggestions?

**Comment by NiklasGustafsson** [comment]
Excellent issue! 

This should be easy to fix, and I'll hold off on making another release until it's fixed. BTW, load/save take readers and writers, so you don't have to go to disk, but even so, we should have the direct state_dict loading.

**Comment by GeorgeS2019** [comment]
Related references

[What is a state_dict?](https://pytorch.org/tutorials/beginner/saving_loading_models.html#what-is-a-state-dict)

[Tutorial: what_is_state_dict.py](https://github.com/pytorch/tutorials/blob/master/recipes_source/recipes/what_is_state_dict.py) => potentially for expanding Torchsharp tests on state_dict

**Comment by GeorgeS2019** [comment]
@Ricochet73 if you could share [a simple tutorial](https://github.com/dotnet/TorchSharpExamples) with PPO algorithm using the latest implemented torchsharp load_state_dict functionality, this would be greatly appreciated.

**Comment by Ricochet73** [comment]
I will have a look and get back to you.

**Comment by GeorgeS2019** [comment]
@Ricochet73  have a look on [reinforcement training using Torchsharp](https://github.com/edbeeching/godot_rl_agents/issues/16#issue-1211538523) within the Godot Engine
