### ISSUE TITLE
有针对模型随机权重初始化的方法吗？我是新手,麻烦提供相应的案例

### ISSUE THREAD

**Issue by wormhole2019** [dotnet/TorchSharp#577]

**Comment by GeorgeS2019** [comment]
> Is there a way to initialize random weights for the model? I am a novice, please provide the corresponding case

**Comment by NiklasGustafsson** [comment]
Yes, unless you load saved weights, every module will have random weights upon creating.

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson  i will not attempt English back to Chinese 😄

**Comment by NiklasGustafsson** [comment]
I will close this issue, given that an answer has been provided. Please re-open if the answer is not satisfactory.
