### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by BernhardGlueck** [dotnet/TorchSharp#593]
1. Hi !

I hope this is the right venue to ask this but a few questions came up for me, that would be awesome to get an answer to.
Thanks for the great work and finally a project allowing proper deep learning in C#. 

Now for my questions:

1. Is the hinted at productization in the ML.NET roadmap of this project happening ? 
2. What are the plans for torchscript export as well as Onnx export  as they are the big enabled for production usage...
3. What are the plans for distributed training ( the python tools for that would probably not work, so are there any plans to add a new C# implementation of that kind of functionality ? )
4. Are there plans to bring up the other Accelerators like TPUs etc ? 

Thanks for your work and time !

**Comment by NiklasGustafsson** [comment]
@BernhardGlueck , I'm moving this over to 'Discussions.'
