### ISSUE TITLE
Multiple assert statements in xUnit tests

### ISSUE THREAD

**Issue by MovGP0** [dotnet/TorchSharp#615]
most test cases in this repository feature multiple lines with asserts. The issue here is that the code breaks on the first failing condition and doesn't check the rest of the asserts. Therefore, I recommend introducing the [FluentAssertions](https://fluentassertions.com/introduction) library and use [assertion scopes](https://medium.com/geekculture/using-assertion-scopes-to-execute-multiple-assertions-in-c-fcded73b1a35). 

The drawback is that we introduce an additional dependency and would have to rewrite existing asserts to use the FluentAssertion equivalents.  

There is also `Assert.Multiple()` in [xUnit 2.4.2-pre](https://www.thomasbogholm.net/2021/11/25/xunit-2-4-2-pre-multiple-asserts-in-one-test), but the dependency on an pre-release library might also introduce unwanted issues.

**Comment by NiklasGustafsson** [comment]
@MovGP0, I propose that we wait until 2.4.2 is out of 'prerelease' status and then move on to that version. There'll be lots of editing to do to take advantage, but this is a good idea.

**Comment by NiklasGustafsson** [comment]
@MovGP0, since it's no longer in preview, I have updated the test projects to xUnit 2.4.2, where Assert.Multiple() is available. See PR #675

**Comment by NiklasGustafsson** [comment]
PR #675 has been merged, so multiple asserts should now be supported.
