### ISSUE TITLE
Web client has been deprecated and should to replaced with HttpClient

### ISSUE THREAD

**Issue by dayo05** [dotnet/TorchSharp#637]
In Hub.cs, This uses WebClient to download the file. 

This class has marked as obsolete on .NET6 and this class will removed soon.

**Comment by NiklasGustafsson** [comment]
@kaiidams -- since you introduced Hub.cs, could you take care of this issue?

**Comment by kaiidams** [comment]
They also depends on `WebClient`.

https://github.com/dotnet/TorchSharp/blob/e2bd85f50fc513b31bc6cecaf31dc2683f97a147/src/TorchSharp/TorchVision/dsets/MNIST.cs
https://github.com/dotnet/TorchSharp/blob/e2bd85f50fc513b31bc6cecaf31dc2683f97a147/src/TorchSharp/TorchVision/dsets/CIFAR.cs
