### ISSUE TITLE
Cuda not found for embedding

### ISSUE THREAD

**Issue by axel578** [dotnet/TorchSharp#639]
Hello !
It seems that embedding doesnt work with cuda, all tensors are on the cuda device
![image](https://user-images.githubusercontent.com/44734791/175700137-551f1cf7-34c6-41b3-801d-946a03fc3aae.png)

the error message:
`System.Runtime.InteropServices.ExternalException : 'Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)
Exception raised from common_device_check_failure at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\adaption.cpp:10 (most recent call first):
00007FFD4E5AA4C200007FFD4E5AA460 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FFD4E5A9D8E00007FFD4E5A9D40 c10.dll!c10::detail::torchCheckFail [<unknown file> @ <unknown line number>]
00007FFC0EBEAB6600007FFC0EBEAAA0 torch_cpu.dll!c10::impl::common_device_check_failure [<unknown file> @ <unknown line number>]
00007FFC2715E0E400007FFC27145B90 torch_cuda_cu.dll!at::cuda::view_as_real [<unknown file> @ <unknown line number>]
00007FFC270FD69400007FFC270BA730 torch_cuda_cu.dll!at::cuda::bucketize_outf [<unknown file> @ <unknown line number>]
00007FFC0F14A0F700007FFC0F149FB0 torch_cpu.dll!at::_ops::index_select::call [<unknown file> @ <unknown line number>]
00007FFC0ED3537C00007FFC0ED35070 torch_cpu.dll!at::native::embedding [<unknown file> @ <unknown line number>]
00007FFC0F69F83000007FFC0F69E710 torch_cpu.dll!at::compositeexplicitautograd::xlogy_ [<unknown file> @ <unknown line number>]
00007FFC0F66623B00007FFC0F64B0D0 torch_cpu.dll!at::compositeexplicitautograd::bmm [<unknown file> @ <unknown line number>]
00007FFC0F4744AA00007FFC0F44F050 torch_cpu.dll!at::_ops::zeros_like::redispatch [<unknown file> @ <unknown line number>]
00007FFC0F4D24A100007FFC0F4D2400 torch_cpu.dll!at::_ops::embedding::redispatch [<unknown file> @ <unknown line number>]
00007FFC10233BD400007FFC0FF9A050 torch_cpu.dll!torch::autograd::GraphRoot::apply [<unknown file> @ <unknown line number>]
00007FFC10221B4F00007FFC0FF9A050 torch_cpu.dll!torch::autograd::GraphRoot::apply [<unknown file> @ <unknown line number>]
00007FFC0F48DEB700007FFC0F48DD40 torch_cpu.dll!at::_ops::embedding::call [<unknown file> @ <unknown line number>]
00007FFC10E2582A00007FFC10E254E0 torch_cpu.dll!torch::nn::EmbeddingImpl::EmbeddingImpl [<unknown file> @ <unknown line number>]
00007FFC10E263C700007FFC10E26370 torch_cpu.dll!torch::nn::EmbeddingImpl::forward [<unknown file> @ <unknown line number>]
00007FFD3930010400007FFD39300070 LibTorchSharp.DLL!THSNN_Embedding_forward [<unknown file> @ <unknown line number>]
00007FFCDC04A2F0 <unknown symbol address> !<unknown symbol> [<unknown file> @ <unknown line number>]`

the code:
`Embedding = nn.Embedding(
            num_embeddings: numVocab,
            embedding_dims: EmbeddingDim);
var embed = Embedding.forward(x);`

**Comment by axel578** [comment]
As always, I find the 'maybe answer' after asking, I forgot to use the Embedding.cuda(0) method

**Comment by NiklasGustafsson** [comment]
> As always, I find the 'maybe answer' after asking, I forgot to use the Embedding.cuda(0) method

:-) So, can we close this issue, then?

**Comment by NiklasGustafsson** [comment]
@axel578 -- since there's no answer, I will close the issue now. Please reopen with more information if this is still an issue.
