### ISSUE TITLE
tensor is missing a mean(dim=-2) method

### ISSUE THREAD

**Issue by toolgood** [dotnet/TorchSharp#648]
tensor is missing a mean(dim=-2) method.

source code
``` python
   def _get_initial_context(self, V, L_Q):
        B, H, L_V, D = V.shape
        if not self.mask_flag:
            V_sum = V.mean(dim=-2)  # here
            contex = V_sum.unsqueeze(-2).expand(B, H, L_Q, V_sum.shape[-1]).clone()
        else: 
            contex = V.cumsum(dim=-2)
        return contex
```

**Comment by 241721** [comment]
Hmm V.mean(dimensions: new long[] { -2 }) should work fine. You don't have that implementation?
But btw, dim = -2 means that u pass second from the last element (in that case dimension), don't u? 
See: https://www.i2tutorials.com/what-are-negative-indexes-and-why-are-they-used/
So just in regular TorchSharp torch.Tensor.mean() implementation pass V.mean(dimensions: new long[] { x.dim()-2 });

**Comment by lostmsu** [comment]
I think the overloads could be improved here:
1. Add support for `System.Index`
2. Have a `params Index[]` and/or `params long[]` overloads with the other parameters optionally moved to the beginning of the parameter list.
This might apply to any methods that take an array of dims.

**Comment by toolgood** [comment]
@PointerGuide @lostmsu thank you.

**Comment by PointerGuide** [comment]
> I think the overloads could be improved here:
> 
> 1. Add support for `System.Index`
> 2. Have a `params Index[]` and/or `params long[]` overloads with the other parameters optionally moved to the beginning of the parameter list.
> 
> This might apply to any methods that take an array of dims.

Yep, that would be much better. Especially adding "params".
