### ISSUE TITLE
Can not convert 2D array to tensor by using from_array() method.

### ISSUE THREAD

**Issue by wangyexiang** [dotnet/TorchSharp#655]
**My code:**
```
int[][] a = { new[] { 1, 2, 3 }, new[] { 4, 5, 6 }, new[] { 7, 8, 9 }, new[] { 10, 11, 12 } };
var ii = from_array(a);
```
**raise exception:**
`System.NotSupportedException:“The type System.Int32[] is not supported.”`

**Comment by NiklasGustafsson** [comment]
@wangyexiang -- 'from_array()' does not support jagged arrays (arrays of arrays). It supports n-dimensional arrays, for example:

```C#
int[,] a = new int[,] { { 1, 2, 3, 4 }, { 5, 6, 7, 8 } };
var ii = from_array(a);
```
