### ISSUE TITLE
Enable API Compat for TorchSharp

### ISSUE THREAD

**Issue by ericstj** [dotnet/TorchSharp#681]
Can we enable API Compat for TorchSharp?   It’s part of the .NET SDK since 6.0.

Enabling it can be done with these steps:
[.NET Package Validation - .NET | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/fundamentals/package-validation/overview)

This will help flag when changes are made that would break the API surface.  You can still choose to make those changes if you want to suppress the errors, but this will make it clear when breaking changes are made.

**Comment by NiklasGustafsson** [comment]
Sounds like a great idea. Can I talk you into volunteering to do it? :-)

**Comment by ericstj** [comment]
Sure, I'll submit a change that does it.
