### ISSUE TITLE
[Help]Cycle detected TorchSharp -> TorchSharp >=0.971

### ISSUE THREAD

**Issue by ewdlop** [dotnet/TorchSharp#687]
Hello

 I was trying to add the TorchSharp NuGet package to my VS project. I kept getting the following strange error:
 
 Cycle detected TorchSharp -> TorchSharp >=0.971
 
 I got the same error with a different version too. The Cuda native package installed fine though. I am wondering how I go about it. Is there something with my dev environment?
 
 I also noticed I got the same error if I try to install DiffSharp
 
 Thank you

**Comment by NiklasGustafsson** [comment]
Hello @ewdlop -- when are you seeing this error, specifically? I just tried to update a project from 0.96.7 to 0.97.1, and it worked fine.

Also, are you including TorchSharp-cpu or TorchSharp-cuda, and on what OS?

**Comment by ewdlop** [comment]
I think I know what happened. There was a namespace conflict with my visual studio project  Thank you for the help. 
It was on Windows btw.
