### ISSUE TITLE
torch.InitializeDeviceType(DeviceType.CPU) fails on OSX

### ISSUE THREAD

**Issue by arghyasur1991** [dotnet/TorchSharp#689]
This internally calls into
`NativeLibrary.TryLoad(path, out var res);`

which is defined as follows - 

```
public static bool TryLoad(string libraryPath, out IntPtr handle)
        {
            if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                throw new NotSupportedException("This call is not supported on non-Windows platforms.");
            }

            if (libraryPath == null)
                throw new ArgumentNullException(nameof(libraryPath));

            handle = LoadFromPath(libraryPath, throwOnError: false);
            return handle != IntPtr.Zero;
        }
```

Since the runtime check is for windows only, it throws exception and fails to load the library.
I have no idea if I am missing something, but TorchSharp doesn't seem usable in mac due to this code.

**Comment by NiklasGustafsson** [comment]
Which NuGet package did you install? If you're using TorchSharp, you also need to install a LibTorch package. It's recommended to use TorchSharp-cpu, which pulls in both the main TS library as well as the right underlying LibTorch library.

**Comment by arghyasur1991** [comment]
I already did that. There are issues in the logic of loading before as well like the package name needing "torchsharp" in smaller case only. 
```
if (torchsharpLoc.Contains("torchsharp") && torchsharpLoc.Contains("lib") && Directory.Exists(packagesDir) && Directory.Exists(torchsharpHome)) {
```
And then the libtorch-cpu-osx-x64 folder had version concatenated 1.11.0.1 in the root only as opposed to the code wanting 2-level structure
```
var packages =
                    Directory.GetDirectories(packagesDir, packagePattern)
                       .Where(d => Directory.Exists(Path.Combine(d, packageVersion)))
                       .ToArray();
```

These 2 issues could be worked around by renaming and changing the package directory structures. But the final issue of loading failure is because it tries to always route through NativeLibrary.TryLoad which throws exception on non windows platform.

I checked and found the intiializeDevice is called from many operations in Tensor class. So, not sure how it is supposed to work in non-windows platforms

**Comment by NiklasGustafsson** [comment]
So, this would only happen if torchsharp comes from NuGet, then? I'm wondering, since we test on OSX all the time, but built form source, not downloaded packages.

**Comment by NiklasGustafsson** [comment]
@tarekgh -- any thoughts?

**Comment by tarekgh** [comment]
@arghyasur1991 what is the target in your project? if it is netstandard, then you need to change that to explicitly targetting either net core 3.1 or up or targetting netfx 4.7 or up.

**Comment by tarekgh** [comment]
> This also seems to be related to https://github.com/dotnet/TorchSharp/issues/640

This is unrelated. https://github.com/dotnet/TorchSharp/issues/640 is about including the published bits with the project output.

**Comment by NiklasGustafsson** [comment]
@arghyasur1991 -- is this still a problem for you? If yes, could you please provide more information as requested? If not, please close the issue.

**Comment by glopesdev** [comment]
This is related to #1311 just opened. It is not clear to us how these native dependencies are supposed to be loaded on non-windows platforms, if NativeLibrary cannot handle cross-platform shared libraries.
