### ISSUE TITLE
loading tensor from Pytorch in TorchSharp

### ISSUE THREAD

**Issue by sheercyy** [dotnet/TorchSharp#706]
Hi, I have a question if we can load one or more tensors from a file saved from Pytorch in TorchSharp. I see that the methods Tensor.load() and Tensor.save() are implemented for loading and saving tensors in TorchSharp. Just wondering if there is a way to do it between Pytorch and TorchSharp?

**Comment by NiklasGustafsson** [comment]
Yes. 

See:

https://github.com/dotnet/TorchSharp/blob/main/docfx/articles/saveload.md

and

https://github.com/dotnet/TorchSharp/blob/main/docfx/articles/torchscript.md

For saving/loading entire models. The code of the former is built on the code for saving individual tensors.

**Comment by sheercyy** [comment]
> Yes.
> 
> See:
> 
> https://github.com/dotnet/TorchSharp/blob/main/docfx/articles/saveload.md
> 
> and
> 
> https://github.com/dotnet/TorchSharp/blob/main/docfx/articles/torchscript.md
> 
> For saving/loading entire models. The code of the former is built on the code for saving individual tensors.

Thanks for this. If I get it correctly, this is for saving and loading the pytorch/TorchSharp models. I am wondering if this can be used for save any tensor(s) I encontered in TorchSharp. For example, I created a tensor in Pytorch tensorsave = torch.ones(20,20), is there a way I save this tensorsave variable to be loaded by TorchSharp in C# or vice versa?

**Comment by NiklasGustafsson** [comment]
Yes, that's what I meant by saying that it's built on the code for saving individual tensors. See:

https://github.com/dotnet/TorchSharp/blob/main/src/TorchSharp/Tensor/TensorExtensionMethods.cs#L247

You do have to use the logic in:

**Comment by sheercyy** [comment]
Thanks, this really helps.
