### ISSUE TITLE
A separate numpy package in C#

### ISSUE THREAD

**Issue by ChengYen-Tang** [dotnet/TorchSharp#709]
I want to transfer some AI projects on python to C#, because python's multi-core computing is not very friendly, and the basic computing speed of python is not very ideal.
I think numpy is a big problem when I migrate, numpy provides many friendly methods for data processing, but these functions must be implemented by myselves in C#, the SciSharp project does not seem to be actively maintained, and many bugs or functions are not completed
Therefore, I hope that a numpy for .net kit can be provided here, which can be easily combined with TorchSharp
thanks

**Comment by GeorgeS2019** [comment]
@ChengYen-Tang 
Have u read this?
https://github.com/dotnet/TorchSharp/discussions/394

**Comment by GeorgeS2019** [comment]
@ChengYen-Tang 
https://www.youtube.com/watch?v=s3Epe3ox72s

When Torchsharp was given a new commitment back in 2020, the aim was to support .NET community to keep e.g. deep machine learning training and inference to stay within ..NET. The decision to imitate python syntax, I believe, is key to a more friendly and low learning curve adoption of TorchSharp by .NET community.

The second goal, which I often being reminded of, is to focus and cover the TorchSharp **core** and keep it up-to-date with the latest PyTorch release. 

There is still **a lot to do** for the second goal.

This is why, again being reminded often, not to put effort beyond Torchsharp e.g. NumPy

### HOWEVER, 

Many .NET users have expressed before, supporting NumPy would assist the Torchsharp adoption 

There are many excellent and experienced developers here. 

The key to bringing reliable NumPy to .NET users is to mobilize them into ONE effort.

 This could be done OUTSIDE TorchSharp but uses the Torchsharp platform to **get coding tips** in making the NumPy vision for .NET community **reliable**.

**Comment by ChengYen-Tang** [comment]
Hi @GeorgeS2019 ,
Yes, I think Microsoft can lead the community to develop Numpy to C#, although SciSharp wants to do it, obviously they don't have enough people.
I hope that numpy can be implemented on C# as soon as possible, because the absence of numpy has greatly increased the difficulty of project migration. I believe that many developers have the same problem.

**Comment by GeorgeS2019** [comment]
@ChengYen-Tang 
https://github.com/Quansight-Labs/numpy.net

**Comment by ChengYen-Tang** [comment]
Thanks, I didn't discover this repository before.

**Comment by GeorgeS2019** [comment]
@ChengYen-Tang 

What is the final decision on numpy.

How u address this in tensorboard?
