### ISSUE TITLE
Span<T> can replace pointers to stackalloc when they're not needed.

### ISSUE THREAD

**Issue by TheBlackPlague** [dotnet/TorchSharp#712]
In TorchSharp, there is this code:
```cs
    public static unsafe torch.Tensor zeros(
      int size,
      torch.ScalarType? dtype = null,
      torch.Device? device = null,
      bool requiresGrad = false)
    {
      long* pointer = stackalloc long[1];
      pointer[0] = (long) size;
      return torch._zeros((ReadOnlySpan<long>) new Span<long>((void*) pointer, 1), dtype, device, requiresGrad);
    }
```

This can be replaced by:
```cs
    public static unsafe torch.Tensor zeros(
      int size,
      torch.ScalarType? dtype = null,
      torch.Device? device = null,
      bool requiresGrad = false)
    {
      ReadOnlySpan<long> dim = stackalloc long[] { size };
      return torch._zeros(dim, dtype, device, requiresGrad);
    }
```

From my interpretation, this makes the codebase look cleaner.

**Comment by NiklasGustafsson** [comment]
@TheBlackPlague -- this looks like code I might have written in the past, when I didn't quite grasp stackalloc from a type perspective. However, I've been looking for this code fragment, but I can't find it. Could you tell me the file and line number?

Thanks!

**Comment by TheBlackPlague** [comment]
> @TheBlackPlague -- this looks like code I might have written in the past, when I didn't quite grasp stackalloc from a type perspective. However, I've been looking for this code fragment, but I can't find it. Could you tell me the file and line number?
> 
> Thanks!
> 
> This is the code with that method signature that I find:
> 
> ```cs
>         /// <summary>
>         ///  Create a new 1-D tensor filled with zeros
>         /// </summary>
>         public static Tensor zeros(int size, torch.ScalarType? dtype = null, torch.Device? device = null, bool requiresGrad = false)
>         {
>             return _zeros(stackalloc long[] { size }, dtype, device, requiresGrad);
>         }
> ```

Ah. I found it with the disassembler, but I'm missing 2 critical updates on the version of TorchSharp I'm using for my project. Apologies for this issue. The code was likely changed in those 2 updates.
