### ISSUE TITLE
How to implement the following code

### ISSUE THREAD

**Issue by githubxiaoa** [dotnet/TorchSharp#715]
How to implement the following code:
nn.Sequential(*list(resnet18().children())[:-3])

it's error like this:
<img width="650" alt="QQ20220912-191215@2x" src="https://user-images.githubusercontent.com/31387524/189639826-e52643ae-cf0f-4615-aa24-6fae571be535.png">

**Comment by NiklasGustafsson** [comment]
@githubxiaoa -- found the problem. This will be fixed in the next version. Also, note that the TorchSharp version of ResNet has one more layer at the very end than the PyTorch version does -- it ends with a Flatten module.
