### ISSUE TITLE
ResNet maxpool 

### ISSUE THREAD

**Issue by githubxiaoa** [dotnet/TorchSharp#719]
pytorch code:
self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)

kernel_size=3

torchsharp:
maxpool = MaxPool2d(kernelSize: 2, stride: 2, padding: 1);

**Comment by NiklasGustafsson** [comment]
Ah, I see -- the torchvision.ResNet models have a bug. Will be fixed in next version.
