### ISSUE TITLE
Active Community Chat Room

### ISSUE THREAD

**Issue by TheBlackPlague** [dotnet/TorchSharp#724]
Hello,

This isn't necessarily an issue, but I'm wondering if there is an active chat service (preferably Discord or something similar) where we can actively discuss the development of TorchSharp and seek help from others regarding this library.

Please let me know.

**Comment by GeorgeS2019** [comment]
Hi Sohail  @TheBlackPlague 

The most active person who scans through what is new on regular basis is @NiklasGustafsson 

A few of us, including myself, are to keep the traffic active.

TorchSharp is approaching an interesting phase where many features are getting in place. 

So far, from my point of view, is to create **a CREDIBLE framework** for the .NET community to jump in to contribute to the missing parts.

What you could do is to start asking what you could do, even starting with a little contribution, here and there.  

Even inviting others to join the discussion you created is already a great contribution.

By engaging, I have learned so much and I urge anyone to do so.

**Comment by TheBlackPlague** [comment]
Hi George,

Thank you for your response. That's all good for figuring out how to contribute, but I'm more so talking about in general. I am using this library for my own project and occasionally run into places where I wonder how it'd be done for TorchSharp. 

A Community Chat room would be beneficial for all those that want to use this library.

**Comment by GeorgeS2019** [comment]
I understand your suggestion.  There is a Gitter, however, no ONE uses it. It has been dormant for many years.  THIS is the only place that is ACTIVE right now.

**Comment by GeorgeS2019** [comment]
First, we need to build UP the critical mass.  Once we are there, there will be enough people to keep the Chat going.

**Comment by GeorgeS2019** [comment]
[Which projects use TorchSharp?](https://github.com/dotnet/TorchSharp/network/dependents?package_id=UGFja2FnZS0yMTEyNjYxNjA%3D)

**Comment by GeorgeS2019** [comment]
I am independent, my view does not reflect the organization driving this project.

**Comment by NiklasGustafsson** [comment]
The old gitter room was associated with the old TorchSharp org -- 'xamarin'.

I just started a new room: https://gitter.im/dotnet/TorchSharp. Let's try to use that for chats. I will make it a habit to look there.

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson 

We need a logo on the front page with link to the gitter

![image](https://user-images.githubusercontent.com/49812372/190276274-6df30ca9-df12-46ef-96f7-cf253365c286.png)
