### ISSUE TITLE
Changing `torchvision` namespace into a static class?

### ISSUE THREAD

**Issue by kaiidams** [dotnet/TorchSharp#729]
Quite a few code starts from `torchvision` instead of importing objects by `from torchvision... import xxx`

https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html
```py
model = torchvision.models.detection.fasterrcnn_resnet50_fpn(weights="DEFAULT")
```

Now in TorchSharp, we have `TorchSharp.torchvision` namespace. 

```csharp
namespace TorchSharp.torchvision
{
    public static partial class models
    {
```

Can we make this a class `TorchSharp.torchvision` like we did for `TorchSharp.torch` class?

```csharp
namespace TorchSharp
{
    public static partial class torchvision
    {
        public static partial class models
        {
```

I believe that we have to do like these in C#

```csharp
using TorchSharp.torchvision;
...
models.detection.fasterrcnn_resnet50_fpn();
```
or
```csharp
using static TorchSharp.torchvision.models.detection;
...
fasterrcnn_resnet50_fpn();
```

**Comment by NiklasGustafsson** [comment]
Any time a scope directly contains methods, or is nested within a scope that contains methods, whether instance factories or other, it needs to be a static class. If that is the case with 'torchvision,' it should definitely be a static class.

**Comment by kaiidams** [comment]
PyTorch torchvision has four methods

- `torchvision.set_image_backend(backend)`
- `torchvision.get_image_backend()`
- `torchvision.set_video_backend(backend)`
- `torchvision.get_video_backend()`

TorchSharp has `Imager` as an argument of `torchvision.io.read_image()` instead of having those four methods.
So currently TorchSharp doesn't have any methods under the `torchvision` named scope.

A namespace has to start from the top. Currently we cannot write like this in the user code.
```csharp
using TorchSharp;
...
torchvision.io.read_image()
```
