### ISSUE TITLE
Sequential.Add

### ISSUE THREAD

**Issue by githubxiaoa** [dotnet/TorchSharp#730]
I tried to write resnet myself, and this problem occurred：
<img width="703" alt="QQ20220915-230535@2x" src="https://user-images.githubusercontent.com/31387524/190440092-f3e8dea7-2291-4b8c-b93f-c8f003c25fb4.png">

**Comment by NiklasGustafsson** [comment]
Ah... 'Add' is internal, since it's not part of the PT API. You can rewrite MakeLayer to take a list which you then turn into a Sequential at the very end. Or wait for the next release.

**Comment by NiklasGustafsson** [comment]
The PT API has an 'append,' which we're missing. I'll add that.
