### ISSUE TITLE
Ease of use: `Module.to` method should be generic `T -> T`

### ISSUE THREAD

**Issue by lostmsu** [dotnet/TorchSharp#742]
Currently it is an instance method that returns `Module`, which means I can't do simple code like `Linear layer = Linear(...).to(device)`.

**Comment by NiklasGustafsson** [comment]
Sounds like a reasonable idea.

**Comment by NiklasGustafsson** [comment]
If "T" is not the right type, would you prefer an exception or returning 'null'?

**Comment by lostmsu** [comment]
Exception would be better imho.

I am unsure how to let the user still call the method though.

**Comment by NiklasGustafsson** [comment]
> I am unsure how to let the user still call the method though.

Not sure what you mean, exactly.

**Comment by lostmsu** [comment]
There's existing `virtual Module to(...)`, which allows modules to return modules of different type. Simply adding `T to<T>(...)` won't work because C# does not overload based on return type. Presumably TorchSharp would want to keep the original virtual method in order to preserve the ability to return a module of different type (which I am not sure is required). In that case the generic would need to be named differently.

**Comment by NiklasGustafsson** [comment]
No, it doesn't overload on return type, but it does seem to overload on whether there's a type parameter or not (which is what I thought it did). The compiler has no issue with the two versions side by side (untyped for PT compat, typed for convenience).

**Comment by lostmsu** [comment]
`.to<Modules.Linear>` that variant is not very convenient though

**Comment by NiklasGustafsson** [comment]
So what is the experience you're looking for? That's the experience I thought you were proposing.

**Comment by NiklasGustafsson** [comment]
So, the extension methods approach that you described elsewhere should work for this -- I'll get rid of the 'to()' declarations in Module and put them in the extension methods class, instead. As long as 'using TorchSharp' is present in any file where 'to' is used, it should work.

**Comment by lostmsu** [comment]
@NiklasGustafsson not sure if anybody cared, but what if people would want to override how `to` works (they can now)?

**Comment by NiklasGustafsson** [comment]
They would override '_to()', which is declared as 'internal protected' One of the examples does that, and I'll add a comment to the article/wiki page on custom modules.

It should be very rare to have to do so, though.
