### ISSUE TITLE
[WIP] Wiki

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/TorchSharp#748]
We now have Wiki
Creating an issue here to track what need to go into the Wiki

## Python API 
- [ ] [torch](https://pytorch.org/docs/stable/torch.html#module-torch)
- [ ] [torch.nn](https://pytorch.org/docs/stable/nn.html)
- [ ] [torch.nn.functional](https://pytorch.org/docs/stable/nn.functional.html)
- [x] [torch.jit](https://pytorch.org/docs/stable/jit.html)
   - [x] [torch.jit.compile()](https://pytorch.org/cppdocs/api/function_namespacetorch_1_1jit_1a8660dc13a6b82336aadac667e6dccba1.html)

## Libraries
- [ ] [TorchAudio API](https://pytorch.org/audio/stable/index.html)
- [ ] [TorchVision API](https://pytorch.org/vision/stable/index.html)

## Others
- [x] [Tensor String Formatting](https://github.com/dotnet/TorchSharp/pull/737)

## FAQ
- [ ] Common problems when using TorchSharp with notebook

**Comment by GeorgeS2019** [comment]
### [TorchAudio API coverage](https://pytorch.org/audio/stable/index.html)
- [ ] torchaudio
- [ ] torchaudio.io
- [ ] torchaudio.backend
- [ ] torchaudio.functional
- [ ] torchaudio.transforms
- [ ] torchaudio.datasets
- [ ] torchaudio.models
- [ ] torchaudio.models.decoder
- [ ] torchaudio.pipelines
- [ ] torchaudio.sox_effects
- [ ] torchaudio.compliance.kaldi
- [ ] torchaudio.kaldi_io
- [ ] torchaudio.utils

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson 
My setup is really strange, simple loading of Cuda NuGet takes forever. Including loading from a local source.
Is there a way or eventually a FAQ to troubleshoot what could go wrong

![Code_5LwdIDrF0J](https://user-images.githubusercontent.com/49812372/192037007-5209ce2a-f866-437b-924f-89b23438e600.gif)

**Comment by NiklasGustafsson** [comment]
The CUDA NuGet packages are enormous -- they are so big, that we had to split them into multiple chunks and then put them together on the local system. again. So, depending on your bandwidth, it can take a long time. 21 min sounds long, but it's definitely 5-6 minutes or more, even on a fast connection. Once they have been downloaded, it's a different story.

**Comment by GeorgeS2019** [comment]
Simply nuget:TorchSharp-cpu
Restart kernel, yet the warning message happens!

![image](https://user-images.githubusercontent.com/49812372/192054904-0c5c88cc-5630-4143-a6b5-f7744bac199c.png)

**Comment by GeorgeS2019** [comment]
## [TorchScript -from HuggingFace](https://huggingface.co/docs/transformers/serialization#torchscript)

>“TorchScript is a way to create serializable and optimizable models from PyTorch code”. Pytorch’s two modules [**JIT** and **TRACE**](https://pytorch.org/docs/stable/jit.html) allow the developer to export their model to be re-used in other programs written in e.g. c#

> Starting with release TorchSharp 0.96.9, you can load TorchScript modules and functions that have been either **traced** or **scripted** in Pytorch

**Comment by GeorgeS2019** [comment]
I try to evaluate the pro/con of using TorchScript(TorchSharp) versus Onnx(ML.NET) as stated here.

<details>
<summary><strong>Using PyTorch to save TorchSript model: traced_bert.pt</summary>

#### [Using PyTorch to save TorchSript model](https://huggingface.co/docs/transformers/serialization#saving-a-model)
Using TorchSharp to load traced_bert.pt for inference

```python
from transformers import BertModel, BertTokenizer, BertConfig
import torch

enc = BertTokenizer.from_pretrained("bert-base-uncased")

# Tokenizing input text
text = "[CLS] Who was Jim Henson ? [SEP] Jim Henson was a puppeteer [SEP]"
tokenized_text = enc.tokenize(text)

# Masking one of the input tokens
masked_index = 8
tokenized_text[masked_index] = "[MASK]"
indexed_tokens = enc.convert_tokens_to_ids(tokenized_text)
segments_ids = [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1]

# Creating a dummy input
tokens_tensor = torch.tensor([indexed_tokens])
segments_tensors = torch.tensor([segments_ids])
dummy_input = [tokens_tensor, segments_tensors]

# Initializing the model with the torchscript flag
# Flag set to True even though it is not necessary as this model does not have an LM Head.
config = BertConfig(
    vocab_size_or_config_json_file=32000,
    hidden_size=768,
    num_hidden_layers=12,
    num_attention_heads=12,
    intermediate_size=3072,
    torchscript=True,
)

# Instantiating the model
model = BertModel(config)

# The model needs to be in evaluation mode
model.eval()

# If you are instantiating the model with *from_pretrained* you can also easily set the TorchScript flag
model = BertModel.from_pretrained("bert-base-uncased", torchscript=True)

# Creating the trace
traced_model = torch.jit.trace(model, [tokens_tensor, segments_tensors])
torch.jit.save(traced_model, "traced_bert.pt")
```

</details>

<details>
<summary><strong>Using PyTorch to export Onnx: traced_bert.onnx</summary>

### [Using PyTorch to export Onnx](https://rubikscode.net/2022/09/13/bert-tokenizers-for-ml-net/)
Using Torch Sharp load traced_bert.onnx for inference

</details>

**Comment by NiklasGustafsson** [comment]
@GeorgeS2019 -- is there an issue here? I'm not sure what problem this is tracking.
