### ISSUE TITLE
torch.index_put_ etc

### ISSUE THREAD

**Issue by Sprinzl** [dotnet/TorchSharp#758]
Hello,
first this libary is one of the best i came along for a long time. I am trying to make an echo state network.
In pytorch where is an overload (accumulate) which i think (i do not know) is aggregating the input to the existing tensor. 
Where are also other index operations like:

index_add_
index_add
index_copy_
index_copy
index_fill_
index_fill
index_put_
index_put
index_select

which are not extisting right now. I want to have some kind of lookup which is describing the connections between the neurons. Whats why I need this quite urgend.

greeting Michael

some thing like this,but it should sum up or do other operations if it matches the index more often.

var i1 = tensor(new int[]{ 0,0,1,2}).to(ScalarType.Int64);
           var i2 = tensor(new int[] { 0,0,3,1 }).to(ScalarType.Int64);
           var x1 = torch.zeros(6);
           var x2 = tensor(new float[] { 1, 5, 10, 1 });
           var data = x2.index_select(0, i1);
           x1.index_put_(data, i2);
           x1.print();

**Comment by Sprinzl** [comment]
Sorrx found a solution.... torch.scatter_add_(x1, 0, i1, data);

**Comment by NiklasGustafsson** [comment]
All of those index_* operators are defined on Tensor. The only missing feature is 'accumulate' on index_put.

**Comment by GeorgeS2019** [comment]
>  The only missing feature is 'accumulate' on index_put.

I look through the codes, but could not follow your statement. Appreciate a bit of further elaboration.

**Comment by GeorgeS2019** [comment]
- [x] index_add_
- [x] ndex_add
- [x] index_copy_
- [x] index_copy
- [x] index_fill_
- [x] index_fill
- [x] index_put_
- [x] index_put
- [x] index_select
