### ISSUE TITLE
Torchvision.IO related to DenseNet

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/TorchSharp#763]
[DenseNet.cs](https://github.com/WindDYTING/DeepWind/blob/main/src/DeepWind/NeuralNetworks/Classification/DenseNet.cs) of the project [DeepWind ](https://github.com/WindDYTING/DeepWind/issues/1#issuecomment-1261720690)is based on [densenet.py](https://github.com/pytorch/vision/blob/v0.13.1/torchvision/models/densenet.py)

@kaiidams @NiklasGustafsson 

Do look into this project to see and if possible feedback/recommend if the Torchvision.**IO** and potentially **processing** attempts here could add value to Torchsharp and/or Torchsharp.Example projects

**Comment by NiklasGustafsson** [comment]
The project is using ImageSharp for I/O. 

Supporting ImageSharp would not be hard if we were to choose that as the image library we use for loading and saving images. As discussed elsewhere, we have not made that decision yet. We are leaning towards SkiaSharp, but have not made the decision to go with that, either.
