### ISSUE TITLE
Compatibility between the new generic Module<T, TResult> and ModuleList / ModuleDict

### ISSUE THREAD

**Issue by QingtaoLi1** [dotnet/TorchSharp#781]
In version 0.98.0, we have to adding a cast when forwarding a `Module` in a `ModuleList` / `ModuleDict`:
```
// For Example:
var input = torch.tensor( ... );
var list = new ModuleList { ... };
var output1 = list[0].forward(input);   // Compile error because "list[0]" is a Module instead of Module<Tensor, Tensor>.
var output2 = (list[0] as Module<Tensor, Tensor>)?.forward(input);   // Correct
```
Is it possible to support generic `Module` in `ModuleList` / `ModuleDict`, e.g. adding generic `ModuleList` / `ModuleDict`?

**Comment by NiklasGustafsson** [comment]
I'll take a look at it. Seems like something reasonable to do.

**Comment by NiklasGustafsson** [comment]
There are two ways to do it -- create a ModuleDict<T,TResult> which holds Module<T,TResult>, or ModuleDict<T> where T is a Module-derived type. Which would be preferrable? The latter is more flexible, I think, and the current ModuleDict is simply a ModuleDict<Module>

**Comment by QingtaoLi1** [comment]
@NiklasGustafsson Both looks good for my case. And I think the more flexible solution is usually the better.

**Comment by NiklasGustafsson** [comment]
@QingtaoLi1 -- please review the PR.
