### ISSUE TITLE
[Feature request] Reading tensors from file of tensors

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/TorchSharp#785]
#### [Use Case](https://stackoverflow.com/questions/64073517/pytorch-reading-tensors-from-file-of-tensors-stream-training-from-disk)
Given a [list of files of tensors ](https://github.com/fwaris/BertTorchSharp/issues/2#issuecomment-1272404987)with file names consisting of name_tensors, load these files to TorchSharp as name_tensors

With this [WIP PR](https://github.com/dotnet/TorchSharp/pull/779), please advice when the PR is merged, what are missing features needed to make this feature request (Reading tensors from file of tensors) works?

- [ ] TestLoadSave.cs: is there unit tests for loading tensor data saved using to PyTorch and load it back in TorchSharp?
- [ ] Wiki: [Sharing **Model Data** between PyTorch and TorchSharp](https://github.com/dotnet/TorchSharp/wiki/Sharing-Model-Data-between-PyTorch-and-TorchSharp): is there wiki documentation of **sharing tensor data** between PyTorch and TorchSharp?

**Comment by GeorgeS2019** [comment]
Current Wiki: [Sharing **Model Data** between PyTorch and TorchSharp](https://github.com/dotnet/TorchSharp/wiki/Sharing-Model-Data-between-PyTorch-and-TorchSharp)

if I am not wrong, has note extended to a topic on sharing **Tensor Data** between PyTorch and TorchSharp

**Comment by NiklasGustafsson** [comment]
There are already two methods to save tensors: Tensor.save, which uses libtorch native code to write to disk, and Tensor.Save, which uses the .NET-specific serialization format we're using to pass model weights between Python and .NET.

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson  If I am not wrong, all the unit tests in [TestLoadSave.cs](https://github.com/dotnet/TorchSharp/blob/main/test/TorchSharpTest/TestLoadSave.cs) involved TorchSharp save file with ".ts" extension. None of the unit tests involve tensor data saved using PyTorch.

**Comment by NiklasGustafsson** [comment]
The file extensions used in the unit tests have no significance. In these cases, they are written and read by the unit tests, so the file names can be whatever.

Supporting pickling, which is a very general serialization format for all of Python's object model is far outside the scope of TorchSharp. I can readily say (and have done so in the past), that we will not support depickling Python pickle files. As far as exchange formats go, we'll use TorchScript, the custom .NET serialization format for weights (only weights), and at some point, perhaps ONNX, Pickle files will not be supported.

**Comment by NiklasGustafsson** [comment]
If you take a look at the source code, you will see that 'save()' uses libtorch, and 'Save()' uses the .NET format.

**Comment by NiklasGustafsson** [comment]
Let me clarify -- .NET already has an API to load ONNX files and run them, so there's no extra work there. What I was referring to was to add an API to pass TorchSharp tensors to a loaded ONNX model.

**Comment by GeorgeS2019** [comment]
#### Something to think about :-)
> How to pass TorchSharp tensors to a loaded ONNX model

**Comment by GeorgeS2019** [comment]
<details>
<summary>Save/Load .Net Specific</summary>

`tensor/TensorExtensionMethods.cs`

```cs
/// <summary>
/// Save the tensor in a .NET-specific format.
/// </summary>
/// <param name="tensor"></param>
/// <param name="writer"></param>
public static void Save(this Tensor tensor, System.IO.BinaryWriter writer)
{
    bool copied = false;

    if (tensor.device_type != DeviceType.CPU) {
        tensor = tensor.to(torch.CPU);
        copied = true;
    }

    // First, write the type
    writer.Encode((int)tensor.dtype); // 4 bytes
                                      // Then, the shape.
    writer.Encode(tensor.shape.Length); // 4 bytes
    foreach (var s in tensor.shape) writer.Encode(s); // n * 8 bytes
                                                      // Then, the data
#if NETSTANDARD2_0_OR_GREATER
            // TODO: NETSTANDARD2_0_OR_GREATER Try to optimize to avoid the allocation
            writer.Write(tensor.bytes.ToArray()); // ElementSize * NumberOfElements
#else
            writer.Write(tensor.bytes); // ElementSize * NumberOfElements
#endif // NETSTANDARD2_0_OR_GREATER

     if (copied) tensor.Dispose();
 }

 /// <summary>
 /// Load the tensor using a .NET-specific format.
 /// </summary>
 /// <param name="tensor">The tensor into which to load serialized data.</param>
 /// <param name="reader">A BinaryReader instance</param>
 /// <param name="skip">If true, the data will be read from the stream, but not copied to the target tensor.</param>
 /// <remarks>
 /// Using a skip list only prevents tensors in the target module from being modified, it
 /// does not alter the logic related to checking for matching tensor element types.
 /// </remarks>
 public static void Load(this Tensor tensor, System.IO.BinaryReader reader, bool skip = false)
 {
     // First, read the type
     var type = (ScalarType)reader.Decode();

     if (type != tensor.dtype)
         throw new ArgumentException("Mismatched tensor data types while loading. Make sure that the model you are loading into is exactly the same as the origin.");

     // Then, the shape
     var shLen = reader.Decode();
     long[] loadedShape = new long[shLen];

     long totalSize = 1;
     for (int i = 0; i < shLen; ++i) {
         loadedShape[i] = reader.Decode();
         totalSize *= loadedShape[i];
     }

     if (!skip && !loadedShape.SequenceEqual(tensor.shape))
         // We only care about this if the bytes will be written to the tensor.
         throw new ArgumentException("Mismatched tensor shape while loading. Make sure that the model you are loading into is exactly the same as the origin.");

     //
     // TODO: Fix this so that you can read large tensors. Right now, they are limited to 2GB
     //
     if (totalSize > int.MaxValue)
         throw new NotImplementedException("Loading tensors larger than 2GB");

     // This needs to be done even if the tensor is skipped, since we have to advance the input stream.
     var bytes = reader.ReadBytes((int)(totalSize * tensor.ElementSize));

     if (!skip) {
         var device = tensor.device;
         if (device.type != DeviceType.CPU) tensor.to(torch.CPU);
         tensor.bytes = bytes;
         tensor.to(device);
     }
 }
```
</details>

**Comment by GeorgeS2019** [comment]
> For exchange formats, we'll use TorchScript, the **custom .NET serialization format for weights** (only weights), and at some point, perhaps ONNX,

**Comment by NiklasGustafsson** [comment]
> > A future version of TorchSharp may include support for reading and writing Python pickle files directly.

Yes, it does. Thanks for catching it.

**Comment by NiklasGustafsson** [comment]
@GeorgeS2019 -- I'm going to close this now, since I believe that the way to do what you asked for has been explained. If you disagree, please reopen and explain what further information you need.
