### ISSUE TITLE
torch.where(condition) → tuple of LongTensor function missing

### ISSUE THREAD

**Issue by xhuan8** [dotnet/TorchSharp#787]
torch.where(condition) is identical to torch.nonzero(condition, as_tuple=True).

but it's better to implement it to minimize the gap.

**Comment by GeorgeS2019** [comment]
#### [Indexing, Slicing, Joining, Mutating Ops](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)
- torch.[where](https://pytorch.org/docs/stable/generated/torch.where.html)
  > Return a tensor of elements selected from either x or y, depending on condition. 
- torch.[nonzero](https://pytorch.org/docs/stable/generated/torch.nonzero.html)

**Comment by NiklasGustafsson** [comment]
where is missing the right return variant, but could you tell me whether nonzero_as_list does the right thing vis-a-vis nonzero(condition, as_tuple=True)?

**Comment by xhuan8** [comment]
actually it's not right, the Tensor in list should be 1-D Tensor, not 2D
