### ISSUE TITLE
System.InvalidOperationException: Torch device type CUDA did not initialise on the current machine

### ISSUE THREAD

**Issue by benaclejames** [dotnet/TorchSharp#793]
Hey, this is my first time trying to use TorchSharp and I keep running into the same error regardless of CUDA version, NuGet package version, PyTorch version, and I've even tried using a version build from source to no avail.

Here's the log:
```Unhandled Exception: System.InvalidOperationException: Torch device type CUDA did not initialise on the current machine. Trace from LoadNativeBackend:

TorchSharp: LoadNativeBackend: Initialising native backend, useCudaBackend = True

Step 1 - First try regular load of native libtorch binaries.

    Try loading Windows cuda native components
    Trying to load native component cudnn_adv_infer64_8 relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Failed to load native component cudnn_adv_infer64_8 relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Trying to load native component cudnn_adv_train64_8 relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Failed to load native component cudnn_adv_train64_8 relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Trying to load native component cudnn_cnn_infer64_8 relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Failed to load native component cudnn_cnn_infer64_8 relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Trying to load native component cudnn_cnn_train64_8 relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Failed to load native component cudnn_cnn_train64_8 relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Trying to load native component cudnn_ops_infer64_8 relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Failed to load native component cudnn_ops_infer64_8 relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Trying to load native component cudnn_ops_train64_8 relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Failed to load native component cudnn_ops_train64_8 relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Trying to load native component nvrtc-builtins64_113 relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Failed to load native component nvrtc-builtins64_113 relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Trying to load native component caffe2_nvrtc relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Failed to load native component caffe2_nvrtc relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Trying to load native component nvrtc64_112_0 relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Failed to load native component nvrtc64_112_0 relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Trying to load native component torch_cuda relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Failed to load native component torch_cuda relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Trying to load native component LibTorchSharp relative to C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\TorchSharp.dll
    Result from regular native load of LibTorchSharp is True

   at TorchSharp.torch.InitializeDeviceType(DeviceType deviceType)
   at SharpSpeaker.Program.Main(String[] args) in C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\Program.cs:line 25```

**Comment by NiklasGustafsson** [comment]
Which TorchSharp NuGet package did you use?

**Comment by benaclejames** [comment]
torchsharp-cuda-windows-0.98.0

**Comment by NiklasGustafsson** [comment]
Hmm...

Can you check whether those files it's complaining about failing to load are in that folder `C:\Users\Ben\RiderProjects\SharpSpeaker\SharpSpeaker\bin\Debug\`

**Comment by benaclejames** [comment]
They appear to all be there, or at least the ones it claims to be failing to load are. Here's a photo
![image](https://user-images.githubusercontent.com/11042095/195188078-a2df39d3-0787-4c36-a970-28688d13761b.png)

**Comment by NiklasGustafsson** [comment]
There's something funky going on here -- it's clearly not that the files weren't moved in place, so I wonder if there's something else on the system. What GPU do you have on your machine, and what version driver?

**Comment by benaclejames** [comment]
> it's clearly not that the files weren't moved in place
I moved most of the cuda files manually actually, could that be the issue?
After a clean rebuild, only these files are moved:
![image](https://user-images.githubusercontent.com/11042095/195191248-43e532a0-82da-4e64-9a54-d91e9ce22599.png)

**Comment by NiklasGustafsson** [comment]
I notice that you're using Rider -- I don't think we have actually tested building with Rider. Do you have access to VS and can try building from there? I noticed that the dlls are all placed in the same folder as TorchSharp.dll, whereas VS seems to place them in subfolders extracted from the package.

Like this:

![image](https://user-images.githubusercontent.com/1791495/195191506-c343aa92-8c37-4d37-a8b3-c64b2c193760.png)


There's code in TorchSharp to explicitly load the backend DLLs, and it's aware of the folder structure. I would think that it's fine with a flat folder, too, since that's what happens when you build from source, but I'm not sure.

**Comment by NiklasGustafsson** [comment]
I have a slightly different driver for my 2080:

![image](https://user-images.githubusercontent.com/1791495/195192228-65bc4fdb-99cf-483c-b5f6-6dc61e2af5d4.png)

**Comment by benaclejames** [comment]
Very strange! Building from Visual Studio yields the same results! Though upon a fresh project created with visual studio in dotnet core, this works fine. Looks like I'll be recreating the project file 😆

**Comment by NiklasGustafsson** [comment]
That's fascinating. It'll be interesting to see what the project file differences are that could trigger this.

**Comment by NiklasGustafsson** [comment]
@benaclejames -- anything more to share on this, or should we close the issue?

**Comment by benaclejames** [comment]
My sincerest apologies for the delay, I've been looking into why this might have been happening but haven't found anything thus far. I'll be sure to let you know if anything changes. Thank you for your help!
