### ISSUE TITLE
`TorchSharp.csproj` refers Skia

### ISSUE THREAD

**Issue by kaiidams** [dotnet/TorchSharp#799]
Should this be referred by `TorchVision.cspros`?
 
https://github.com/dotnet/TorchSharp/blob/20b0fd210ca34c021eef9421a8bfdf173da6d419/src/TorchSharp/TorchSharp.csproj#L32

**Comment by NiklasGustafsson** [comment]
No. Apparently, I forgot to remove the dependency when I split TorchVision out.
