### ISSUE TITLE
TorchScript modules as dynamic objects

### ISSUE THREAD

**Issue by NiklasGustafsson** [dotnet/TorchSharp#812]
Modules that are loaded from a TorchScript file, or produced using torch.jit.compile, can have any number of methods and attributes, and invoking / accessing them needs to be done using methodology that looks a lot like .NET reflection:

```C#
string script = @"
def relu_script(a, b):
    return torch.relu(a + b)
def relu6_script(a, b):
    return torch.relu6(a + b)
def add_i(x: Tensor, i: int) -> Tensor:
    return x + i
def add_d(x: Tensor, i: float) -> Tensor:
    return x + i
def add_ii(x: int, i: int) -> Tuple[int,int]:
    return (x + i,x-i)
";

using var cu = torch.jit.compile(script);
var z = cu.invoke("relu_script", x, y);
```

If ScriptModule (returned by `torch.jit.load`) and CompilationUnit (returned by `torch.jit.compile`) were dynamic classes, the invocation could look like this:

```C#
using var cu = torch.jit.compile_dynamic(script); // or load_dynamic for a TorchScript saved in a file.
var z = cu.relu_script(x, y);
```

which is much closer to the Python experience.

Thoughts?

@dsyme, @kaiidams, @lostmsu, @MovGP0, @oluwandabira, @dayo05, @luisquintanilla, @GeorgeS2019?

**Comment by dayo05** [comment]
I think second way is more similar to the Python experience but, second way may or may not cause performance issue so is there any benchmark about that?

**Comment by kaiidams** [comment]
TorchScript is also meant for mobile platforms, If we want TorchSharp in such platforms, I am not sure how much dynamic is supported for Xamarin iOS and Android.

I guess dynamic `CompilationUnit` in C# needs to implement a method that is similar to `cu.invoke()` anyway, then the first way is good to start with.

**Comment by dayo05** [comment]
> TorchScript is also meant for mobile platforms, If we want TorchSharp in such platforms, I am not sure how much dynamic is supported for Xamarin iOS and Android.
> 
> I guess dynamic `CompilationUnit` in C# needs to implement a method that is similar to `cu.invoke()` anyway, then the first way is good to start with.

`dynamic` is supported on Android(it supports JIT) but in iOS, it doesn't(it doesn't supports JIT, I know about its caused by Apple's policy).
I've agree about implementation requires cu.invoke(). C# is implemented on moblie devices but Python is normally doesn't.

**Comment by NiklasGustafsson** [comment]
@kaiidams, @dayo05 -- thanks. I didn't think about the platform availability issue. That's a deal-breaker, IMO.
