### ISSUE TITLE
TensorStringStyle is ambiguous

### ISSUE THREAD

**Issue by kaiidams** [dotnet/TorchSharp#817]
I need `TorchSharp.TensorStringStyle.Julia` as there is `TorchSharp.torch.TensorStringStyle`.

C# compiler complains about ambiguous `TensorStringStyle`.

```cs
using TorchSharp;
using static TorchSharp.torch;
using System.IO;
using System.Runtime.InteropServices;

using Microsoft.DotNet.Interactive.Formatting;

var style = TensorStringStyle.Julia;

Formatter.SetPreferredMimeTypesFor(typeof(torch.Tensor), "text/plain");
Formatter.Register<torch.Tensor>((torch.Tensor x) => x.ToString(style, newLine: "\n"));
```

**Comment by kaiidams** [comment]
Seems that that the examples are updated with this change. https://github.com/dotnet/TorchSharpExamples/commit/ffdbaef2d03fe8ce914b46149b5980b5a32730ab

I think this issue can be closed if this change is intentional.

**Comment by NiklasGustafsson** [comment]
This change is intentional. There is also torch.julia and torch.numpy, in the pattern of torch.int16, etc.
