### ISSUE TITLE
how can I get tensor length 

### ISSUE THREAD

**Issue by ChengYen-Tang** [dotnet/TorchSharp#829]
Hi,
In python I can:
```
a is a Tensor
if (len(a) > 1):
    do something
```

How do I do this in C#

**Comment by NiklasGustafsson** [comment]
try t.numel()

**Comment by ChengYen-Tang** [comment]
Thanks, but I ended up using size(dim: 0)

```
>>> a = torch.randn(1, 2, 3, 4)
>>> a.numel()
24
>>> len(a)
1
>>> a.size()
torch.Size([1, 2, 3, 4])
>>> a.size(dim=0)
1
```

**Comment by NiklasGustafsson** [comment]
t.shape[0] works, too, if you're after the length of the batch (first) dimension. In both Python and .NET. I personally find that easier to read than size(0), but that's subjective.

**Comment by ChengYen-Tang** [comment]
Thank you for sharing
