### ISSUE TITLE
List is not supported

### ISSUE THREAD

**Issue by lijianxin520** [dotnet/TorchSharp#835]
![image](https://user-images.githubusercontent.com/47262889/200540329-a8a9d192-477d-411d-8a0e-0759a210a8c1.png)
![image](https://user-images.githubusercontent.com/47262889/200540425-5c073dac-2e04-4894-aaf5-87bbecf1e6c2.png)
Hello, could you tell me how to solve this error?

**Comment by NiklasGustafsson** [comment]
By calling `ToArray()` you're passing in an array of List<List<float>>. That is not supported -- you need to pass in an array of one of the fundamental numerical types (the valid element types of tensors).

Therefore, you'll need to either form a multi-dimensional array (different from array of arrays) or have a single-dimensional list with all elements and then reshape it to the shape you want.

**Comment by lijianxin520** [comment]
Thank you for your answer, but I can't directly convert from pytorch to torchsharp in many cases, which is a troublesome problem.

**Comment by NiklasGustafsson** [comment]
@lijianxin520 -- I'm sorry about that, but there are limitations to how far we can take the mimicking of Python in C#. Lists are so much more widely used in Python, and converting jagged arrays (or lists of lists) to tensors is expensive. The natural .NET data structure for multi-dimensional data with equal length rows and columns is a multi-dimensional array.

If you disagree, please submit a PR with additional APIs as you envision them. The current APIs require single-dimensional lists of numeric types, or multi-dimensional arrays, also of numeric types.

**Comment by lijianxin520** [comment]
Thank you for your answer. Thank you again! I am a loyal fan of csharp. I am currently learning nlp related technologies and want to show them through csharp.
