### ISSUE TITLE
Error with torch.jit: Expected all tensor to be on the same device, but found at least two devices, cuda:0 and cpu.

### ISSUE THREAD

**Issue by ilaykid** [dotnet/TorchSharp#840]
Hey,
I'm trying to load a transformer model that i exported from python as TorchScript. I want to run the model as cuda.
I turned the loaded model and the input to cuda with .cuda() method. I printed all device's parameters and it seems that everything is on cuda.
On prediction the model returning the error below:
Expected all tensor to be on the same device, but found at least two devices, cuda:0 and cpu.

Torchsharp version is 0.98.3
Exapmle Code:
```
model= torch.jit.load(modelPath, torch.CUDA);

model.eval();

long[] tokens = Tokenizer();

Tensor input= torch.from_array(tokens).unsqueeze(0).to(DeviceType.CUDA);

var pred = ((Tensor)model.forward(input)).data<float>();
```

**Comment by NiklasGustafsson** [comment]
Hmmm. I don't see anything wrong with the code, except that you're calling 'data<float>()' on what should be a CUDA:0 tensor. It has to be on the CPU to call it. However, the error message you're getting isn't consistent with that.

I'd need more details, and access to your TorchScript model file in order to troubleshoot. For example, what is the shape of the input tensor, and what is its element type (float32??)

**Comment by ilaykid** [comment]
Thank you!
The input shape is 1x32 and the type is int64.
If it matters the model is roberta_xlm.
The model works on cpu so i think that its something with the convertion

**Comment by NiklasGustafsson** [comment]
Yeah, don't close this... :-)

**Comment by NiklasGustafsson** [comment]
Can you point me at a TorchScript file?

**Comment by ilaykid** [comment]
Yeah that was mistake 😃
Its roberta xlm base from hugging face that i exported to TorchScript.
Im sorry but the model size is more than gb and it's on internal network so its hard to send it to you.
If its necessary i can try to build a copy in my private computer.
I printed every parameter in the model and its looks like they on cuda.

**Comment by NiklasGustafsson** [comment]
Can you try to insert a call to `cpu()` before the call to `data<float>()`

**Comment by ilaykid** [comment]
I'll try it when I can, but anyway I tried to separate the forward and data methods and the the exception was at forward. It didn't reached to .data

**Comment by NiklasGustafsson** [comment]
In that case, there's no point.

**Comment by NiklasGustafsson** [comment]
Do you get any kind of stack trace with the exception?

**Comment by NiklasGustafsson** [comment]
I looked at the code again. torch.jit.load() simply calls to C++:

```C#
var result = THSJIT_load(filename, (long)device_type, device_index);
if (result == IntPtr.Zero)
    CheckForErrors();
return result;
```

```C++
JITModule THSJIT_load(const char* filename, int64_t device, int64_t index)
{
    c10::DeviceType dev = c10::kCPU;
    if (device == 1)
        dev = c10::kCUDA;
 
    CATCH(
        auto res = torch::jit::load(filename, torch::Device(dev, index));
        auto copy = new torch::jit::Module(res);
        return new std::shared_ptr<torch::jit::Module>(copy);
    );

    return nullptr;
}
```

so this one really puzzles me. Can you see if any buffers (not parameters) are on CPU instead of CUDA?

**Comment by Hagaygur** [comment]
Chiming in here (I work with @ilaykid) , we'll get the relevant stacktrace once we're back at work next week.
As for as checks have gone, we've went through every possible method we could think of to make sure everything's on cuda:0 (Although, admittedly, haven't checked the buffers, will do with the stacktrace).
IIRC, the exception seems like it's coming from the Torch backend, not the TorchSharp front. 
The things we've tried thus far:
1. Exporting the model when it's on the GPU and not the cpu
2. Transferring the model and inputs to GPU in any way possible we could find (will give out a list next week)
3. Both print checking, asserting and debugging to try and notice anything that's on the CPU to no avail

Is there anyway to print which part is on the cpu precisely when catching this exception? It would help immensely in the debugging process. Should also be a worthwhile enhancement in general (as it's one of the most common bugs when executing a training loop in general) 

Just as an aside, TorchSharp is amazing with Torchscript support. Finally an end to our VRAM troubles in Python GC is in sight!

**Comment by NiklasGustafsson** [comment]
>> Is there anyway to print which part is on the cpu precisely when catching this exception?

That's what I'm **hoping** a stack trace will help determine.

It's complicated with a TorchScript module as opposed to a regular module, where you can just single-step the `forward()`.

**Comment by GeorgeS2019** [comment]
Just feedback the excitement that the newly implemented TorchScript has generated strong interest and a concrete use case where TorchSharp has a clear advantage. Appreciate more feedback.

**Comment by Hagaygur** [comment]
Hey, we've checked the buffers, which seem to be on the gpu as well.
Attaching the stacktrace, fastest method to export it out of the internal network was to retype it, so typos might be abound:

```
Traceback of TorchScript, serialized code (most recent call last):
	File "code/__torch__/___torch_mangle_2580.py", line 10, in forward
		  input_id: Tensor) -> Tensor:
		  model = self.model
		  return (model).forward(input_ids, )
			~~~~~~~~~~~~~~ <---HERE
	File "code/__torch__/transformers/models/xlm_roberta/modeling_xlm_roberta/__torch_mangle_2579.py", line 33, in forward
	 attention_mask()=torch.mul(torch.rsub(_8,1.), CONSTANTS.cl)
	 _9=(embeddings).forward(input_ids,input,)
	 _10=(encoder).forward(_9,attention_mask0,)
			~~~~~~~~~~~~~~~~ <---HERE
	return (pooler).forward(_10,)
    File "code/__torch__/transformers/models/roberta/modeling_roberta/___torch_mangle_2575.py", line 34, in forward
	 layer10=self.layer
	 _0=getattr(layer10,"0")
	 _12=(_0).forward(argument_1,attention_mask,)
			~~~~~~~~~~~<---HERE
	 _13=(_2).forward((_1).forward(_12,attention_mask,)attention_mask,)
	 _14=(_4).forward((_3).forward(_13,attention_mask,)attention_mask,)
	File "code/__torch__/transformers/models/roberta/modeling_roberta/___torch_mangle_2386.py", line 15, in forward
	 intermediate=self.intermediate
	 attention=self.attention
	 _0=(attention).forward(argument_1,attention_mask,)
			~~~~~~~~~~~~~~~~~~<---HERE
	 _1=(output).forward((intermediate).forward(_0,),_0,)
	 return _1
 	File "code/__torch__/transformers/models/roberta/modeling_roberta/___torch_mangle_2379.py", line 13, in forward
	 output=self.output
	 self0=self.self
	 _0=(self0).forward(argument_1,attention_mask,)
			~~~~~~~~~~~~~~<---HERE
	 return (output).forward(_0,argument_1,)
  	File "code/__torch__/transformers/models/roberta/modeling_roberta/___torch_mangle_2374.py", line 37, in forward
	 attention_scores=torch.matmul(query_layer,torch.transpose(key_layer,-1,-2))
	 attention_scores0=torch.div(attention_scores,CONSTANTS.c3)
	 input=torch.add(attention_scores0,attention_mask)
		~~~~~~~~~<---HERE
	 input0=torch.softmax(input,-1)
	 context_layer=torch.matmul((dropout).forward(input0,),value_layer)
	...
	...
	...
	...
	RuntimeError: Excepted all tensors to be on the same device, but found at least two devices,cuda:0 and cpu!
```

We've left out the TorchSharp parts as they were all either "slow_forward" or calling for external resources (and the typist's hands gotten sore) 


As for Torchscript usage, its incredibly important as far as we're concerned in order to bridge the gap between the community size of TorchSharp and the main platforms (TF, Pytorch, Mxnet) so we dont have to recode each model from scratch (some being extremely lengthy to code, which will always lead to dimensionality bugs).

As for why TorchSharp, basically, Python memory management of external resources pretty much sucks balls. Which leads to VRAM usage and it not being collected to be one of the most common issues on large models.

.Net on the other hand has amazing management of external resources with the dispose pattern. So no more errant "cuda out of memory" will occur for no reason hopefully.

**Comment by NiklasGustafsson** [comment]
@Hagaygur -- since Python exception traces start with the outermost layer, those "..." at the end may be significant... :-)

Anyway, if you trace the call chain, and without having the full stack, it seems that it's in the last matmul that the exception is happening.

However, since you're showing me a Python exception trace, I'm now officially confused -- is this what comes out from TorchScript when run from within .NET? I haven't actually seen a TorchScript stack trace before, so I don't know.

Also, if you run the exact same TorchScript model from Python, it works, right?

**Comment by NiklasGustafsson** [comment]
> So no more errant "cuda out of memory" will occur for no reason hopefully.

Well... While the dispose pattern is very nice for explicit memory management, and the NewDisposeScope construct helps make using it really easy, it's still quite easy to run out of CUDA memory... If you don't, then I'm envious of the hardware you have... :-)

**Comment by Hagaygur** [comment]
> @Hagaygur -- since Python exception traces start with the outermost layer, those "..." at the end may be significant... :-)
> 
> Anyway, if you trace the call chain, and without having the full stack, it seems that it's in the last matmul that the exception is happening.
> 
> However, since you're showing me a Python exception trace, I'm now officially confused -- is this what comes out from TorchScript when run from within .NET? I haven't actually seen a TorchScript stack trace before, so I don't know.
> 
> Also, if you run the exact same TorchScript model from Python, it works, right?

The exception IS coming from TorchSharp. It is the exact print of the stacktrace from the Exception object.
You have made me notice that we're getting exceptions later that are "originating" from the path which the model was exported from, which doesn't even exist in the environment it is running on.
Weirder still, it references .py files as if coming from python.
The docker it's running on doesn't even have python running.


As far as cusa oom, my meaning wasn't that we're not lacking gpu resources (we all are unfortunately), I meant that an extremely common problem is that Python is unable to reclaim unused resources on the GPU many times as it entirely lacks the proper management of external resources. We were forced to resort into manually deleting objects in Python and calling GC.Collect after each batch (on large models) when using Python and even that isn't perfect.
Will post the rest of the stacktrace soon

**Comment by ilaykid** [comment]
hey,
we exported the model again from scratch on CUDA and not on CPU, which worked for us. 
our old model works on CPU so we are still thinking that there is something with the conversion to CUDA that doesn't work well.
anyway for us the problem is solved. 
thank you for the support!
