### ISSUE TITLE
How to use register_forward_hook?

### ISSUE THREAD

**Issue by tondangerza** [dotnet/TorchSharp#842]
Hi,
I use resnet50 to classify images and I want use grad-cam to create heatmap 
to identify a defect but it must use a register_forward_hook and I not found this function
 What should I do?

**Comment by NiklasGustafsson** [comment]
Not supported at the moment. Now that an issue has been raised, it'll be on the backlog. If you want to, please implement and send us a PR! :-)

**Comment by NiklasGustafsson** [comment]
@tondangerza -- do you also need the pre-and full backward hooks?

**Comment by tondangerza** [comment]
> @tondangerza -- do you also need the pre-and full backward hooks?

Yes, could you possibly add backward hooks? 
because I don't want to use 2 systems (python & C#)

**Comment by NiklasGustafsson** [comment]
@tondangerza -- I haven't forgotten about this, but still trying to figure out the best way to hook methods calls in .NET. It's certainly possible to add pre-and-post-hooks manually to all forward() methods of built-in modules, and then ask users to add them also to their own forwards(). There is a precedent for this -- calling `RegisterComponents()` in the constructor of all custom modules, but I'd prefer something more transparent.

Also, it is necessary to also find an approach that works for ScriptModules, i.e TorchScript.

Any and all suggestions toward a solution are welcome...

**Comment by NiklasGustafsson** [comment]
Somebody suggested a pretty simple (but it would be a very breaking change) to make `forward()` non-virtual. 

Instead of overriding 'forward()' in custom modules, we would have a virtual or abstract method `ForwardImpl()` (or something like that) which would be where the logic of your module would be found.

So, in C# "pseudo-code":

```C#
public abstract class Module<T, TResult> : Module, IModule<T, TResult>
{
    protected Module(string name) : base(name) { }
    protected Module(IntPtr handle, IntPtr boxedHandle) : base(handle, boxedHandle) { }
    internal Module(HType handle, IntPtr? boxedHandle) : base(handle, boxedHandle) { }

    public TResult forward(T input1)
    {
        // call pre-hook if there is one.

        var res = ForwardImpl(input);

        // call post-hook if there is one.

        return res;
    }

    public abstract TResult forward_impl(T input1);
}
```

A custom module would override `forward_impl()` and call `forward()` on all sub-modules.

It's similar to how you defined `forward()` in PyTorch, but usually use `__call__()` to pass data to the module.

@MovGP0, @lostmsu, @kaiidams, @dayo05, @tondangerza, @luisquintanilla -- your thoughts?

**Comment by dayo05** [comment]
> Somebody suggested a pretty simple (but it would be a very breaking change) to make `forward()` non-virtual. 
> 
> Instead of overriding 'forward()' in custom modules, we would have a virtual or abstract method `ForwardImpl()` (or something like that) which would be where the logic of your module would be found.
> 
> So, in C# "pseudo-code":
> 
> ```C#
> public abstract class Module<T, TResult> : Module, IModule<T, TResult>
> {
>     protected Module(string name) : base(name) { }
>     protected Module(IntPtr handle, IntPtr boxedHandle) : base(handle, boxedHandle) { }
>     internal Module(HType handle, IntPtr? boxedHandle) : base(handle, boxedHandle) { }
> 
>     public TResult forward(T input1)
>     {
>         // call pre-hook if there is one.
> 
>         var res = forward_impl(input);
> 
>         // call post-hook if there is one.
> 
>         return res;
>     }
> 
>     public abstract TResult forward_impl(T input1);
> }
> ```
> 
> A custom module would override `forward_impl()` and call `forward()` on all sub-modules.
> 
> It's similar to how you defined `forward()` in PyTorch, but usually use `__call__()` to pass data to the module.
> 
> @MovGP0, @lostmsu, @kaiidams, @dayo05, @tondangerza, @luisquintanilla -- your thoughts?
> 
> Sometimes, I wish we had operator()() in C#...

I'm not sure it is able due I didn't tested it before but how about making able to cast to the delegate?

**Comment by NiklasGustafsson** [comment]
You have to explicitly cast, like

```C#

Func<Tensor,Tensor> r = Relu();
r(torch.randn(3,4));
```
But that's not convenient inside forward() implementations.

**Comment by NiklasGustafsson** [comment]
The least breaking change would be to introduce a new method that's not virtual, of course, which is the one to call from forward():


```C#
public abstract class Module<T, TResult> : Module, IModule<T, TResult>
{
    protected Module(string name) : base(name) { }
    protected Module(IntPtr handle, IntPtr boxedHandle) : base(handle, boxedHandle) { }
    internal Module(HType handle, IntPtr? boxedHandle) : base(handle, boxedHandle) { }

    public TResult call(T input1)
    {
        // call pre-hook if there is one.

        var res = forward(input);

        // call post-hook if there is one.

        return res;
    }

    public abstract TResult forward(T input1);
}
```

**Comment by kaiidams** [comment]
The latter example with `forward()` and `call()` looks better to me than the one with `forward_impl()` and `forward()`.

**Comment by MovGP0** [comment]
I am unsure if the `forward()` methods should be part of the `Module` class at all, or better implemented as a [fluent interface](https://dotnettutorials.net/lesson/fluent-interface-design-pattern/) utilizing extension methods. Also I wonder how merging and splitting would work:

```mermaid
flowchart TD
    A[Input]  --> AB
    B[Input] --> AB
    AB[Some Operation] --> ResA
    AB --> ResB
    ResA[Result]
    ResB[Result]
```
