### ISSUE TITLE
registered buffers are being ignored in move model to device

### ISSUE THREAD

**Issue by fwaris** [dotnet/TorchSharp#845]
https://github.com/dotnet/TorchSharp/blob/a360c6d141ad18572586b16f4bccae5e02387539/src/TorchSharp/NN/Module.cs#L166

The named_children() method does not include registered buffers. 

If the registered buffer is not also a 'field' of the module object then its not moved.

The buffer may be registered with a module (even though it is not a field) (e.g. TorchSharp.Fun library does that).

Please add the move for buffers that are not fields

**Comment by NiklasGustafsson** [comment]
@fwaris -- thank you for finding this. It amazes me that this issue has gone undetected for so long. There is no reason for the code to use reflection in the `_toEpilog()` logic, since the registered parameters and buffers is more general.

**Comment by Hagaygur** [comment]
Any chance this is related to our issue at #840 ?

**Comment by NiklasGustafsson** [comment]
I doubt it, since you're relying on TorchScript, where the 'to' functionality is implemented in the TorchScript runtime. _This_ bug affects buffers (and parameters) in a custom module that were properly registered, but not held in a field of the module class.

**Comment by fwaris** [comment]
@NiklasGustafsson thanks for making the updates. Give me day or two to go through the changes. I think parameters are in the same boat as buffers so that change may also be needed

**Comment by NiklasGustafsson** [comment]
@fwaris -- yes, parameters not held in fields are also facing the same problem. I made the same change for those, too.

**Comment by NiklasGustafsson** [comment]
>  Give me day or two to go through the changes. 

No need -- @tarekgh reviewed for me.
