### ISSUE TITLE
bug:  tensor.ToString(TorchSharp.TensorStringStyle.Numpy)

### ISSUE THREAD

**Issue by williamlzw** [dotnet/TorchSharp#851]
vision 0.99.0
var a = torch.tensor(new long[] { 100,200,300,400  }, new long[] {1,4});
a.print();
Console.WriteLine(a.ToString(TorchSharp.TensorStringStyle.Numpy));//bug
====================================
[1x4], type = Int64, device = cpu
 100 200 300 400

[[100 200 300 400]
 [100 200 300 400]]

**Comment by NiklasGustafsson** [comment]
Thanks for reporting! This bug should only affect tensors with dimensions of size '1'. I reproduced it and have a fix that will be in the next version.

**Comment by NiklasGustafsson** [comment]
https://github.com/dotnet/TorchSharp/pull/854
