### ISSUE TITLE
Can the Torch.Save support object?

### ISSUE THREAD

**Issue by ChengYen-Tang** [dotnet/TorchSharp#862]
Hi,
According to the official design, torch.save can save the object state.
Can TorchSharp support it?
https://pytorch.org/docs/stable/generated/torch.save.html

Because I need to save extra information.
https://github.com/DLR-RM/stable-baselines3/blob/f3abda5cbc9dab71fbda44d9feca7efd7bb09dfe/stable_baselines3/common/policies.py#L159

**Comment by ChengYen-Tang** [comment]
I know that because of the characteristics of C#, using Reflection to create instances will still encounter many problems.
Perhaps it is possible to design an interface that allows developers to choose which attributes need to be extracted

**Comment by NiklasGustafsson** [comment]
It cannot currently do so.

**Comment by ChengYen-Tang** [comment]
Will it be supported in the future?
Python has a [pickle function library](https://docs.python.org/3/library/pickle.html), which can easily save the state of the object
However, this seems to require support from the dotnet team. I think this feature is useful in the field of machine learning

**Comment by NiklasGustafsson** [comment]
General object serialization is hard in a language / runtime where you have to have the type implementation compiled, available, and discoverable, and cannot just reconstruct it at runtime as you can in some dynamic language runtimes. It's not a problem we will be solving within the scope of TorchSharp -- as you say, it's something the .NET runtime team would have to take on.

**Comment by NiklasGustafsson** [comment]
If you need to save additional state, I would go with any of several .NET serialization frameworks, and store that part of the state separately from the tensor state.

**Comment by Sprinzl** [comment]
> Hi, According to the official design, torch.save can save the object state. Can TorchSharp support it? https://pytorch.org/docs/stable/generated/torch.save.html
> 
> Because I need to save extra information. https://github.com/DLR-RM/stable-baselines3/blob/f3abda5cbc9dab71fbda44d9feca7efd7bb09dfe/stable_baselines3/common/policies.py#L159

You could use the System.Text.JSON.JsonConverter<T>  and when use public static void Save(this Tensor tensor, System.IO.BinaryWriter writer) as Nikolas explained. This would do the job of serialisation.

**Comment by Sprinzl** [comment]
This should do the trick now you can make a class with Tensors in the Parameters and serialize this as Json.

           var options = new System.Text.Json.JsonSerializerOptions();
            options.Converters.Add(new TensorConverter());
            var data = System.Text.Json.JsonSerializer.Serialize(this, options);

using System.Text.Json;
using static TorchSharp.torch;
using TorchSharp;
using System.IO;

namespace Docker.Visual
{
    public class JsonTensor 
    { 
            public long[] _shape { get; set; }
            public  ScalarType _type { get; set; }
            public byte[] data { get; set; }
            public bool requires_grad { get; set; }
            public string[] names { get; set; }
    }
 
    public class TensorConverter : System.Text.Json.Serialization.JsonConverter<Tensor>
    {

        public override Tensor Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var txt = reader.GetString();
            var jt = (JsonTensor) System.Text.Json.JsonSerializer.Deserialize(txt, typeof(JsonTensor));
            var tensor = torch.empty(jt._shape, dtype: jt._type, requires_grad: jt.requires_grad, names:jt.names);
            using (var s = new MemoryStream(jt.data))
            { tensor.Load(new BinaryReader(s));}
            return tensor;
        }

        public override void Write(Utf8JsonWriter writer, Tensor value, JsonSerializerOptions options)
        {
            using (var s = new MemoryStream()) 
            {
                using (var w = new BinaryWriter(s))
                { value.Save(w);}
                var jt =new JsonTensor() { data = s.ToArray(), _shape = value.shape, _type = value.dtype , names = value.names , requires_grad = value.requires_grad};
                var _o = new System.Text.Json.JsonSerializerOptions();
                var data = System.Text.Json.JsonSerializer.Serialize(jt, _o);
                writer.WriteStringValue(data);
            };
        }
    }
}

**Comment by NiklasGustafsson** [comment]
There's also a 'bytes' read/write property on Tensor that allows you to get the byte array of the Tensor. That's what the Tensor.Save()/Load() methods use for serialization.

**Comment by Sprinzl** [comment]
Ok Nicklas. Its updated.

**Comment by NiklasGustafsson** [comment]
Can the JsonConverter not take a Span<byte> as input? That's too bad, if that's the case, because the bytes.ToArray() call will make a copy.

**Comment by Sprinzl** [comment]
Niklas. Ok i cannot serialize pointers right now. Maybe Microsoft knows how to do this. :-) Some cloud based rent a pointer business model.

**Comment by NiklasGustafsson** [comment]
Fair enough. I guess the performance of serialization isn't super-critical, it's not likely something you do for every batch, for example. Probably no more than once every epoch.

**Comment by ChengYen-Tang** [comment]
> This should do the trick now you can make a class with tensors in the parameters and serialize this as Json.
> 
> ` public class JsonTensor { public long[] _shape { get; set; } public ScalarType _type { get; set; } public byte[] data { get; set; } public bool requires_grad { get; set; } public string[] names { get; set; } }
> 
> ```
> public class TensorConverter : System.Text.Json.Serialization.JsonConverter<Tensor>
> {
> 
>     public override Tensor Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
>     {
>         var txt = reader.GetString();
>         var jt = (JsonTensor) System.Text.Json.JsonSerializer.Deserialize(txt, typeof(JsonTensor));
>         var tensor = torch.empty(jt._shape, dtype: jt._type, requires_grad: jt.requires_grad, names:jt.names);
>         tensor.bytes = jt.data;
>         return tensor;
>     }
> 
>     public override void Write(Utf8JsonWriter writer, Tensor value, JsonSerializerOptions options)
>     {
>             var jt =new JsonTensor() { data = value.bytes.ToArray(), _shape = value.shape, _type = value.dtype , names = value.names , requires_grad = value.requires_grad};
>             var _o = new System.Text.Json.JsonSerializerOptions();
>             var data = System.Text.Json.JsonSerializer.Serialize(jt, _o);
>             writer.WriteStringValue(data);
>     }
> }`
> ```

If the property in the object is still an object. Then defines him as the parent class when writing the code.

**Comment by Sprinzl** [comment]
Ok I maybe do not get the question. But now you can write something like this:

`
public string Serialize() 
        {
            var options = new System.Text.Json.JsonSerializerOptions();
            options.Converters.Add(new TensorConverter());
            var data = System.Text.Json.JsonSerializer.Serialize(this, options);
            return data;
        }

        public IVisual Deserialize(string json) 
        {
            var options = new System.Text.Json.JsonSerializerOptions();
            options.Converters.Add(new TensorConverter());
            return (IVisual)System.Text.Json.JsonSerializer.Deserialize(json, this.GetType(), options);
        }
`

**Comment by ChengYen-Tang** [comment]
@NiklasGustafsson @Sprinzl,
I think BinaryFormatter is the most suitable for my needs, he is very close to python's pickle, but he seems to be deprecated.

https://learn.microsoft.com/zh-tw/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter?view=net-7.0
https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md

**Comment by ChengYen-Tang** [comment]
Hi @NiklasGustafsson,
I have my code serializable by system.text.json, but I need to pass JsonSerializerOptions to JsonSerializer.Serialize and JsonSerializer.Deserialize.

**Comment by NiklasGustafsson** [comment]
If you are using JSON (including BSON), I would suggest using the Newtonsoft,Json package: https://www.nuget.org/packages/Newtonsoft.Json

**Comment by ChengYen-Tang** [comment]
Why use Newtonsoft instead of system.text.json

**Comment by ChengYen-Tang** [comment]
Hi @NiklasGustafsson,
My code supports serialization using newtonsoft. But I need to pass JsonSerializerSettings to JsonSerializer.

```
        Newtonsoft.Json.JsonSerializer jsonSerializer = Newtonsoft.Json.JsonSerializer.Create(newtonsoftSerializerOptions);
        using MemoryStream ms = new();
        using BsonDataWriter writer = new(ms);
        jsonSerializer.Serialize(writer, space);
        ms.Position = 0;
        using BsonDataReader reader = new(ms);
        Box? box = jsonSerializer.Deserialize<Space>(reader) as Box;
```

**Comment by Sprinzl** [comment]
> Hi @NiklasGustafsson, My code supports serialization using newtonsoft. But I need to pass JsonSerializerSettings to JsonSerializer. Thank you.
> 
> ```
> Newtonsoft.Json.JsonSerializer jsonSerializer = Newtonsoft.Json.JsonSerializer.Create(newtonsoftSerializerOptions);
> using MemoryStream ms = new();
> using BsonDataWriter writer = new(ms);
> jsonSerializer.Serialize(writer, space);
> ms.Position = 0;
> using BsonDataReader reader = new(ms);
> Box? box = jsonSerializer.Deserialize<Space>(reader) as Box;
> ```
> 
> `BsonDataWriter and BsonDataReader ` moved to https://www.nuget.org/packages/Newtonsoft.Json.Bson/1.0.2

Ok just have a helper with an extension and you have no problem with always rewrite.

public static void Write(this string path, object object) ….

public static string Local(this string path)…


Now you can write @“Data/xxx.json”.Local().Write(object)

This is as simple as it gets.

**Comment by ChengYen-Tang** [comment]
What does it mean?
> you have no problem with always rewrite.

**Comment by ChengYen-Tang** [comment]
Umm...
I still prefer BinaryFormatter, not all objects can be quickly serialized using Newtonsoft.Json
