### ISSUE TITLE
Save as Stream

### ISSUE THREAD

**Issue by Sprinzl** [dotnet/TorchSharp#864]
Hello,
I want to use memory mapped files mechanics. Is where any possibility to serialize a Tensor without using the harddrive? Json/XML....

**Comment by NiklasGustafsson** [comment]
You should be able to serialize to any BinaryStream instance.

**Comment by NiklasGustafsson** [comment]
In TensorExtensionMethods.cs, line 248:

```C#
public static void Save(this Tensor tensor, System.IO.BinaryWriter writer)
```

**Comment by Sprinzl** [comment]
> In TensorExtensionMethods.cs, line 248:
> 
> ```cs
> public static void Save(this Tensor tensor, System.IO.BinaryWriter writer)
> ```

I used this but I get an reflection error of some assembly’s missing.

**Comment by Sprinzl** [comment]
Thanks for the fast message.

**Comment by NiklasGustafsson** [comment]
Can this be closed?
