### ISSUE TITLE
Feature suggestion: How to get the submodel of Sequential from the index.

### ISSUE THREAD

**Issue by williamlzw** [dotnet/TorchSharp#869]
How to get the submodel of Sequential from the index.

        class testclass(nn.Module):
            def __init__(self):
                super(testclass, self).__init__()
                layers = []
                layers.append(nn.Conv2d(3, 6, 3))
                layers.append(nn.Conv2d(3, 1, 1))
                self.features = nn.Sequential(*layers)
        
            def forward(self, x):
                out_feats = []
                x1 = self.features[0](x) # torchsharp not support?
                out_feats.append(x1)
                x2 = self.features[1](x) # torchsharp not support?
                out_feats.append(x2)
                return out_feats

**Comment by williamlzw** [comment]
ModuleList can temporarily solve this problem.

**Comment by SteveJSteiner** [comment]
Thank you for the temporary workaround!  
[NiklasGustafsson](https://github.com/NiklasGustafsson) asked me to keep an eye out and at minimum let contributors know he is away until early next year.
