### ISSUE TITLE
torch.nn.parameter.is_lazy() missing

### ISSUE THREAD

**Issue by xhuan8** [dotnet/TorchSharp#871]
Is it necessary or not?

**Comment by SteveJSteiner** [comment]
Hi xhuan8.   [NiklasGustafsson](https://github.com/NiklasGustafsson) will be back early January.  If other community members don't jump in sooner this will get attention when he is back.

**Comment by xhuan8** [comment]
@SteveJSteiner thanks, got it.

**Comment by NiklasGustafsson** [comment]
I don't actually think we support lazy parameters at this point, so it should always be returning false...
