### ISSUE TITLE
Compiler error CS0121

### ISSUE THREAD

**Issue by williamlzw** [dotnet/TorchSharp#882]
Padding: 0, triggering error
=======================

public class BasicBlock : Module<Tensor, Tensor>
    {
        private readonly Conv2d conv1;
        public BasicBlock(long inplanes, List<long> planes) : base(
            "BasicBlock")
        {
            long plane = planes[0];
            conv1 = Conv2d(inputChannel: inplanes, outputChannel: plane, kernelSize:1, stride: 1, padding: 0, dilation:1, bias: false, groups:1);
            RegisterComponents();
        }

      public override Tensor forward(Tensor input)
        {
            return input;
        }
    }

**Comment by NiklasGustafsson** [comment]
If you use '0L' instead of '0' in the padding argument, it works. The problem is that 'padding' takes a long, so since there's an implicit conversion from int -> long, it's ambiguous against another overload.

**Comment by williamlzw** [comment]
Thank you.
