### ISSUE TITLE
TorchSharp:How do I slice layers of the Sequential by index?

### ISSUE THREAD

**Issue by williamlzw** [dotnet/TorchSharp#883]
https://github.com/bubbliiiing/yolo3-pytorch/blob/master/nets/yolo.py
line 77
line 78

  last_layer1            = make_last_layers([512, 1024], out_filters[-1], len(anchors_mask[0]) * (num_classes + 5))
   out0_branch = last_layer1\[:5\](x0)#How do I slice layers of the Sequential by index
   out0        = last_layer1\[5:\](out0_branch)#How do I slice layers of the Sequential by index

**Comment by NiklasGustafsson** [comment]
Huh!

I was just about to make a release with indexing into Sequential implemented. Obviously, more work is needed... :-)

**Comment by williamlzw** [comment]
Very good.Thank you.

**Comment by williamlzw** [comment]
There is a suggestion: When Sequential supports slicing, the weight key name of the layer should not be changed to facilitate the conversion of pytorch weights to torchsharp.

**Comment by NiklasGustafsson** [comment]
It definitely will preserve the names of the modules, which should preserve the names of the parameters and buffers, which is what you need for loading tensors.
