### ISSUE TITLE
Enhance performance with CUDA by exposing allow_tf32 properties 

### ISSUE THREAD

**Issue by dje-dev** [dotnet/TorchSharp#889]
In April of 2022 it was announced:  "Update: in consultation with our colleagues at NVIDIA we will be changing the default value of torch.backends.matmul.allow_tf32 to False." https://dev-discuss.pytorch.org/t/pytorch-and-tensorfloat32/504''

The result is much slower TorchSharp performance with CUDA for many common GPUs. 

It would be desirable to be able to enable these in code:
  torch.backends.cuda.matmul.allow_tf32 = True
  torch.backends.cudnn.allow_tf32 = True
but this does not currently appear possible in Torchsharp.

As a workaround, I have recovered the speedup (of 2.15x on a medium sized transformer model) by using this line at the beginning of the program:
  Environment.SetEnvironmentVariable("NVIDIA_TF32_OVERRIDE", "1");

**Comment by NiklasGustafsson** [comment]
@dje-dev -- that you for noticing this announcement. I will look into how to do this in native code, since that's all we have to play with here. TorchSharp is just a thin layer on top of libtorch.

**Comment by NiklasGustafsson** [comment]
I found these in the `at` namespace:
```C++
  bool allowTF32CuDNN() const;
  void setAllowTF32CuDNN(bool);
  bool allowTF32CuBLAS() const;
  void setAllowTF32CuBLAS(bool);
```

Presumably, `setAllowTF32CuDNN` corresponds to `torch.backends.cudnn.allow_tf32 = ...` and `setAllowCuBLAS()` corresponds to `torch.backends.cuda.allow_tf32 = ...`.
