### ISSUE TITLE
SelfOrganizingMap too slow

### ISSUE THREAD

**Issue by Sprinzl** [dotnet/TorchSharp#894]
Hello, 
my SOM is too slow. Maybe someone can help. I think I have to get rid of the grid and make it two dimensions not three and when do some fancy recalc of the psoitions. This would enable braodcasting. I also think we need a better public base for code examples. MatchingNeighbors needs to be optimzed....

 public class SelfOrganizingMap: torch.nn.Module<torch.Tensor, torch.Tensor>
    {
        public Tensor Grid;
      
        public SelfOrganizingMap(int size, int depth):base(nameof(SelfOrganizingMap)) 
        { 
            Grid = torch.empty(new long[] { size, size, depth });
            this.register_buffer("Grid", Grid);
        }
        public long Width => Grid.size(0);
        public long Height => Grid.size(1);
        public long Depth => Grid.size(2);

        public Tensor this[int x, int y]
        { get { return Grid[x, y, ..]; } set { Grid[x, y, ..] = value; } }

        public virtual void Train(Tensor x)
        {
          
            Initialize(x);
            const double slr = 0.02;
            const int cycles = 100;
            double lat = Math.Max(this.Width, this.Height) / 2;
            double tim = cycles / Math.Log(lat);
            int ix = 0;
            double lr = slr;
            while (ix < cycles)
            {
                double nr = lat * Math.Exp(-ix / tim);
                double nd = nr * 2;
                for (int iy = 0; iy < x.size(0); iy++)
                { MatchingNeighbors(x[iy, ..], nd, nr, nr * nr, lr); }
                ix++;
                lr = slr * Math.Exp(-(double)ix / cycles);
            }
        }

        public void Initialize(Tensor x)
        {
            var min = x.min().sum();
            var max = x.max().sum();
            var div = max - min;
            Grid = (torch.rand(Width, Width, Depth,device:Grid.device) * div) + min;
        }

        public double DistanceToSquared((int x, int y) A, (int x, int y) B)
        {
            int dx = A.x - B.x;
            int dy = A.y - B.y;
            return (dx * dx) + (dy * dy);
        }

        private void MatchingNeighbors(Tensor vector, double dia, double radius, double s, double lr)
        {
            var match = this.Match(vector);
            int sx = (int)Math.Max(0, match.x - radius - 1);
            int sy = (int)Math.Max(0, match.y - radius - 1);
            int ex = (int)Math.Min(Width, sx + dia + 1);
            int ey = (int)Math.Min(Height, sy + dia + 1);

            for (int x = sx; x < ex; x++)
            {
                for (int y = sy; y < ey; y++)
                {
                    double dq = this.DistanceToSquared(match, (x, y));
                    if (dq <= s) { this.AdjustWeights(vector, lr, Math.Exp(-dq / (2 * s)), x, y); }
                }
            }
        }

        public void AdjustWeights(Tensor i, double lr, double df, int x, int y)
        {
            double lrf = lr * df;
            var wi = Grid[x, y, ..];
            Grid[x, y, ..] = wi + (lrf * (i[..] - wi));
        }

        public (int x, int y) Match(Tensor i)
        {
            var f = Grid.reshape(Width * Height, Depth);
            var x = (double)(int)(f - i).pow(2.0).sum(1).argmin() / (double)Width;
            var y = (x - Math.Floor(x)) * Height;
            x = Math.Floor(x);
            return ((int)x, (int)y); ;
        }

        public override Tensor forward(Tensor i)
        {return torch.tensor(Match(i), device: Grid.device);}

        [WpfType(typeof(Grid))]
        public static void Test() 
        {
            var wpf ="".GetWpf<Grid>();
            var som = new SelfOrganizingMap(100, 3).to("Cuda");
            var trainingdata = torch.randint(0, 256, new int[] { 200, 3 }).to(ScalarType.Float32).to("Cuda");
            som.Train(trainingdata);
            wpf.Children.Add(som.Grid.ToImage());

        }
    }
}
Thanks in advance.

**Comment by NiklasGustafsson** [comment]
Hello @Sprinzl,

I'm not sure what your specific ask is on this one. Is there a performance bug you have identified?

**Comment by Sprinzl** [comment]
> Hello @Sprinzl,
> 
> I'm not sure what your specific ask is on this one. Is there a performance bug you have identified?

Ok I it is hell of slow in comparison with non tensor version. What I am looking for in MatchingNeighbors is to get rid of the loops. If I do [50,3] against [400,3] is where any method to do some lambda to match it and get the index value. I saw something like this long time ago in python

**Comment by NiklasGustafsson** [comment]
So, if I understand correctly, you are looking for help parallelizing your code? I don't know what the right forum for that is, but I suspect that you will find a broader audience of programmers who know how to help elsewhere, maybe on StackOverflow, or maybe someone can help you on the TorchSharp gitter site: https://gitter.im/dotnet/TorchSharp

**Comment by Sprinzl** [comment]
Exactly this is what I needed

**Comment by NiklasGustafsson** [comment]
Okay. I'll leave this issue open and let you close it when you see fit. I don't expect that you will find a solution here, so I encourage you to try other forums, but I won't close the issue.

Niklas

**Comment by Sprinzl** [comment]
> Okay. I'll leave this issue open and let you close it when you see fit. I don't expect that you will find a solution here, so I encourage you to try other forums, but I won't close the issue.
> 
> Niklas

Thanks Nicklas,
I think the hole topic with ranges in combination with this library is quite difficult to get help. Where is not much out in the wild. I think some kind of special forum would really help. I know what Rhino3d got a rally boost by providing specialised forums. And I think this is an important thing to have. I try to dig though the python jungle of dependencies and maybe I find a solution

**Comment by NiklasGustafsson** [comment]
Data parallelism is fundamentally hard. 

Most of the time, it far from obvious how to do it, and sometimes it requires algorithms that, at face value, do more than the sequential version, but given the accelerator HW, is still more efficient. In other words, even if the number of operations is 2x, or even 10x more than the serial version, if the HW is 100x faster for a data-parallel version of the algorithm, you win.

Please, do come back here if/when you find a solution and share it with the rest of us.

**Comment by MovGP0** [comment]
making the code parallel is often times slowing it down, because of the overhead of creating the threads, distributing the data to be calculated, and synchronizing the results. So in most cases it's not worth the additional work, because you need to have the serial code for smaller arrays/tensors anyway. This not only means more work, but also provides more potential for introducing bugs into your code.

There are usually some optimizations to be done before making code parallel, like reducing the number of type castings (ie. from `int` to `double` and back), or use more efficient data types (ie. `float` instead of `double`).

However, when the size of the array/tensor becomes really large, [Parallel.For](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.parallel.for) might be an relatively easy way to parallelize the outer `for` loops. 

In any case, always do the following things:
- to performance testing (ie. using [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet))
- cover everything in unit tests
- use a profiler (ie. using [dotTrace](https://www.jetbrains.com/de-de/profiler/)) to determine which part of the code an benefit from optimizations

**Comment by GeorgeS2019** [comment]
this [Self Organizing PyTorch use case](https://github.com/bougui505/quicksom) suggests that using [another backend](https://jax.readthedocs.io/en/latest/) provides 2x better performance

**Comment by MovGP0** [comment]
another idea would be to eliminate the for loops completely and use appropriate tensor operations instead.

**Comment by NiklasGustafsson** [comment]
> I am not shure but float32 must be equal to double which is default in pytorch

No, float32 is a 32-bit float, i.e. 'single' in many languages.

**Comment by NiklasGustafsson** [comment]
@Sprinzl -- is this a bug or a topic that belongs under the Discussion tab? Converting an issue to a discussion thread is straight-forward, just look for the 'Convert to discussion' link in the right sidebar above.
