### ISSUE TITLE
Possible convergence regression between v 0.99.1 and v 0.99.2

### ISSUE THREAD

**Issue by dje-dev** [dotnet/TorchSharp#896]
I find the convergence rate varies significantly between these two versions for a custom transformer network of medium size. At 2mm samples the loss is 3.75 with 0.99.1 versus 3.86 using 0.99.2.

Several times I have verified this, merely changing the .csproj reference between these two versions, and see exactly repeatable results as mentioned above.  Using 0.99.2, the lower level of loss (3.75) is only attained after 3mm samples (another 50% of training samples). This is true both on Windows and Linux.

Is there some unit test in TorchSharp which compares convergence rates between different versions as a regression test (for at least one network)? If so and it seems to pass then I'm happy to investigate this further on my end (though not sure exactly how).

**Comment by dje-dev** [comment]
One additional datapoint that might provide a hint. The training rate increases by 20% just by moving project reference from 0.99.1 to 0.99.2. Is it expected that the changes in this later version would induce such a change?

**Comment by NiklasGustafsson** [comment]
Do you mean that the training time increased by 20%?

No, nothing should have changed that way. The underlying libtorch version is identical, and there is very little in the .NET layer, actually. There were some changes to the optimizers, but the change was to add a 'maximize' mode, which shouldn't have impacted the convergence of existing code. Which optimizer and LR scheduler are you using (assuming that you are using an LR scheduler).

**Comment by dje-dev** [comment]
I retract the concern that convergence was inferior with this version. Torchsharp is working well.
I do see some unexplained variability in runtime, but this is probably unrelated to Torchsharp versions.
