### ISSUE TITLE
How to load the trained model？

### ISSUE THREAD

**Issue by lindadamama** [dotnet/TorchSharp#902]
I've been training the model in Python for hours，How to load the trained model？

**Comment by NiklasGustafsson** [comment]
See: 

https://github.com/dotnet/TorchSharp/wiki/Sharing-Model-Data-between-PyTorch-and-TorchSharp

and 

https://github.com/dotnet/TorchSharp/wiki/TorchScript

**Comment by NiklasGustafsson** [comment]
@lindadamama -- can we close this issue?

**Comment by lindadamama** [comment]
OK, no problem. Thank you for your help
