### ISSUE TITLE
ToString representation of objects

### ISSUE THREAD

**Issue by whb07** [dotnet/TorchSharp#905]
I just began playing around with the library on both Jupyter  and regular console to find the visual string representation do one of the following:
![image](https://user-images.githubusercontent.com/15861355/216794228-bc8f15d1-5b5b-4044-9eff-770586090fb7.png)

![image](https://user-images.githubusercontent.com/15861355/216794274-4b1510b9-d843-4ba9-a057-cde489f45670.png)

What's the recommended way to visually inspect objects or is this not a feature that's been implemented yet?

Seems the way forward would be to allow newcomers the same experience as one would have with Python/Pytorch rather than what it is now..closer to the C++ side.

Or am I missing something (most likely the case)?

Thanks!

**Comment by whb07** [comment]
For better context here is the Python side:

![image](https://user-images.githubusercontent.com/15861355/216794357-19c5980b-1432-411a-bcfc-6137d5f1304a.png)

**Comment by NiklasGustafsson** [comment]
There are instructions on how to get notebooks to show tensors properly at https://github.com/dotnet/TorchSharpExamples/tree/main/tutorials.

**Comment by NiklasGustafsson** [comment]
@whb07 -- please close the issue if you determine that the tutorials above address your question. If not, please let me know how I can improve the tutorials.

**Comment by ChengYen-Tang** [comment]
Actually, I had the same problem before.

![image](https://user-images.githubusercontent.com/32535494/217139537-25c54429-ba1f-4d70-b110-6057ad634e8f.png)

**Comment by NiklasGustafsson** [comment]
> Actually, I had the same problem before.
> 
> ![image](https://user-images.githubusercontent.com/32535494/217139537-25c54429-ba1f-4d70-b110-6057ad634e8f.png)

This is exactly what the instructions in the tutorials are meant for.

**Comment by NiklasGustafsson** [comment]
@whb07 -- can we close this one? If I haven't answered the question, please let me know what remains to be answered.

**Comment by ChengYen-Tang** [comment]
@NiklasGustafsson ,

https://github.com/marketplace/actions/close-stale-issues

**Comment by MovGP0** [comment]
When I understand this correctly, what is missing here is the [DebuggerDisplayAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debuggerdisplayattribute) and related attributes on the most important classes.

**References**
- [Enhancing Debugging with the Debugger Display Attributes](https://learn.microsoft.com/en-us/dotnet/framework/debug-trace-profile/enhancing-debugging-with-the-debugger-display-attributes)
