### ISSUE TITLE
How to save the model trained with torchsharp as a TorchScript module?

### ISSUE THREAD

**Issue by lindadamama** [dotnet/TorchSharp#909]
How to save the model trained with torchsharp as a TorchScript module?
python code：
```python
m = MyModule()
m = torch.jit.script(m)
m.save("exported.method.dat")
```
Does torchsharp have similar functions?
How to convert Module<Tensor, Tensor> to ScriptModule and Save it？

**Comment by NiklasGustafsson** [comment]
See: https://github.com/dotnet/TorchSharp/wiki/TorchScript

TorchScript models can currently only be created from Python. Once you have the script file, however, you can load it in TorchSharp, continue training it, save it, or use it for inference, etc.
