### ISSUE TITLE
How can I quickly convert a Tensor to a byte array?

### ISSUE THREAD

**Issue by lindadamama** [dotnet/TorchSharp#911]
<img width="418" alt="image" src="https://user-images.githubusercontent.com/48863486/218301941-9e463804-b3ed-449e-872a-67a490304dc1.png">
I tried to use the for loop and found it very time-consuming，
The inference time of neural network is 5ms, but it takes 300ms for Tensor to turn to Arry
Tensor.shape=[320,256]
<img width="983" alt="image" src="https://user-images.githubusercontent.com/48863486/218305076-35a5dfcc-82a2-434e-a5ed-0344dd0cf517.png">
I asked CHATGPT, but it didn't solve the problem. Visual studio prompts that there is no such API

python实现方法：

```python
array1=tensor2.numpy()
```

**Comment by lindadamama** [comment]
<img width="497" alt="image" src="https://user-images.githubusercontent.com/48863486/218324137-85b4cefe-8625-47a0-96d0-bd9f995c42a1.png">
The reasoning time is reduced from 300 ms to 40 ms

**Comment by NiklasGustafsson** [comment]
Be careful with `bytes` -- it will point to native memory and is a very low-level API. If the array element type you want corresponds to the tensor's element type, you should use `a.data<T>()`, instead of `a.bytes`. It's safer and does a validation of the underlying element type.

**Comment by NiklasGustafsson** [comment]
> I asked CHATGPT, but it didn't solve the problem. Visual studio prompts that there is no such API
> python实现方法：

ChatGPT hasn't seen much TorchSharp code, so don't rely on it for advice. Take a look at our tutorials at dotnet/TorchSharpExamples
