### ISSUE TITLE
nn.Module  save and state_ dict method error

### ISSUE THREAD

**Issue by toolgood** [dotnet/TorchSharp#912]
nn.Module  save and state_ dict method error

``` cs

    internal partial class Program
    {
        static void Main(string[] args)
        {
            var test = new Test(2);
            Dictionary<string, Tensor> sd = test.state_dict(); // No layer2.modules keyword

            test.save("1.pth");
        }
    }

    public class Test : nn.Module
    {
        public nn.Module layer;
        public nn.Module layer2;

        public Test(int layernum) : base("Test")
        {
            layer = nn.Linear(16, 2);
            layer2 = new Test2((from l in Enumerable.Range(0, layernum)
                                select new Test3()).ToArray(),
                                (from l in Enumerable.Range(0, layernum)
                                select new Test3()).ToArray());
            this.RegisterComponents();
        }
    }
    public class Test2 : nn.Module
    {
        public ModuleList<Test3> modules;
        public ModuleList<nn.Module> modules2;
        public nn.Module layer;
        public Test2(Test3[] ms, nn.Module[] ms2) : base("Test2")
        {
            layer = nn.Linear(16, 2);
            modules = nn.ModuleList(ms);
            modules2 = nn.ModuleList(ms2);
            this.RegisterComponents();
        }
    }
    public class Test3 : nn.Module
    {
        public nn.Module layer;
        public Test3( ) : base("Test3")
        {
            layer = nn.Linear(16, 2);
            this.RegisterComponents();
        }
    }

```

**Comment by GeorgeS2019** [comment]
@toolgood 

##### Minor feedback
Some of the [discussions ](https://stackoverflow.com/questions/59095824/what-is-the-difference-between-pt-pth-and-pwf-extentions-in-pytorch)involving the choice of extensions "pth", "pt"

Typically in TorchSharp, saving state_dict, the extension "dat" is used. This format seems to be specific only to TorchSharp AFAIK, I could be wrong, not transferable to pytorch, unless further transformation.

**Comment by toolgood** [comment]
Error getting parameters,

Test2 class
public ModuleList<nn.Module> modules2;  Registered
public ModuleList<Test3> modules;           Not registered

**Comment by toolgood** [comment]
> Interesting, thanks for the repro. What happens if you declare `Test2.modules` as a ModuleList<nn.Module>, instead?

 Yes, it is normal to declare to ModuleList<nn. Module> 

Test2 class
public ModuleList<nn.Module> modules2; Registered
public ModuleList modules; Not registered

**Comment by NiklasGustafsson** [comment]
Found it. The fix will be in next release. In the meantime, declare the `ModuleList<T>` with `T = nn.Module` instead.
