### ISSUE TITLE
conv = nn.Conv2d(c1, 1, 1, bias=False).requires_grad_(False)

### ISSUE THREAD

**Issue by williamlzw** [dotnet/TorchSharp#913]
conv = nn.Conv2d(c1, 1, 1, bias=False).requires_grad_(False) 
self.conv.weight.data[:] = nn.Parameter(x.view(1, c1, 1, 1))

https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/modules.py
line73
requires_grad_(False) ? not support in torchsharp.
conv.weight.data[:] = nn.Parameter(x.view(1, c1, 1, 1))

**Comment by NiklasGustafsson** [comment]
Thanks for reporting the issue. It's been implemented incorrectly (easy fix):

```C#
            public Tensor requires_grad_(bool requires_grad = true)
            {
                this.requires_grad = true;
                return this;
            }
```

In the meantime, use `with_requires_grad()` or set the `requires_grad` property directly.
