### ISSUE TITLE
I have an idea. Can we train a new model by directly loading scriptmodule without writing the class library of the model?

### ISSUE THREAD

**Issue by lindadamama** [dotnet/TorchSharp#916]

**Comment by lindadamama** [comment]
Don't know whether it is feasible?

**Comment by NiklasGustafsson** [comment]
Yes, that works. You will need to call `train()` on the module after loading it, and then you can save it again, after training, which will update the TorchScript file.

ScriptModule in TorchSharp has the same limitations as it does in PyTorch. The only thing that doesn't work in TorchSharp is creating a scriptmodule from scratch -- you have to first export it from Python.

**Comment by NiklasGustafsson** [comment]
@lindadamama -- did this answer your question?

**Comment by lindadamama** [comment]
I got a positive answer from you. I feel this answer is very good. Now I am ready to find a project to test, Thanks
