### ISSUE TITLE
`torch.from_file` is missing

### ISSUE THREAD

**Issue by lostmsu** [dotnet/TorchSharp#917]
See [torch::from_file](https://pytorch.org/cppdocs/api/function_namespacetorch_1ada2922b5ce8ffb447c0b105895c04196.html).

It is useful for working with large file-backed tensors.

**Comment by NiklasGustafsson** [comment]
I find the PyTorch documentation on `from_file` somewhat less than fully illuminating. What does the underlying file look like and who creates it?

**Comment by lostmsu** [comment]
It is a memory-mapped view into a file.

**Comment by NiklasGustafsson** [comment]
Does it get created if it doesn't exist?

**Comment by lostmsu** [comment]
Never tried TBH. I usually use it to transparently load large input datasets and/or parameter tensors in read-only mode.

**Comment by NiklasGustafsson** [comment]
Can you attach a Python snippet exemplifying? 

The C++ function returns an at::Tensor, while the Python API returns a Storage object.

**Comment by lostmsu** [comment]
![image](https://user-images.githubusercontent.com/239520/219175385-13f4b112-7fb3-49fb-8dad-965d743c373e.png)

AFAIK, Python API also returns a `Tensor`

**Comment by NiklasGustafsson** [comment]
The only Python `from_file()` I can find in the PyTorch docs are these ones: 

https://pytorch.org/docs/stable/storage.html?highlight=from_file#torch.TypedStorage.from_file
https://pytorch.org/docs/stable/storage.html?highlight=from_file#torch.UntypedStorage.from_file

**Comment by lostmsu** [comment]
Perhaps it is not fully supported or they somehow missed it in the docs. It is present in `torch/_C/_VariableFunctions.pyi` in my PyTorch installation, and my IDE can see its signature (see above).

**Comment by NiklasGustafsson** [comment]
Alright. That's the one I'll implement, then, not the documented *Storage.from_file().

**Comment by NiklasGustafsson** [comment]
@lostmsu  -- from_file is available in 0.99.3, which is available on NuGet now.
