### ISSUE TITLE
Torch.meshgrid often reports errors

### ISSUE THREAD

**Issue by williamlzw** [dotnet/TorchSharp#922]
Sometimes the predictions are right, and sometimes they are wrong.
How to ensure that torch.mesh parameters are in the same memory area?

Try running the following code several times in succession:
List<torch.Tensor> mesh = new List<torch.Tensor>();
int outputH = 128;
int outputW = 128;
mesh.Add(torch.arange(0, outputH));
mesh.Add(torch.arange(0, outputW));
var retMesh = torch.meshgrid(mesh);

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at TorchSharp.PInvoke.LibTorchSharp.THSTensor_meshgrid(IntPtr, Int64, System.String, TorchSharp.AllocatePinnedArray)
--------------------------------
   at TorchSharp.torch.meshgrid(System.Collections.Generic.IEnumerable`1<Tensor>, System.String)
   at MicroDet.PostProcess.DecodeBox(Tensor, Tensor, Tensor, Double)
   at MicroDet.Program.test()
   at MicroDet.Program.Main()

**Comment by williamlzw** [comment]
The solution is as follows:
List<torch.Tensor> list = new List<torch.Tensor>();
int outputH = 128;
int outputW = 128;
list.Add(torch.arange(0, outputH));
list.Add(torch.arange(0, outputW));
var all = torch.cat(list, 0).contiguous();
var mesh = all.split(128);
var retMesh = torch.meshgrid(mesh);

**Comment by NiklasGustafsson** [comment]
@williamlzw -- are you still seeing this problem manifested?

**Comment by williamlzw** [comment]
torchsharp 0.100.5 doesn't seem to report errors anymore.
