### ISSUE TITLE
jit saving in python and loading in C# issue

### ISSUE THREAD

**Issue by ryanshrott** [dotnet/TorchSharp#925]
I am trying to compile and save a torch function in python and then load it later in C#, however, I get an error. 

Here is a minimal example:
Python code:

```
import torch
 
def get_bucket_indices(buckets, x):
    indices = torch.searchsorted(buckets, x)
    indices = torch.clamp(indices - 1, 0, buckets.shape[0] - 2)
    return indices
 
# Save the module to a file
torch.jit.script(get_bucket_indices).save('file.pt')

```

C# code:
```
using System;
using TorchSharp;
using static TorchSharp.torch;
 
...
 
var module = torch.jit.load('file.pt')
// Call the get_bucket_indices method
var buckets = torch.arange(0, 10, 1);
var x = torch.tensor(new float[] { 2, 3, 5, 8 });
var indices = module.invoke("get_bucket_indices", buckets, x)

```

Error message: 
In this example, the module.get_bucket_indices call will result in a System.Runtime.InteropServices.ExternalException with the message "Method 'get_bucket_indices' is not defined." This suggests that there might be an issue with how the module is defined or saved in the Python code.
 
How can I fix this issue? What am I doing wrong?

**Comment by NiklasGustafsson** [comment]
If the script module was created from a function rather than a module, I think you just call 'forward()' on the module. Something like:

```C#
var indices = module.forward(buckets,x);
```

**Comment by NiklasGustafsson** [comment]
I think it's mentioned (not very prominently, but still) in: https://github.com/dotnet/TorchSharp/wiki/TorchScript

**Comment by lindadamama** [comment]
I have also encountered the problem you mentioned. After changing the API, I can save the model normally
![Uploading 123.png…]()

**Comment by ryanshrott** [comment]
@NiklasGustafsson - Thank you -- it worked! 

One weird thing I encountered is that torch.jit.load(filePath) is slow in C# -- it takes 800ms for me! On the other hand, pytorch can load the file in 6ms. How can that be?

**Comment by NiklasGustafsson** [comment]
Is it as slow a second time? It could just be how .NET works, where the first time something is called, it compiles it. Regardless, loading a TorchScript file isn't something you do over and over, so the cost shouldn't be too bad, right?
