### ISSUE TITLE
torch.equal missing

### ISSUE THREAD

**Issue by toolgood** [dotnet/TorchSharp#928]
url : https://github.com/hpcaitech/ColossalAI/blob/main/applications/ChatGPT/tests/test_data.py

``` py
def gather_and_equal(tensor: torch.Tensor) -> bool:
    world_size = dist.get_world_size()
    outputs = [torch.empty_like(tensor) for _ in range(world_size)]
    dist.all_gather(outputs, tensor.contiguous())
    for t in outputs[1:]:
        if not torch.equal(outputs[0], t): # this
            return False
    return True
```

**Comment by GeorgeS2019** [comment]
@toolgood 
Do you have a plan to use [PyToCs](https://github.com/toolgood/pytocs) to parse the PyTorch codes in the folder e.g. [ChatGPT](https://github.com/hpcaitech/ColossalAI/blob/main/applications/ChatGPT) to identify a list of `missing TorchSharp implementations`?

**Comment by toolgood** [comment]
@GeorgeS2019   There are many changes in ColossalAI code. When the code is stable, consider converting it to csharp code.
