### ISSUE TITLE
The output of the scriptmodule loaded by torchsharp is different from that directly output by python

### ISSUE THREAD

**Issue by lindadamama** [dotnet/TorchSharp#929]
![捕获](https://user-images.githubusercontent.com/48863486/220046537-f7ead8e3-d59b-4394-b52f-18e12ce19d8d.PNG)
On the left is the output of python, and on the right is the output of torchsharp
The height of the picture is 320, and the width of the picture is 256

[Segformer](https://github.com/bubbliiiing/segformer-pytorch)
After I trained the model with the Segformer network, I exported the ScriptModule through python, and then input the same image for testing. python and torchsharp output two different results

I tried to use method 1 to export the model program and kept reporting errors, so I chose method 2, which works normally, but the test results are inconsistent
method 1

```Python

        example = torch.rand(1, 3, 256, 320)
        # Use torch.jit.trace to generate a torch.jit.ScriptModule via tracing.
        traced_script_module = torch.jit.script(self.net)
        traced_script_module.save("model.pt")

```
err Code：

  TypeError: TypeError: cannot create weak reference to 'numpy.ufunc' object

method 2

```Python

        example = torch.rand(1, 3, 256, 320)
        # Use torch.jit.trace to generate a torch.jit.ScriptModule via tracing.
        traced_script_module = torch.jit.trace(self.net,example)
        traced_script_module.save("model.pt")

```

**Comment by GeorgeS2019** [comment]
@lindadamama 
Thx for sharing, we wish this 2 years ago, it is great to see more users are applying TorchSharp and we could see WHERE we need to improve further and closing on the GAPS!  Great job!

**Comment by lindadamama** [comment]
I have an idea. I don't know whether it is feasible or not. Can we let torchsharp support more kinds of models, such as the models accelerated by onnx and TensorRT? Your work is very good
To export the model with torch.jit.script, I have tried five types of semantic segmentation networks, none of which can be exported correctly using this API. I know the difference between torch.jit.script and torch.jit.trace by searching the forum, but I have no way to solve it for the time being
You can only export through the method of torch. jit. trace, but I don't get the desired result

**Comment by NiklasGustafsson** [comment]
Are you comparing the result when loading the script file into Python and TorchSharp, or between the original Pytorch model and loading the script.

In other words are you:

1. Using an unsaved model in Python vs. the loaded model in TorchSharp.

or 

2. Saving the model after tracing, loading it again in Python, and then comparing against loading in TorchSharp.

**Comment by lindadamama** [comment]
It is obviously a problem with the model exported by Python. I checked some websites. It seems that complex models can only be exported by using torch.jit.trace. If you use torch.jit.script, you may need to modify the python code, or it is not as easy to use as the simple torch.jit.script (model). save ("model. dat") in your example
Because I checked the issue, it seems that other people have met the same problem

**Comment by NiklasGustafsson** [comment]
Unfortunately, using tracing will sometimes modify the logic of the model, especially if it contains conditional statements, loops, etc., so you don't always get a high-fidelity script out of it. In that case, the only option is to port the model logic to .NET from the Python source code, and then just save and load the weights:

https://github.com/dotnet/TorchSharp/wiki/Sharing-Model-Data-between-PyTorch-and-TorchSharp

**Comment by lindadamama** [comment]
Can torchsharp load models in other formats? For example, onnx format or TensorRt format

**Comment by NiklasGustafsson** [comment]
There's already support for loading ONNX models in .NET, but it has nothing to do with TorchSharp.

**Comment by lindadamama** [comment]
Thank you very much for your answer
