### ISSUE TITLE
Revisit: torch. save and torch. load

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/TorchSharp#930]
> - [ ] [https://github.com/dotnet/TorchSharp/issues/862](https://github.com/dotnet/TorchSharp/issues/862)
> - [ ] [https://github.com/dotnet/TorchSharp/issues/785](https://github.com/dotnet/TorchSharp/issues/785)
> - [ ] [https://github.com/dotnet/TorchSharp/issues/551](https://github.com/dotnet/TorchSharp/issues/551)

The dotnet team: .NET for spark used **Pyrolite** to address [**pickle protocol**](https://github.com/irmen/Pyrolite) to interoperate with python

## Pyrolite

![image](https://user-images.githubusercontent.com/49812372/220086742-0bc9ce3d-ac53-416b-a338-0e6511720d8e.png)

**Comment by GeorgeS2019** [comment]
> Will it be supported in the future?
Python has a [pickle function library](https://docs.python.org/3/library/pickle.html), which can easily save the state of the object
However, this seems to require support from the dotnet team. I think this feature is useful in the field of machine learning

@ChengYen-Tang

**Comment by ChengYen-Tang** [comment]
@GeorgeS2019 
I did a quick read of the code for this library and I don't think it fits our needs. This library is only suitable for data objects.

**Comment by GeorgeS2019** [comment]
@ChengYen-Tang  thx for checking this out. :-)

**Comment by GeorgeS2019** [comment]
@ChengYen-Tang 
@NiklasGustafsson 


https://github.com/irmen/pickle

### Python to .NET (unpickling)

The unpickler simply returns an object. In the case of C#, that is a statically typed
language so you will have to cast that to the appropriate type. Refer to this
table to see what you can expect to receive. Tip: you can use the 'dynamic' type 
in some places to avoid excessive type casting.


PYTHON              | .NET
--------------------|-------------
None                | null
bool                | bool
int                 | int
long                | long (c# doesn't have BigInteger so there's a limit on the size)
string              | string
unicode             | string
complex             | Razorvine.Pickle.Objects.ComplexNumber
datetime.date       | DateTime
datetime.datetime   | DateTime
datetime.time       | TimeSpan
datetime.timedelta  | TimeSpan
float               | double
array.array         | array (all kinds of element types supported)
list                | ArrayList (of objects)
tuple               | object[]
set                 | HashSet<object>
dict                | Hashtable (key=object, value=object)
bytes               | ubyte[]
bytearray           | ubyte[]
decimal             | decimal (except NaN which is mapped to double.NaN)
custom class        | IDictionary<string, object>  (dict with class attributes including its name in "__class__")
Pyro4.core.URI      | Razorvine.Pyro.PyroURI
Pyro4.core.Proxy    | Razorvine.Pyro.PyroProxy
Pyro4.errors.*      | Razorvine.Pyro.PyroException
Pyro4.utils.flame.FlameBuiltin    | Razorvine.Pyro.FlameBuiltin 
Pyro4.utils.flame.FlameModule     | Razorvine.Pyro.FlameModule 
Pyro4.utils.flame.RemoteInteractiveConsole   | Razorvine.Pyro.FlameRemoteConsole 


### .NET to Python (pickling)


.NET                | PYTHON
--------------------|---------------
null                | None
boolean             | bool
byte                | byte
sbyte               | int
char                | str/unicode (length 1)
string              | str/unicode
double              | float
float               | float
int/short/sbyte     | int
uint/ushort/byte    | int
decimal             | decimal
byte[]              | bytearray
primitivetype[]     | array
object[]            | tuple  (cannot contain self-references)
DateTime            | datetime.datetime
TimeSpan            | datetime.timedelta
Enum                | just the enum value as string
HashSet             | set
Map, Hashtable      | dict
Collection          | list
Enumerable          | list
object with public properties      | dictionary of those properties + __class__
anonymous class type        | dictonary of the public properties
Razorvine.Pyro.PyroURI      | Pyro4.core.URI
Razorvine.Pyro.PyroProxy    | cannot be pickled.

previously I suggested
https://github.com/irmen/Pyrolite

**Comment by NiklasGustafsson** [comment]
Unless I have completely misunderstood, unpickling Python objects with any .NET unpickling library will not restore the logic of the logic of the methods on the object, only the data. Also, a Python custom class, which is what all modules are, will come out as an IDictionary<string,object>, which is not what we want or need.

Pickling is a Python-specific serialization format, one that requires the Python VM at runtime in order to work fully. Partial solutions for .NET are available, but will not meet the needs of TorchSharp.

**Comment by NiklasGustafsson** [comment]
@GeorgeS2019 - can we close this?
