### ISSUE TITLE
SummaryWriter is not fully functional

### ISSUE THREAD

**Issue by ChengYen-Tang** [dotnet/TorchSharp#932]
https://pytorch.org/docs/stable/tensorboard.html#torch.utils.tensorboard.writer.SummaryWriter

I want to implement this function, but need your assistance. Thanks.
https://github.com/DLR-RM/stable-baselines3/blob/085bdd5a68be7748e62ca710162f16ac7b62ddfc/stable_baselines3/common/logger.py#L400

**Comment by NiklasGustafsson** [comment]
Already tracked in:

https://github.com/dotnet/TorchSharp/issues/728

**Comment by NiklasGustafsson** [comment]
A contribution with the missing functions will be welcomed. :-)

**Comment by NiklasGustafsson** [comment]
BTW, @ChengYen-Tang, since you've reported issues with 0.99.2 -- 0.99.3 is out on NuGet, now.

**Comment by ChengYen-Tang** [comment]
I don't know Tensorboard format so can't understand the code.😰😨😭

**Comment by ChengYen-Tang** [comment]
I need help hahaha
Can you help me with these components?
https://github.com/pytorch/pytorch/blob/master/torch/utils/tensorboard/summary.py#L9-L16

https://github.com/dotnet/TorchSharp/blob/main/src/TorchSharp/Utils/tensorboard/protobuf/Summary.cs

**Comment by NiklasGustafsson** [comment]
@ChengYen-Tang -- I was sent some emails with comments, which you must have deleted. 

The TB format is complicated, and needs to be reverse-engineered. I found the TB source code helpful, but not sufficient, and so I had to re-learn to use the binary file viewer in VS... 

Lots of hex-decimal-hex conversion involved... :-)

**Comment by ChengYen-Tang** [comment]
> @ChengYen-Tang -- I was sent some emails with comments, which you must have deleted.
> 
> The TB format is complicated, and needs to be reverse-engineered. I found the TB source code helpful, but not sufficient, and so I had to re-learn to use the binary file viewer in VS...
> 
> Lots of hex-decimal-hex conversion involved... :-)

I found another solution 🤣

**Comment by ChengYen-Tang** [comment]
@NiklasGustafsson,
Can I install [NumpyDotNet](https://github.com/Quansight-Labs/numpy.net) to TorchSharp?

When I saw these code, my head was painful😭
https://github.com/pytorch/pytorch/blob/master/torch/utils/tensorboard/summary.py#L338-L411

**Comment by NiklasGustafsson** [comment]
No, that is not an acceptable dependency to introduce.

**Comment by ChengYen-Tang** [comment]
Maybe I can achieve the same functionality using torch.
These are the features I found missing.

#939 
#940

**Comment by ChengYen-Tang** [comment]
@NiklasGustafsson,

add_hparams needs your help to add these components
https://github.com/pytorch/pytorch/blob/master/torch/utils/tensorboard/summary.py#L95-L114

**Comment by ChengYen-Tang** [comment]
Do you have an image processing library that you recommend, because we need to draw boxes in pictures.
https://github.com/pytorch/pytorch/blob/master/torch/utils/tensorboard/summary.py#L464-L506

https://github.com/SixLabors/ImageSharp

**Comment by NiklasGustafsson** [comment]
>> Do you have an image processing library that you recommend?

As a dependency for TorchSharp? We've taken a dependency on SkiaSharp for reading and writing images.

If you're looking for a general recommendation, ImageSharp is also good, and runs everywhere, since it's pure .NET (Skia has native components).

**Comment by GeorgeS2019** [comment]
@ChengYen-Tang 
We had this discussion before and why the SkiaSharp with `MIT license` is a better choice than the ImageSharp with `Six Labors Split License.`

**Comment by ChengYen-Tang** [comment]
@NiklasGustafsson @GeorgeS2019,

I have a problem, SkiaSharp can't combine multiple images into one gif
add_video() store gif as base64 string

**Comment by ChengYen-Tang** [comment]
If we want to achieve this function, I feel that ImageSharp is more convenient.
TorchSharp is an open source project and should be available unconditionally?

![image](https://user-images.githubusercontent.com/32535494/222391908-f510d472-90ac-4047-9014-0ae2cd6fd3fe.png)

**Comment by GeorgeS2019** [comment]
@mattleibow 

> I have a problem, SkiaSharp can't combine multiple images into one gif

Hi Matthew,  do we have a solution to use SkiaSharp to combine multiple images into on gif?

Ideally, a MIT SkiaSharp project is a better choice.

**Comment by GeorgeS2019** [comment]
@ChengYen-Tang 
Will this [issue ](https://github.com/mono/SkiaSharp/issues/237) helps?

**Comment by GeorgeS2019** [comment]
@mattleibow 

WIth you here, could you share if you know any project uses SkiaSharp to create image or/and gif outputs for the dotnet polyglot notebook?

**Comment by ChengYen-Tang** [comment]
> @ChengYen-Tang Will this issue: [AnimatedGifEncoder.cs](https://github.com/avianbc/NGif/blob/master/Components/AnimatedGifEncoder.cs) ([mono/SkiaSharp#1130 (comment)](https://github.com/mono/SkiaSharp/issues/1130#issuecomment-584370903)) helps?

@GeorgeS2019,
Thanks, this is very helpful.

**Comment by NiklasGustafsson** [comment]
> If we want to achieve this function, I feel that ImageSharp is more convenient. TorchSharp is an open source project and should be available unconditionally?
> 
> https://sixlabors.com/posts/license-changes/#questions-and-answers ![image](https://user-images.githubusercontent.com/32535494/222391908-f510d472-90ac-4047-9014-0ae2cd6fd3fe.png)

.NET Foundation, of which TorchSharp is a part, only works with dependencies on projects with OSI-approved licenses. See this blog post:

https://old.dotnetfoundation.org/blog/2022/10/20/imagesharpupdate

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson 

We had this discussion before. When the future .NET (e.g. .NET7) looking for a replacement for a cross-platform option for System. Drawing to e.g. Linux, ImageSharp was dropped. If I am not wrong.

**Comment by GeorgeS2019** [comment]
[System.Drawing.Common only supported on Windows](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only)

**Comment by ChengYen-Tang** [comment]
> > @NiklasGustafsson, Can I install [NumpyDotNet](https://github.com/Quansight-Labs/numpy.net) to TorchSharp?
> > When I saw these code, my head was painful😭 https://github.com/pytorch/pytorch/blob/master/torch/utils/tensorboard/summary.py#L338-L411
> 
> Maybe I can achieve the same functionality using torch. These are the features I found missing.
> 
> #939 #940



> @NiklasGustafsson,
> 
> add_hparams needs your help to add these components https://github.com/pytorch/pytorch/blob/master/torch/utils/tensorboard/summary.py#L95-L114

Hi @NiklasGustafsson,
I need your help for the remaining two tasks
<img width="114" alt="image" src="https://user-images.githubusercontent.com/32535494/222743232-8bb375ac-45cd-4471-af15-e3a6b4f489ce.png">

**Comment by NiklasGustafsson** [comment]
I'll take a look.
