### ISSUE TITLE
nn.ReplicationPad1d(long[] padding)   miss

### ISSUE THREAD

**Issue by toolgood** [dotnet/TorchSharp#942]
url|: https://github.com/yuqinie98/PatchTST/blob/main/PatchTST_supervised/layers/PatchTST_backbone.py#L37
``` py
    self.padding_patch_layer = nn.ReplicationPad1d((0, stride)) 
```

`TorchSharp`  Method definition
``` cs
            public static ReplicationPad1d ReplicationPad1d(long padding)
```

**Comment by NiklasGustafsson** [comment]
A whole bunch of ***Pad modules are missing the tuple-version. Fixing them all at once.
