### ISSUE TITLE
How can I limit the usage of cuda memory to avoid CUDA out of memory.

### ISSUE THREAD

**Issue by toolgood** [dotnet/TorchSharp#950]
System.Runtime.InteropServices.ExternalException:“CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 23.99 GiB total capacity; 21.46 GiB already allocated; 0 bytes free; 23.18 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception raised from malloc at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\c10\cuda\CUDACachingAllocator.cpp:704 (most recent call first):
00007FFB7D5CAD0200007FFB7D5CACA0 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FFB7D59524500007FFB7D5951D0 c10.dll!c10::OutOfMemoryError::OutOfMemoryError [<unknown file> @ <unknown line number>]
00007FFB7D63DC8400007FFB7D63C1D0 c10_cuda.dll!c10::cuda::CUDACachingAllocator::init [<unknown file> @ <unknown line number>]
00007FFB7D63DD0700007FFB7D63C1D0 c10_cuda.dll!c10::cuda::CUDACachingAllocator::init [<unknown file> @ <unknown line number>]
00007FFB7D6216F0 <unknown symbol address> c10_cuda.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFAD36B16F100007FFAD36B1620 torch_cpu.dll!at::detail::empty_generic [<unknown file> @ <unknown line number>]
00007FFB7DA3DD9200007FFB7DA3DCA0 torch_cuda_cpp.dll!at::detail::empty_cuda [<unknown file> @ <unknown line number>]
00007FFB7DA3DBC200007FFB7DA3DA80 torch_cuda_cpp.dll!at::detail::empty_cuda [<unknown file> @ <unknown line number>]
000001F9CA76722F000001F9CA740370 torch_cuda_cu.dll!at::cuda::set__symint [<unknown file> @ <unknown line number>]
00007FFAD36DFF2D00007FFAD36DFA10 torch_cpu.dll!at::TensorIteratorBase::fast_set_up [<unknown file> @ <unknown line number>]
00007FFAD36DBF6700007FFAD36DBEE0 torch_cpu.dll!at::TensorIteratorBase::build [<unknown file> @ <unknown line number>]
00007FFAD36DC58000007FFAD36DC490 torch_cpu.dll!at::TensorIteratorBase::build_borrowing_binary_op [<unknown file> @ <unknown line number>]
000001F9CA8386F9000001F9CA7E32E0 torch_cuda_cu.dll!at::cuda::where_outf [<unknown file> @ <unknown line number>]
000001F9CA72863F000001F9CA6E6010 torch_cuda_cu.dll!at::cuda::bucketize_outf [<unknown file> @ <unknown line number>]
00007FFAD3F4AA0800007FFAD3F4A980 torch_cpu.dll!at::_ops::mul_Tensor::redispatch [<unknown file> @ <unknown line number>]
00007FFAD53FF71500007FFAD53B6BD0 torch_cpu.dll!torch::autograd::GraphRoot::apply [<unknown file> @ <unknown line number>]
00007FFAD53C9C3A00007FFAD53B6BD0 torch_cpu.dll!torch::autograd::GraphRoot::apply [<unknown file> @ <unknown line number>]
00007FFAD3EDC24A00007FFAD3EDC0D0 torch_cpu.dll!at::_ops::mul_Tensor::call [<unknown file> @ <unknown line number>]
00007FFAD36762C400007FFAD36762B0 torch_cpu.dll!at::Tensor::mul [<unknown file> @ <unknown line number>]
00007FFB68008A3700007FFB680089C0 LibTorchSharp.DLL!THSTensor_mul [<unknown file> @ <unknown line number>]
00007FFB093A0633 <unknown symbol address> !<unknown symbol> [<unknown file> @ <unknown line number>]
”

**Comment by toolgood** [comment]
I don't know why the memory of the graphics card can work normally when I run python code. After I convert it to C # code, the memory of the graphics card is not enough.

python code:  https://github.com/thuml/Autoformer

csharp code:  https://github.com/toolgood/OtherFiles/tree/master/ToolGood.SoarSky.StockFormer

**Comment by toolgood** [comment]
run csharp code 


![图片](https://user-images.githubusercontent.com/17310407/224323910-ea282b25-8c9f-40ac-9047-64cec9547e5f.png)

**Comment by NiklasGustafsson** [comment]
The first step is to try 'Technique 3' outlined in this article: https://github.com/dotnet/TorchSharp/wiki/Memory-Management.

**Comment by toolgood** [comment]
@NiklasGustafsson  thank you
