### ISSUE TITLE
Module State Dictionary not being generated properly for custom modules.

### ISSUE THREAD

**Issue by TheBlackPlague** [dotnet/TorchSharp#958]
The module state dictionary isn't generated properly. In PyTorch, one only has to set the modules to some instance variables, but that doesn't work in TorchSharp. 

This should be something already implemented via the use of Reflection to find all variables of type `nn.Module`, and call relevant state dictionary methods on them.

**Comment by NiklasGustafsson** [comment]
Are you calling RegisterComponents() after setting all the instance variables referring to submodules? There's no way to hook the end of a constructor in .NET, and the base class constructor is called first, so you have to have an explicit call to detect and register all the modules.

**Comment by TheBlackPlague** [comment]
> Are you calling `RegisterComponents()` after setting all the instance variables referring to submodules? There's no way to hook the end of a constructor in .NET, and the base class constructor is called first, so you have to have an explicit call to detect and register all the modules.
> 
> https://github.com/dotnet/TorchSharp/wiki/Creating-Your-Own-TorchSharp-Modules
> 
> Also, if you use dictionaries or lists of sub-modules, they must be `ModuleDict` and `ModuleList`, otherwise `RegisterComponents()` will miss them. Furthermore, the fields (instance variables) must be `private` to the class.

Right. I see; that's my bad. I ended up overwriting the `state_dict()` method to solve the issue.
