### ISSUE TITLE
Mismatch during loading and saving of model

### ISSUE THREAD

**Issue by Sprinzl** [dotnet/TorchSharp#963]
Hello I have a mismatch of saving and loading the model...

System.ArgumentException
  HResult=0x80070057
  Nachricht = Mismatched state_dict sizes: expected 54, but found 80 entries.
  Quelle = TorchSharp
  Stapelüberwachung:
   bei TorchSharp.torch.nn.Module.load(BinaryReader reader, Boolean strict, IList`1 skip)
   bei TorchSharp.torch.nn.Module.load(String location, Boolean strict, IList`1 skip)
   bei QT.Torch.Model.Attention.TimeEncoder.TrainStock() in D:\Projects\QT\Torch\Model\Attention\TimeEncoder.cs: Zeile166

the class looks like this...

 public class TimeEncoder : nn.Module
    {
        int dim_model;
      // TorchSharp.Modules.TransformerEncoder transformer;
        Linear input;
        Linear output;
        PositionalEncoding positional_encoder;
        TransformerEncoderLayer el01;
        TransformerEncoderLayer el02;
        TransformerEncoderLayer el03;
        TransformerEncoderLayer el04;
        Tensor sqrtmodeldim;
        public TimeEncoder(int features, int dim_model, int nhead,long forward, double dropout_p) : base(nameof(TimeEncoder))
        {
            //INFO
            this.dim_model = dim_model;
            //Layers
            this.positional_encoder = new PositionalEncoding(dim_model: dim_model, dropout_p: dropout_p, max_len: 2000);
            this.input = nn.Linear(features, dim_model);
            nn.ModuleList<TransformerEncoderLayer>();

            var l = new List<TransformerEncoderLayer>();

            el01 = nn.TransformerEncoderLayer(dim_model, nhead, forward, dropout_p);
            el02 = nn.TransformerEncoderLayer(dim_model, nhead, forward, dropout_p);
            el03 = nn.TransformerEncoderLayer(dim_model, nhead, forward, dropout_p);
            el04 = nn.TransformerEncoderLayer(dim_model, nhead, forward, dropout_p);
    
            this.output = nn.Linear(dim_model, features);
            this.sqrtmodeldim= ((Tensor)Math.Sqrt((float)this.dim_model)).to(device: "Cuda");
            this.RegisterComponents();
        }

**Comment by dje-dev** [comment]
As noted by Niklas in another issue, "ModuleList and ModuleDict are primarily used to trigger automatic registration of the modules that are held by them, i.e. during module construction."

I have a suspicion that because List is used here, the RegisterComponents is unable to see the nested layers and properly register them. Therefore I suggest you try with a ModuleList instead of List and see if that might fix the problem.

**Comment by NiklasGustafsson** [comment]
You should always wait until after the call to `RegisterComponents` to move anything to CUDA.

**Comment by NiklasGustafsson** [comment]
@Sprinzl -- is this still a problem for you? If so, please confirm that you are building all the layers on CPU, registering components, and then moving them to CUDA.

**Comment by Sprinzl** [comment]
@NiklasGustafsson No Problem - Solved - as you said. On Top of it i had some issues with the discope sope. Also solved. Your API is really nice.
