### ISSUE TITLE
How to get layers including  "add layer" and other

### ISSUE THREAD

**Issue by JurajJakubov** [dotnet/TorchSharp#969]
Hi, 

I am little bit confused how to get all possible layers from mode.

```
var model = jit.load(filename);
var modules = model.named_modules();
```

with this code I can get all layers but only convolution layer
![image](https://user-images.githubusercontent.com/43072838/228653851-531225e9-4fd9-4b6e-9fcc-3754a6c8ec76.png)

But when I look inside visualisation of network i can see silu and add layers too.
![image](https://user-images.githubusercontent.com/43072838/228653974-50012018-ed93-4080-8d88-2c08d9e5bc63.png)

I will be very thankful if somebody can point me where can I see that connections and layer like "add layer". 

I think name in act should not be null.
![image](https://user-images.githubusercontent.com/43072838/228668037-60f313bb-53bf-450f-958d-d8bd524ccbb8.png)

Thanks and best regards,
Juro

**Comment by NiklasGustafsson** [comment]
ScriptModule.named_modules is implemented as a very thin layer on top of the native code in libtorch that loads and controls the TorchScript model. For JIT, the TorchSharp API doesn't do much of anything except pass data back and forth to native code, so what you are seeing is that libtorch found.

**Comment by JurajJakubov** [comment]
Ou okay. Now I am not sure exactly what to do. Does it mean i cant extract that data in c# at this point? Because I can easily do it in python like this for example and get even silu and add blocks.

```
model = torch.jit.load('best5.torchscript')
layers = []
for name, module in model.named_modules():
    layers.append((name, module))
print(layers)
```
Problem is that is different language.

**Comment by JurajJakubov** [comment]
ModelProtto seems to work from onnxSharp
