### ISSUE TITLE
is there ppo example by torchsharp?

### ISSUE THREAD

**Issue by diybl** [dotnet/TorchSharp#981]
is there ppo example by torchsharp?

**Comment by GeorgeS2019** [comment]
@ChengYen-Tang [WIP: PPO](https://github.com/ChengYen-Tang/RL.Algorithm/issues/4#issuecomment-1469162584)

**Comment by GeorgeS2019** [comment]
@diybl 
@ChengYen-Tang 
[Deel RL using TorchSharp for Deep Learning](https://github.com/xin-pu/DeepSharp/issues/4#issue-1754535588)

**Comment by GeorgeS2019** [comment]
FYI: @NiklasGustafsson
# WIP: TorchSharp for Deep QLearning
https://github.com/xin-pu/DeepSharp/discussions/10

![Items](https://github.com/dotnet/TorchSharp/assets/49812372/2c87042c-c4e1-48a6-9a7c-cef7e7494d43)


# WIP: Deep RL using TorchSharp

```mermaid
mindmap
  root((Reinforcement<br/>Learning))
    Definitions
      Interactions
          Environment
          Agent
      Elements
         State
         Action
         Strategy<br/>策略
             Deterministic Policy<br/>确定性策略
             Stochastic Policy<br/>随机性策略
         State transfer probability<br/>状态转移概率
         Rewards<br/>即时奖励
      Others
        Episodes
        Trial
        Continuing Tasks
    Policy
      Policy based learning
      Value based learning
        Monte Carlo learning
             Temporal Difference Learning
                 SARSA<br/>State Action Reward State Action
                 QLearning
        Dynamic programming learning
            Policy iteration algorithm
                Policy Evaluation
                Policy Improvement
            Value iteration algorithm
    Markov Decision Process
      Markov Decision Process<br/>马尔科夫决策过程
           Trajectory<br/>轨迹
      Markov Process<br/>马尔科夫过程
   Objective Functions
```

**Comment by GeorgeS2019** [comment]
@diybl
@ChengYen-Tang
@NiklasGustafsson <= dotnet team
@xin-pu

This is done => Now with WinForm UI and Winform Chat to monitor training progress
**RL_Matrix** => nuget Gym.NET using TorchSharp

@asieradzk

https://github.com/asieradzk/RL_Matrix/issues/1#issuecomment-1691274872

**Comment by asieradzk** [comment]
Yup. I'm hot on brining RL Matrix to Godot, particularly to flex on Unity's ML Agents.
Ideally I'd like to have at last: DDPG, Rainbow, Deep-MCTS (AlphaZero) on top of DQN and PPO

Please give me architecture advice on how you'd like environment/agent creation implemented, I am basing my current version on how matlab does it to allow easy swapping of agents/environments.

**Comment by GeorgeS2019** [comment]
@asieradzk 

Here, we only work on MIT FOSS license

**Comment by asieradzk** [comment]
> @asieradzk
> 
> Here, we only work on MIT FOSS license

Thank you, great to hear. I will see about license change once I am done with Godot RL agents. Hopefully I find some time in the next weeks in-between working on my PhD.

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson 

cc this [issue ](https://github.com/dotnet/machinelearning/issues/6484#issuecomment-1740005058)

**Comment by GeorgeS2019** [comment]
Related [issue](https://github.com/dotnet/TorchSharp/issues/1100)
