### ISSUE TITLE
Different versions of System.Memory between build and package creation.

### ISSUE THREAD

**Issue by michaelgsharp** [dotnet/TorchSharp#987]
The [.nupkgproj](https://github.com/dotnet/TorchSharp/blob/13919122a310bc6bca7590757141de01bc5108d4/pkg/TorchSharp/TorchSharp.nupkgproj#L13) file references System.Memory version 4.5.3, while the actual [.csproj ](https://github.com/dotnet/TorchSharp/blob/13919122a310bc6bca7590757141de01bc5108d4/src/TorchSharp/TorchSharp.csproj#L34) references System.Memory version 4.5.5. Since the build version is higher than the package version, end users have to manually reference System.Memory 4.5.5 to be able to use TorchSharp.

While the .nupkgproj are probably needed for the packages that are being chunked, you should be able to build the TorchSharp package directly from the .csproj and remove the .nupkgproj which would make this a non issue in the future. Otherwise the versions will have to be kept in sync.

**Comment by NiklasGustafsson** [comment]
@michaelgsharp -- thanks for discovering this. It should be an easy fix. I also noted that SkiaSharp and SharpZipLib are dependencies, but not noted in .nupkgproj. Presumably, they should be added.

**Comment by NiklasGustafsson** [comment]
Since this is a fairly serious problem, I will do an "emergency" release of 0.99.6 after this is taken care of.
