### ISSUE TITLE
Debugging with  enable anomaly detection torch.autograd.set_detect_anomaly(True)

### ISSUE THREAD

**Issue by Sprinzl** [dotnet/TorchSharp#989]
Helloo,
Is it possible to implement torch.autograd.set_detect_anomaly(True). I have some fancy inplace operation error. 
Or is this the reflected Get Set.. no idea.

thanks in advance
Michael Sprinzl

**Comment by NiklasGustafsson** [comment]
@Sprinzl -- this will be in the next release.

**Comment by NiklasGustafsson** [comment]
@Sprinzl  -- released with 0.100.0, now on NuGet

**Comment by Sprinzl** [comment]
Yes ... this libary will render python obsolete. If I would have time, I would make Rhino3d grasshopper the tensorboard killer. Thank you @NiklasGustafsson

**Comment by NiklasGustafsson** [comment]
> Yes ... this libary will render python obsolete.

Not a goal, exactly, but I appreciate the enthusiasm! :-)
